<?php
$myForm = $this->myForm;
$myForm->prepare();
$elementId			= $myForm->get('id');
$elementName 		= $myForm->get('name');
$elementNormal		= $myForm->get('normal');
$elementVip			= $myForm->get('vip');
$elementHot			= $myForm->get('hot');
$elementFree		= $myForm->get('free');
$elementChinhchu	= $myForm->get('chinhchu');
$elementPrice		= $myForm->get('price');
$image        = (!empty($this->item->images))  ? UPLOAD_URL .'/news/'.$this->item->images :  TEMPLATE_URL .'/admin/images/NoImage.jpg';



$elements = array(
	array(
		'label'				=>	$this->formLabel($elementName),
		'input'				=>	$this->formElement($elementName),
		'class'				=>	'col-sm-9',
		'required'			=>	'*',
		'tooltiptitle'		=>	'Tên dịch vụ',
		'tooltipmessage'	=>	'Nhập Tên dịch vụ',
	),
	array(
		'label'				=>	$this->formLabel($elementNormal),
		'input'				=>	$this->formElement($elementNormal),
		'class'				=>	'col-sm-9',
		'required'			=>	'*',
		'tooltiptitle'		=>	'Số tin thường Kích hoạt',
		'tooltipmessage'	=>	'Nhập Số tin thường Kích hoạt',
	),
	array(
		'label'				=>	$this->formLabel($elementNormal),
		'input'				=>	$this->formElement($elementNormal),
		'class'				=>	'col-sm-9',
		'required'			=>	'*',
		'tooltiptitle'		=>	'Số tin thường Kích hoạt',
		'tooltipmessage'	=>	'Nhập Số tin thường Kích hoạt',
	),
	array(
		'label'				=>	$this->formLabel($elementVip),
		'input'				=>	$this->formElement($elementVip),
		'class'				=>	'col-sm-9',
		'required'			=>	'*',
		'tooltiptitle'		=>	'Số tin VIP Kích hoạt',
		'tooltipmessage'	=>	'Nhập Số tin VIP Kích hoạt',
	),
	array(
		'label'				=>	$this->formLabel($elementHot),
		'input'				=>	$this->formElement($elementHot),
		'class'				=>	'col-sm-9',
		'required'			=>	'*',
		'tooltiptitle'		=>	'Số tin HOT Kích hoạt',
		'tooltipmessage'	=>	'Nhập Số tin HOT Kích hoạt',
	),
	array(
		'label'				=>	$this->formLabel($elementFree),
		'input'				=>	$this->formElement($elementFree),
		'class'				=>	'col-sm-9',
		'required'			=>	'*',
		'tooltiptitle'		=>	'Số tin Miễn phí Kích hoạt',
		'tooltipmessage'	=>	'Nhập Số tin Miễn phí Kích hoạt',
	),
	array(
		'label'				=>	$this->formLabel($elementChinhchu),
		'input'				=>	$this->formElement($elementChinhchu),
		'class'				=>	'col-sm-9',
		'required'			=>	'*',
		'tooltiptitle'		=>	'Số tin Chính chủ Kích hoạt',
		'tooltipmessage'	=>	'Nhập Số tin Chính chủ Kích hoạt',
	),
	array(
		'label'				=>	$this->formLabel($elementPrice),
		'input'				=>	$this->formElement($elementPrice),
		'class'				=>	'col-sm-9',
		'required'			=>	'*',
		'tooltiptitle'		=>	'Giá dịch vụ / tháng',
		'tooltipmessage'	=>	'Nhập Giá dịch vụ / tháng',
	),
	
	
	
	
	
);

$messagesErrors = $this->elementErrors(array(
	'name'					=>	$elementName,
	'normal'				=>	$elementNormal,
	'vip'					=>	$elementVip,
	'hot'					=>	$elementHot,
	'free'					=>	$elementFree,
	'chinhchu'				=>	$elementChinhchu,
	'price'					=>	$elementPrice,
));



?>


<form name="appForm" id="appForm" method="post" action="" enctype="multipart/form-data">

<?php include('sublink/index.php');?>
    <!--Nội dung load ở đây-->                   
    <div id="cph_Main_ContentPane">
        <div class="widget">
            <?php include('toolbar/index.php');?>
            
            <div class="widget-body">
            	<?php echo $messagesErrors;?>
            	<?php echo $this->errorMessages($this->error,'admin');?>
	   			<table class="admintable" style="width: 100%;">
	    			<?php  echo $this->form()->openTag($myForm);
	    			echo $this->formElement($elementId);
					echo $this->partialLoop('admin/form-group.phtml',$elements);
					echo $this->form()->closeTag();
					?>
				</table>
           	</div>
        </div> 
   	</div> 
</form>


<script type="text/javascript" src="<?php echo TEMPLATE_URL;?>/admin/js/1.8.3/jquery.min.js"></script>
<script type="text/javascript" src="<?php echo TEMPLATE_URL;?>/admin/js/jquery-ui.js"></script>


<script type="text/javascript">
		$(function() {
			

		    //upload avatar
			$("#appForm").submit(function(){
			    var formData = new FormData($(this)[0]);
			    
			    $.ajax({
			        url: "<?php echo $this->url(null,array('module'=>'admin','controller'=>'news','action'=>'upload'));?>",
			        type: 'POST',
			        data: formData,
			        async: false,
			        success: function (data) {
			        	$j("#load-avatar").html(data);
			        },
			        cache: false,
			        contentType: false,
			        processData: false
			    });

			    return false;
			});


		});

	  </script> 

	 <script type="text/javascript" src="<?php echo EDITOR_URL; ?>/ckeditor-study/ckeditor.js"></script>
	<script type="text/javascript" src="<?php echo EDITOR_URL; ?>/ckfinder/ckfinder.js"></script>

	<script>
			var content = CKEDITOR.replace( 'content', {
				customConfig	: 'config-05.js',
				
			});
			CKFinder.setupCKEditor( content, 'plugins/ckfinder/' );

		

	</script>
  	      	 	