<?php
//dự án nổi bật
$listItemHighlight = '';
if(!empty($this->listItemHighlight)){
    foreach($this->listItemHighlight as $item){
        $linkIntro = $this->url('IntroProjectRoute',array(
            'module'        =>  'home',
            'controller'    =>  'project',
            'action'        =>  'intro',
            'title'         =>  \ZendVN\Url\FriendlyLink::filter($item['name']),
            'id'            =>  $item['id'],
            'extension'     =>  'html',
        ));
        $image          =  TEMPLATE_URL .'/admin/images/NoImage.jpg';
        $i = 1;
        if(!empty($item['images'])){
            $images  = \Zend\Json\Json::decode($item['images']);
            foreach ($images as $key => $image) {
                if($i == 1){
                    $image = UPLOAD_URL .'/project/'.$image;
                    break;
                }
            }
        }

        $listItemHighlight      .= '<li><a href="'.$linkIntro.'" title="'.$item['name'].'"><img src="'.$image.'" width="113" alt="'.$item['name'].'" title="'.$item['name'].'"></a><h3><a href="'.$linkIntro.'" title="'.$item['name'].'">'.\ZendVN\Filter\ReadMore::create($item['name'],0,30).'</a></h3></li>';
    }
}

//BDS nổi bật
$xhtmlHighlight = '';
if(!empty($this->itemRealestateHighlight)){
  foreach ($this->itemRealestateHighlight as $key => $item) {

        $id             = $item['id'];
        $title          = $item['title'];
        $image          = TEMPLATE_URL .'/default/images/nha_mat_tien_100x75.png';
        $name_type      = $item['name_type'];
        $area           = $item['area'];
        $price_m2       = $item['price_m2'];
        $cat_id         = $item['cat_id'];
        $i              = 1;

        if(!empty($item['images'])){
            $images  = \Zend\Json\Json::decode($item['images']);
            foreach ($images as $key => $image) {
                if($i == 1){
                    $image = UPLOAD_URL .'/real-estate/'.$image;
                    break;
                }
            }
        }


        $linkDetail = $this->url('DetailBatDongSanRoute',array(
            'module'        =>  'home',
            'controller'    =>  'realestate',
            'action'        =>  'detail',
            'namecategory'  =>  \ZendVN\Url\FriendlyLink::filter($name_type),
            'title'         =>  \ZendVN\Url\FriendlyLink::filter($title),
            'cid'           =>  $cat_id,
            'id'            =>  $id,
            'extension'     =>  'html',
        ));


        $xhtmlHighlight .= '<li><a href="'.$linkDetail.'" title="'.$title.'"><img src="'.$image.'" width="150" height="112" alt="'.$title.'" title="'.$title.'"></a><h3><a href="'.$linkDetail.'" title="'.$title.'">'.\ZendVN\Filter\ReadMore::create($title,0,50).'</a><span>'.$price_m2.' tr/m2, <i>'.$area.'m<sup>2</sup></i></span></h3></li>';
  }
}

//BDS chính chủ
$xhtmlChinhChu = '';
$xhtmlChinhChuToolTip = '';
if(!empty($this->itemRealestateChinhChu)){
  foreach ($this->itemRealestateChinhChu as $key => $item) {
        $id             = $item['id'];
        $title          = $item['title'];
        $content        = $item['content'];
        $image          = TEMPLATE_URL .'/default/images/nha_mat_tien_100x75.png';
        $date_start     = $item['date_start'];
        $date_end       = $item['date_end'];
        $date_modifi    = $item['date_modifi'];
        $name_city      = $item['name_city'];
        $name_district  = $item['name_district'];
        $name_ward      = $item['name_ward'];
        $name_juridical = (!empty($item['name_juridical'])) ? $item['name_juridical'] : 'Đang cập nhật';
        $name_type      = $item['name_type'];

        $floor          = $item['floor'];
        $bedroom        = $item['bedroom'];
        $bathroom       = $item['bathroom'];
        $direction      = (!empty($item['direction'])) ? $item['direction'] : 'Đang cập nhật';
        $area           = $item['area'];
        $type_news      = $item['type_news'];
        $status         = $item['status'];
        $cat_id         = $item['cat_id'];
        $i              = 1;

        if(!empty($item['images'])){
            $images  = \Zend\Json\Json::decode($item['images']);
            foreach ($images as $key => $image) {
                if($i == 1){
                    $image = UPLOAD_URL .'/real-estate/'.$image;
                    break;
                }
            }
        }


        $linkDetail = $this->url('DetailBatDongSanRoute',array(
            'module'        =>  'home',
            'controller'    =>  'realestate',
            'action'        =>  'detail',
            'namecategory'  =>  \ZendVN\Url\FriendlyLink::filter($name_type),
            'title'         =>  \ZendVN\Url\FriendlyLink::filter($title),
            'cid'           =>  $cat_id,
            'id'            =>  $id,
            'extension'     =>  'html',
        ));

        $price          = $item['price'];


        $xhtmlChinhChu .= '<li>
                            <a href="'.$linkDetail.'" onmouseover="ddrivetipvip(\'divTootipBdsCc_'.$id.'\');" onmouseout="hideddrivetip();">
                              <b>'.$name_city.':</b> '.$title.'
                            </a>
                            <span class="price"><font class="ColorStyle_1">'.\ZendVN\Convert\Price::convert($price).'</font></span>
                          </li>';


        $xhtmlChinhChuToolTip .='<div id="divTootipBdsCc_'.$id.'" class="propertyToolTip" style="display:none;">
                                  <div class="ColImgs">
                                    <img width="100" height="75" title="'.$title.'" alt="311201421586488.jpg - ," src="'.$image.'">
                                   </div>
                                   <div class="ColDes">
                                    <h3>'.$title.'</h3>
                                    <h4><span><b>'.$bedroom.'</b>PN, <b>'.$bathroom.'</b>WC, '.$direction.'&nbsp;&nbsp;|&nbsp;&nbsp;  '.\ZendVN\Convert\Price::convert($price).'  </span><span>ID: '.$id.'</span></h4>
                                  <p>Địa chỉ:<span>'.$name_ward.', '.$name_district.', '.$name_city.'</span></p>
                                   </div>
                                   <ul>
                                    <li><span>Diện tích:</span><span>'.$area.'m<sup>2</sup> </span></li>
                                    
                                    <li><span>Pháp lý:</span><span>'.$name_juridical.'</span></li>
                                    <li><span>Hướng:</span><span>'.$direction.'</span></li>
                                   </ul>   
                                </div>';
  }
}

//Doanh nghiệp nổi bật
$itemBusinessHighlight = '';
if(!empty($this->itemBusinessHighlight)){
    foreach($this->itemBusinessHighlight as $item){
        $linkIntro      = $this->url('IntroBusinessRoute',array('action'=>'detail','alias'=>$item['alias']));

        $logo           = (!empty($item['logo']))  ? UPLOAD_URL .'/logo-business/'.$item['logo'] :  TEMPLATE_URL .'/admin/images/NoImage.jpg';

        $itemBusinessHighlight      .= '<li><a href="'.$linkIntro.'" title="'.$item['name'].'"><img src="'.$logo.'" width="113" alt="'.$item['name'].'" title="'.$item['name'].'"></a><h3><a href="'.$linkIntro.'" title="'.$item['name'].'">'.\ZendVN\Filter\ReadMore::create($item['name'],0,30).'</a></h3></li>';
    }
}

//Tin tức mới nhất slide
$xhtmlTinSlide = '';
if(!empty($this->listItemsNewsMoiNhat)){

  foreach ($this->listItemsNewsMoiNhat as $key => $item) {
    $title          = $item['title'];
    $description    = $item['description'];
    $image          = (!empty($item['images']))  ? UPLOAD_URL .'/news/'.$item['images'] :  TEMPLATE_URL .'/admin/images/NoImage.jpg';
    if($key == 0){
      $divStyle = '';
      $slideControl = "<li id='sli0' class=\"current\"><a onclick='SlideNo(0);'></a></li>
                      <li id='sli1' ><a onclick='SlideNo(1);'></a></li>
                      <li id='sli2' ><a onclick='SlideNo(2);'></a></li>
                      <li id='sli3' ><a onclick='SlideNo(3);'></a></li>
                      <li id='sli4' ><a onclick='SlideNo(4);'></a></li>";
    }else if($key == 1){
      $divStyle = 'style="display: none;"';
      $slideControl = "<li id='sli0'><a onclick='SlideNo(0);'></a></li>
                      <li id='sli1' class=\"current\" ><a onclick='SlideNo(1);'></a></li>
                      <li id='sli2' ><a onclick='SlideNo(2);'></a></li>
                      <li id='sli3' ><a onclick='SlideNo(3);'></a></li>
                      <li id='sli4' ><a onclick='SlideNo(4);'></a></li>";
    }else if($key == 2){
      $divStyle = 'style="display: none;"';
      $slideControl = "<li id='sli0'><a onclick='SlideNo(0);'></a></li>
                      <li id='sli1'><a onclick='SlideNo(1);'></a></li>
                      <li id='sli2' class=\"current\" ><a onclick='SlideNo(2);'></a></li>
                      <li id='sli3' ><a onclick='SlideNo(3);'></a></li>
                      <li id='sli4' ><a onclick='SlideNo(4);'></a></li>";
    }else if($key == 3){
      $divStyle = 'style="display: none;"';
      $slideControl = "<li id='sli0'><a onclick='SlideNo(0);'></a></li>
                      <li id='sli1'><a onclick='SlideNo(1);'></a></li>
                      <li id='sli2' ><a onclick='SlideNo(2);'></a></li>
                      <li id='sli3' class=\"current\" ><a onclick='SlideNo(3);'></a></li>
                      <li id='sli4' ><a onclick='SlideNo(4);'></a></li>";
    }else if($key == 4){
      $divStyle = 'style="display: none;"';
      $slideControl = "<li id='sli0'><a onclick='SlideNo(0);'></a></li>
                      <li id='sli1'><a onclick='SlideNo(1);'></a></li>
                      <li id='sli2' ><a onclick='SlideNo(2);'></a></li>
                      <li id='sli3' ><a onclick='SlideNo(3);'></a></li>
                      <li id='sli4' class=\"current\" ><a onclick='SlideNo(4);'></a></li>";
    }

    $urlDetail   = $this->url('DetailNewsRoute',array(
            'controller'        => 'news',
            'action'            => 'detail',
            'namecategory'      => \ZendVN\Url\FriendlyLink::filter($item['name_category']),
            'title'             => \ZendVN\Url\FriendlyLink::filter($title),
            'cid'               => $item['cat_id'],
            'id'                => $item['id'],
            'extension'         => 'html',
    ));

    $xhtmlTinSlide .= "<div class='newsjsctl' id='divNewMain_".$key."' ".$divStyle.">
                <a class='imgNews' title='".$title."' href='".$urlDetail."'>
                <img width='370' height='277' title='".$title."' alt='".$title."' src='".$image."' /></a>
                <div class='text'>
                    <div class='mainNewsContent'>
                      <h3><a title='".$title."' href='".$urlDetail."'>".$title."</a></h3>
                      <p>".$description."</p>
                    
                    </div>
                  <ul class='slideControl'>           
                    ".$slideControl."
                  </ul>
                </div>
              </div>";
  }
}

//Bds mới nhất
$xhtmlMoiNhat = '';
if(!empty($this->itemRealestateMoiNhat)){
  foreach ($this->itemRealestateMoiNhat as $key => $item) {
        $id             = $item['id'];
        $title          = $item['title'];
        $image          = TEMPLATE_URL .'/default/images/nha_mat_tien_100x75.png';
        $name_type      = $item['name_type'];
        $area           = $item['area'];
        $price_m2       = $item['price_m2'];
        $cat_id         = $item['cat_id'];
        $price          = $item['price'];
        $i              = 1;

        if(!empty($item['images'])){
            $images  = \Zend\Json\Json::decode($item['images']);
            foreach ($images as $key => $image) {
                if($i == 1){
                    $image = UPLOAD_URL .'/real-estate/'.$image;
                    break;
                }
            }
        }


        $linkDetail = $this->url('DetailBatDongSanRoute',array(
            'module'        =>  'home',
            'controller'    =>  'realestate',
            'action'        =>  'detail',
            'namecategory'  =>  \ZendVN\Url\FriendlyLink::filter($name_type),
            'title'         =>  \ZendVN\Url\FriendlyLink::filter($title),
            'cid'           =>  $cat_id,
            'id'            =>  $id,
            'extension'     =>  'html',
        ));




        $xhtmlMoiNhat .= '<li><a href="'.$linkDetail.'">'.$title.'<span></span></a><span class="price">'.\ZendVN\Convert\Price::convert($price).'</span></li>';
  }
}


?>

<div class="pageWrap">
    <div class="breadCrumb">
    <?php echo $this->cmsBreadcrumb(null,array('task'=>'no-data')) .' '.$this->blkAccountGroup($this->identity());?>
    </div>
</div>

<div class="pageWrap" style="height:94px;margin-top:5px;">
    <div class="marB20" style="text-align:center;">
        <?php echo $this->blkAdsTop();?>
    </div>
</div>

<div style="display: block;" class="mainSearch">
    <?php echo $this->formSearch;?>
</div>

 <script type="text/javascript">
    $(document).ready(function(){
//Load quận huyện

    });


</script>

<script type="text/javascript">LoadLoaiBDSFolTranClass('sale');SetValueQH('txtTranClass', 'sale');document.getElementById('txtTranClassText').value='bán';NvgFst.DefaultGiaTTDt();WriteTextCondition();if($('#txtStateID').val()!=''){SetLGDVaLBDSIdx();}else{$('#rdoBan').attr('checked','true');}</script>



<div class="pageWrap">



<div class="leftMainContent">


  <div class="mainNews" style="height: 241px;">
      <?php echo $this->blkSlideNews();?>
  </div>



 <div class="vipObject company">
    <h2 class="leftTitle"><b>Doanh nghiệp nổi bật</b></h2>
    <div class="leftSmallContent">
        <div id="nodegalleryDa" style="left:0;"><ul style="width: 1197px; position: relative; left: -283.0664157292731px;">
            <?php echo $itemBusinessHighlight;?>

        </ul><a onclick="SlideCaroulse(&quot;l&quot;);" href="javascript:" class="previousButton grey" title="Previous"></a><a onclick="SlideCaroulse(&quot;r&quot;);" href="javascript:" class="nextButton grey" title="Next"></a></div>

    </div>
</div>
         <script type="text/javascript">
             self.setInterval("SlideCaroulse('l')", 3000);
             var previousB = 5;
             var noOfSlide = 5;
             var selectedUl = 'div#nodegalleryDa ul';
             var ulWidth = $(selectedUl).width();
             var liWidth = 133;


        </script>


           <div id="dvTopEstate" class="vipObject project">
    <h2 class="leftTitle"><b>Dự án nổi bật</b></h2>
    <div id="slider1" class="leftSmallContent">
        <ul style="width: 2232px; left: 0px;" id="ulDaVipMainMnu"><?php echo $listItemHighlight ;?></ul>

    </div>
</div>
<script type="text/javascript">
    $("#ulDaVipMainMnu img").error(function (event) {
        $(this).attr("src", "http://muabannhadat.com.vn/images/du-an-noi-bat.jpg");
    })
</script>
<script type="text/javascript">
    //    $(function () {
    //        LoadNextTopEstate();
    //    });
    var esi = 4;
    function LoadNextTopEstate() {

        $("#ulDaVipMainMnu").html("");

        var countes = 1;
        while (esi < listtopestate.length) {
            if (countes > 4)
                break;
            var htmlinner = listtopestate[esi].es;
            esi++;
            $("#ulDaVipMainMnu").append(htmlinner);
            countes++;
            if (esi > listtopestate.length - 1)
                esi = 0;
        }

        setTimeout("LoadNextTopEstate()", 10000);
        $("#ulDaVipMainMnu img").error(function(event) {
            $(this).attr("src", "http://muabannhadat.com.vn/images/du-an-noi-bat.jpg");
        });
    }
    if(listtopestate.length>4)
        setTimeout("LoadNextTopEstate()", 10000);
</script>


<div class="vipObject property">
    <h2 class="leftTitle"><b>
        Bất động sản nổi bật</b></h2>
    <div class="leftSmallContent">
        <div id="divListBdsVip">
            <ul><?php echo $xhtmlHighlight;?></ul>
        </div>
    </div>
    <a name="searchbox" ></a>
</div>
<script type="text/javascript">
    $("#divListBdsVip img").error(function (event) {
        $(this).attr("src", "http://muabannhadat.com.vn/images/noimages.gif");
    })
    </script>

    <script type="text/javascript">
        var j = 0;
        function LoadNextTopPro() {
            if (j == 4) j = 1;
            if (j == 0) j = 1;
            var htmlinnerpro = "";
            if (j == 1)
                htmlinnerpro = listTopPro.p1;
            if (j == 2)
                htmlinnerpro = listTopPro.p2;
            if (j == 3)
                htmlinnerpro = listTopPro.p3;

            $("#divListBdsVip").html(htmlinnerpro);
            j++;
            setTimeout("LoadNextTopPro()", 20000);

            $("#divListBdsVip img").error(function (event) {
                $(this).attr("src", "http://muabannhadat.com.vn/images/noimages.gif");
            })
        }

        setTimeout("LoadNextTopPro()", 20000);
</script>



            <div id="MainContent_OwnerProperty1_divBDS_noibat_index" class="M_Box_1 mar_b10"><div class="propertyLine myself">
      <h2 class="leftTitle"><b>Bất động sản chính chủ</b>
      </h2>
      <div class="leftSmallContent">
        <ul>
          <?php echo $xhtmlChinhChu;?>
        </ul>

      </div>


    </div>
  </div>

  <?php echo $xhtmlChinhChuToolTip;?>


  <script>
  ga('send' ,'timing', 'Home', 'Sql time OwnerProperty', 25);
  </script>

  <script src="<?php echo TEMPLATE_URL;?>/default/js/tooltipDoanhNghiep.js" type="text/javascript"></script>




  <div class="propertyLine newest">
    <h2 class="leftTitle"><b>
        Nhà đất mới nhất</b></h2>
    <div class="leftSmallContent">
        <ul id="ListPiNewest">
        <?php echo $xhtmlMoiNhat;?>
      </ul>

    </div>
  </div>
<script type="text/javascript">
    //<!--
    nvgData.ListPropertyNewest('', '', '', '');
    //-->
</script>



<?php echo $this->blkAdsBottom();?>



        </div>
  <div class="rightMainContent">
    <div class="centerBannerMore">
        <div class="marB10">
        <?php echo $this->blkAdsColumnRight();?>
        </div>
    </div>

  <script type="text/javascript">
      function DisplayMe(div) {
          document.getElementById(div).style.display = '';
      }

      $('#txtEmailNL').click(function (event) {$('html').one('click', function () {$("#infoDiv").hide();});event.stopPropagation();});$('#txtFullName').click(function (event) {$('html').one('click', function () {$("#infoDiv").hide();});event.stopPropagation();});
  </script>


  <?php echo $this->blkCafeLuat();?>


  <?php echo $this->blkBangGiaDuAn();?>
  <?php echo $this->blkAgency();?>
  <?php echo $this->blkFengShui();?>

    <script type="text/javascript">
        $("#divTopAgent .padded .infoGroup img").error(function (event) {
            $(this).attr("src", "http://images.videonhadat.com.vn/avatar_male_84x94.gif");
        })
    </script>

  <?php echo $this->blkRegisterEmail();?>
  <?php echo $this->blkNhanXet();?>
  <?php echo $this->blkLienKet();?>
  </div>
</div>
