<?php

$logo  = (!empty($this->item['logo']))  ? UPLOAD_URL .'/logo-business/'.$this->item['logo'] :  TEMPLATE_URL .'/admin/images/NoImage.jpg';

$name  		= $this->item['name'];
$address  	= $this->item['address'] . ' - ' .$this->item['name_ward'] . ' - '.$this->item['name_district'] . ' - '.$this->item['name_city'];

$phone 		= $this->item['phone'];
$fax 		= $this->item['fax'];
$website    = $this->item['website'];
$intro 		= $this->item['intro'];
$contact	= $this->item['contact'];
$department = $this->item['department'];
?>

<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<link href="<?php echo TEMPLATE_URL;?>/admin/css/layout.css" media="screen" rel="stylesheet" type="text/css" >


<div class='message info'><h5>Thông tin doanh nghiệp</h5>
<p class='detail-info even'><span><img style="border-radius: 1px;-moz-border-radius: 1px;-webkit-border-radius: 1px;box-shadow: 0 0 5px black;-webkit-box-shadow: 0 0 5px black;" src="<?php echo $logo;?>" width="200px" height="100"></span></p>
<p class='detail-info even'><label>Tên doanh nghiệp:</label><span><?php echo $name;?></span></p>
<p class='detail-info even'><label>Địa chỉ:</label><span><?php echo $address;?></span></p>
<p class='detail-info even'><label>Điện thoại:</label><span><?php echo $phone;?></span></p>
<p class='detail-info even'><label>Fax:</label><span><?php echo $fax;?></span></p>
<p class='detail-info even'><label>Website:</label><span><?php echo $website;?></span></p>
<p class='detail-info even'><label>Giới thiệu:</label><span><?php echo $intro ;?></span></p>
<p class='detail-info even'><label>Liên hệ:</label><span><?php echo $contact ;?></span></p>
<p class='detail-info even'><label>Chi nhánh:</label><span><?php echo $department ;?></span></p>
</div>