<?php



$title  		= $this->item['fullname'];
$email  		= $this->item['email'];

?>

<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<link href="<?php echo TEMPLATE_URL;?>/admin/css/layout.css" media="screen" rel="stylesheet" type="text/css" >


<div class='message info'><h5>Xem nhanh</h5>

<p class='detail-info even'><label>Họ tên:</label><span><?php echo $title ;?></span></p>
<p class='detail-info even'><label>Email:</label><span><?php echo $email ;?></span></p>

</div>