<?php



$name  			= $this->item->name;
$url 		 	= $this->item->url;

?>

<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<link href="<?php echo TEMPLATE_URL;?>/admin/css/layout.css" media="screen" rel="stylesheet" type="text/css" >


<div class='message info'><h5>Xem nhanh</h5>
<p class='detail-info even'><span></p>
<p class='detail-info even'><label>Tên website:</label><span><?php echo $name ;?></span></p>
<p class='detail-info even'><label>Url website:</label><span><?php echo $url;?></span></p>


</div>