<?php
$myForm = $this->myForm;
$myForm->prepare();
$elementId			= $myForm->get('id');
$elementName 		= $myForm->get('name');
$elementUrl 		= $myForm->get('url');

$elements = array(
	array(
		'label'				=>	$this->formLabel($elementName),
		'input'				=>	$this->formElement($elementName),
		'class'				=>	'col-sm-9',
		'required'			=>	'*',
		'tooltiptitle'		=>	'Tên website',
		'tooltipmessage'	=>	'Nhập Tên website',
	),
	
	
	array(
		'label'				=>	$this->formLabel($elementUrl),
		'input'				=>	$this->formElement($elementUrl),
		'class'				=>	'col-sm-9',
		'required'			=>	'*',
		'tooltiptitle'		=>	'Url website',
		'tooltipmessage'	=>	'Nhập Url website',
	),

	
	
	
);

$messagesErrors = $this->elementErrors(array(
	'name'				=>	$elementName,
	'url'				=>	$elementUrl,
	
));


 
       


?>


<form name="appForm" method="post" action="" enctype="multipart/form-data">

<?php include('sublink/index.php');?>
    <!--Nội dung load ở đây-->                   
    <div id="cph_Main_ContentPane">
        <div class="widget">
            <?php include('toolbar/index.php');?>
            
            <div class="widget-body">
            	<?php echo $messagesErrors;?>
            	<?php echo $this->errorMessages($this->error,'admin');?>
	   			<table class="admintable" style="width: 100%;">
	    			<?php  echo $this->form()->openTag($myForm);
	    			echo $this->formElement($elementId);
					echo $this->partialLoop('admin/form-group.phtml',$elements);
					echo $this->form()->closeTag();
					?>
				</table>
           	</div>
        </div> 
   	</div> 
</form>

<script type="text/javascript" src="<?php echo EDITOR_URL; ?>/ckeditor-study/ckeditor.js"></script>
<script type="text/javascript" src="<?php echo EDITOR_URL; ?>/ckfinder/ckfinder.js"></script>

<script>
		var content = CKEDITOR.replace( 'content', {
			customConfig	: 'config-05.js',
			
		});
		CKFinder.setupCKEditor( content, 'plugins/ckfinder/' );

	

	</script>	
   	      	 	