<?php
$isXmlHttpRequest = $this->isXmlHttpRequest;
if($isXmlHttpRequest == true){

$page       = !empty($this->arrParam['page']) ? $this->arrParam['page'] : 1;
$LinkPage   = $this->basePath()."/".$this->arrParam['module']."/".$this->arrParam['controller']."/list/page/".$page;



$ssFilter               = $this->arrParam['ssFilter'];
$action_link            = $this->basePath($this->currentController . '/filter/order');
$lblID                  = $this->cmsLinkSort('ID','id',$ssFilter,
                                        TEMPLATE_URL . '/admin/images/',$action_link);
                                        
$lblName                = $this->cmsLinkSort('Thư mục','name',$ssFilter,
                                        TEMPLATE_URL . '/admin/images/',$action_link);
    
$lblDateRegister        = $this->cmsLinkSort('Ngày tạo','date_time',$ssFilter,
                                        TEMPLATE_URL . '/admin/images/',$action_link);
                                        
$lblStatus              = $this->cmsLinkSort('Public','status',$ssFilter,
                                        TEMPLATE_URL . '/admin/images/',$action_link);
                                                    
$lblOrder               = $this->cmsLinkSort('Order','order',$ssFilter,
                                        TEMPLATE_URL . '/admin/images/',$action_link);

$lblCheckAll            = $this->cmsInput('checkbox','checkbox','checkbox',array('onclick'=>'checkedAll()'));           
  
?>

<div class="row-fluid">
    <div class="span3">
      
    </div>
    
<?php
    $currentUrl =  $this->currentController.'/index/page/';
    echo $this->paginationControl($this->paginator , 'sliding' , 'paginator.phtml', array('currentUrl'=>$currentUrl)); 
 ?>




<?php

$xhtml = '';
if(!empty($this->items)){
    foreach($this->items as $item){
        $id         =   $item['id'];
        $name       =   $item['name'];
        
       
        $image          = (!empty($item['images']))  ? UPLOAD_URL .'/gallery/'.$item['images'] :  TEMPLATE_URL .'/admin/images/NoImage.jpg';
                                   
    

        $cid                = $this->cmsInput('cid[]','cid','checkbox',array('value'=>$id));

         //Icon status
        if($item['status'] == 1){
            $linkStatus = $this->basePath($this->currentController . '/status/'.$id.'/0'); 
            $btnStatus  = $this->cmsIconButton('Active', TEMPLATE_URL . '/admin/images/kh.png',$linkStatus,'link'); 
        }else{
            $linkStatus = $this->basePath($this->currentController . '/status/'.$id.'/1'); 
           $btnStatus  = $this->cmsIconButton('Active', TEMPLATE_URL . '/admin/images/kkh.png',$linkStatus,'link');
        }
       

        $xhtml .= '<div id="item">
                    <div class="img"><a href="'.$image .'" rel="facybox"><img style="border-radius:7px;-moz-border-radius:7px;-webkit-border-radius:7px;box-shadow:0 0 5px black;-webkit-box-shadow:0 0 5px black;" src="'.$image .'" alt="Mặc định" width="160px" height="200"></a>
                                    
                </div>


                <div class="price" style="margin-top:5px;">
                '.$btnStatus.'
                </div>
                <div class="price">'.$cid .' Chọn ảnh</div>
                <div style="margin-top:5px;height:20px;position:relative;font-size:12px;text-align: center;"> <span>'.$name.'</span></div>                
                </div>';                    

                             
    }
}

?>

<style>
#list-gallary{}
#list-gallary #item{width:170px;float:left;margin-bottom:10px;margin-left:7px;margin-right:5px;background:#FFFFFF;}
#list-gallary #item .img{height:200px;position:relative;text-align:center;margin-top:5px;}
#list-gallary #item .title-p{height:20px;position:relative;text-align:center;font-size:12px;font-weight:bold;}
#list-gallary #item .price{text-align:center;height:20px;position:relative;font-size:12px;font-weight:bold;color:red;}
</style>

    <div id="dialog-confirm" title="Thông báo!'" style="display: none;">
        <p>Bạn có chắc muốn xóa phần tử này hay không?</p>
    </div> 
     <div id="dialog-confirm-all" title="Thông báo!'" style="display: none;">
        <p>Bạn có chắc muốn những phần tử được chọn này hay không?</p>
    </div> 
    
    <div id="list-gallary" style="clear:both;float:left;">
        <?php echo $xhtml;?>         

    </div>

<?php
    $currentUrl =  $this->currentController.'/index/page/';
    echo $this->paginationControl($this->paginator , 'sliding' , 'paginator.phtml', array('currentUrl'=>$currentUrl)); 

 ?>
</div>


<script type="text/javascript" src="<?php echo TEMPLATE_URL;?>/admin/js/jquery.js"></script>
<script type="text/javascript" src="<?php echo TEMPLATE_URL;?>/admin/js/jquery-ui-1.10.3.custom.min.js"></script>
<link rel="stylesheet" type="text/css" href="<?php echo TEMPLATE_URL;?>/admin/css/jquery-ui-1.10.3.custom.min.css">

<script type="text/javascript">
function checkAdmin(id){
    alert("Tài khoản admin không thể xóa");
}
//Xóa dữ liệu
function deleteItem(id) {
    $j("#dialog-confirm").dialog({
        resizable : false,
        height : 200,
        modal : true,
        buttons : {
            "Yes" : function() {
             
                $j(this).dialog("close");
                <?php $urlDelete = $this->currentController.'/delete/';?>
                window.location.href ='<?php echo $urlDelete;?>' + id;
                
            },
            Cancel : function() {
                $j(this).dialog("close");
            }
        }
    });
    
}
//Xóa những item đã chọn
function deleteItemChanged(){
    $j("#dialog-confirm-all").dialog({
        resizable : false,
        height : 200,
        modal : true,
        buttons : {
            "Yes" : function() {
                var strId = '';
                $j('input[id=cid]:checked').each( function(index,element) {
                   
                    if(index == 0){
                        strId += $j(this).val();
                    }else{
                        strId += ',' + $j(this).val();
                    }
                    
                   
                });
                $j(this).dialog("close");
                <?php $urlMutiDelete = $this->currentController.'/multi-delete/';?>
                window.location.href ='<?php echo $urlMutiDelete;?>' + strId;
                
            },
            Cancel : function() {
                $j(this).dialog("close");
            }
        }
    });
}
function statusItemChanged(option){
    var strId = '';
    $j('input[id=cid]:checked').each( function(index,element) {
        if(index == 0){
            strId += $j(this).val();
        }else{
            strId += ',' + $j(this).val();
        }     
    });
    <?php $urlMutiStatus = $this->currentController.'/multi-status/';?>
    window.location.href ='<?php echo $urlMutiStatus;?>' + strId + '/' + option;
}
//Chọn xóa
function Confirm(option) {
    var strId = '';
    $j('input[type=checkbox]:checked').each( function(index,element) {
        if($j(this).val() != 'on'){
            if(index == 1){
                strId += $j(this).val();
            }else{
                strId += ',' + $j(this).val();
            }
        }
       
    });
    if(strId == ''){
        alert('Hãy chọn ít nhất 1 Item để thao tác');
    }else{
        if(option == 'multi-delete'){
            deleteItemChanged();
        }if(option == 'multi-active'){
            statusItemChanged('multi-active');
        }if(option == 'multi-in-active'){
            statusItemChanged('multi-in-active');
        }
    }
    return false;
}



$j(document).ready(function(){

    /*Thay đổi thứ tự*/
    $j(".change-order").change(function(){
        var link    = $j(this).attr("rel");
        var idItem  = $j(this).attr('title');
        var val     = $j(this).val();
        var pattern = /[0-9]+$/;
        if(!pattern.test(val)){
            alert('Vui lòng nhập số');
        }else{
            $j.ajax({
            url     : '<?php echo $LinkPage;?>',
            type    : 'GET',
            data    : {id : idItem,  value : val, option : 'order'},
            cache   : false,
            success : function(data,status){
                $j("div.dataTables_wrapper").html(data);
            }
        });
        }
    });

        
    
});   
</script>


<?php
}else{
    echo 'not ajax';
}
?>




