<?php 

    $myForm             = $this->myForm;
    $myForm->setAttribute('action', $this->url(null, array(
            'module'        =>  'home',
            'controller'    => 'user',
            'action'        => 'validate-forgot-password'
    )));
    
    
    $myForm->prepare();
    $elementEmail       = $myForm->get('my-email');
    $elementBtnSubmit   = $myForm->get('my-button-submit');
   
    
    $elements       = array(
            array(
                    'label'     => $this->formLabel($elementEmail),
                    'input'     => $this->formElement($elementEmail),
                    'error'     => 'ajax-info-email',
                    'lierror'   => 'li-email',
            ),
           
            array(
                    'label' => null,
                    'input' => $this->formElement($elementBtnSubmit),
                    'error' => '',
                    'lierror'   =>'',
            ),
    );

if(!empty($this->msgError)){
    $messageError = $this->msgError;
}

$linkRegister           = $this->url('MVC_HomeRouter/action',array('module'=>'home','controller'=>'user','action'=>'register'));
$linkPasswordForgot     = $this->url('MVC_HomeRouter/action',array('module'=>'home','controller'=>'user','action'=>'forgot-password'));

?>


<style type="text/css">
.content-error {
    color: #df3832;
    font-style: normal;
}
</style>
<script type="text/javascript" src="<?php echo TEMPLATE_URL;?>/default/js/jquery.min.js"></script>
<script type="text/javascript" src="<?php echo TEMPLATE_URL;?>/default/js/jquery.form.js"></script>
<script type="text/javascript">
    var options = { 
        target      : '#ajax-info',
        dataType    : 'json',
        success     : showResponse  
 
    }; 

    function showResponse(data){
        if(data.status == 'success'){
             //console.log(data.messages['success']);
            $('#li-email').removeAttr('style');
            $('#ajax-info-success').html(data.messages['success'])
                                .removeAttr('style')
                                .css({'padding':'10px','color':'white','background-color':'#61b832','border-color':'#55a12c','margin-bottom':'10px'});
           
        }else if(data.status == 'error'){
            
            /*var error   = '';
            for(x in data.messages){
                error += data.messages[x] + '<br/>';
            }*/
            $('#li-email').removeAttr('style');
            $('#inputEmail').removeClass();

            if(data.messages['email']){
                $('#inputEmail').addClass('inputWarmning');
            }

            //Thông báo email
            $('#ajax-info-email').html(data.messages['email'])
                                 .removeClass()
                                 .addClass('content-error')
                                 .css({'width':'386px'}); 


            
        }else if(data.status == undefined){
            $('#ajax-info').html('Có lỗi trong quá trình xử lý').removeClass().addClass('content-warning');
        }
    }
    
    $(document).ready(function() {
        $('#login-form').submit(function(){
            $(this).ajaxSubmit(options); 
            return false; 
        });
    })
    

</script>

<div class="pageWrap">
<?php echo $this->cmsBreadcrumb($this->title,array('task'=>'no-data')) .' '.$this->blkAccountGroup($this->identity());?>
</div>
<div class="pageWrap">
<div class="leftMainContent popupPage">
    <div class="signInNewDialog">
		<div class="TitleDialog">
            <h4>Quên mật khẩu?</h4>
        </div>
		 <div class="ContentDialog">

         	<h6>Nhập vào địa chỉ Email, chúng tôi sẽ gửi Mật khẩu lại cho bạn!</h6>
            <div id="ajax-info-success" style="display:none;"></div>
            <ol>
            	<?php 
                echo $this->form()->openTag($myForm);
                    echo $this->partialLoop('form-group.phtml', $elements);
                echo $this->form()->closeTag();
                ?>

            </ol>
         </div>
	</div>
</div>
</div>
   