<div class="mbn-list hidden-xs">
    <div data-bind="with: TopSearch" id="dv-top-search">
        <div class="mbn-search clearfix hidden-xs" id="topSearch" data-bind="addOnEnter: GotoSearch">
            <div class="container container-top-seach row">
                <div class="col-md-3 col-sm-3 col-xs-3 top-search-location">
                    <i id="mbn-top-search-city-icon" class="fa fa-map-marker marker"></i>
<!--                    <select data-gtm-event="mbn-event-link" data-gtm-category="mbn-search"-->
<!--                            data-gtm-action="mbn-city-dropdown"-->
<!--                            data-bind="chosen: { source: Cities, selectedValue: CityId, displayProp: 'Name', valueProp: 'CityId', styleProp: 'Style', chosenOption: { disable_search: true } }"-->
<!--                            class="hide">-->
<!--                    </select>-->

                    <select name="" id="" class="chosen-select mbn-search">
                        <option value="">1212</option>
                        <option value="">1212</option>
                        <option value="">1212</option>
                        <option value="">1212</option>
                        <option value="">1212</option>
                        <option value="">1212</option>
                        <option value="">1212</option>
                        <option value="">1212</option>
                        <option value="">1212</option>
                    </select>


                </div>

                <div class="col-md-5 col-sm-5 col-xs-5 top-search-keyword">
                    <div class="input-group">
                        <input type="text" class="form-control input-keyword"
                               data-bind="value: Keyword, attr:{placeholder: KeywordPlaceholder}" maxlength="50">
                        <a data-gtm-event="mbn-event-link" data-gtm-category="mbn-search"
                           data-gtm-action="simple-search" class="input-group-addon btn-search"
                           data-bind="click:GotoSearch" href="#"> <i class="fa fa-search"></i> &nbsp;Tìm</a>
                    </div>
                </div>
            </div>
        </div>


    </div>
</div>
<div class="posting-line"></div>
<div class="mbn-list">
    <div class="mbn-title-link hidden-xs">
        <div class="container">
            <div class="mbn-box-sub-link" id="dv_box_sub_link">
                <div class="mbn-box-sub-list-link ">
                    <?php require_once TEMPLATE_PATH . DS . 'home_v2' . DS . 'inc' . DS . 'box-menu.php'; ?>
                    <div class="clearfix"></div>
                </div>
                <div class="clearfix"></div>

                <?php require_once TEMPLATE_PATH . DS . 'home_v2' . DS . 'inc' . DS . 'box-filter.php'; ?>
                <div class="clearfix"></div>
            </div>

        </div>
    </div>
    <div class="container">


        <div class="breadcrumb breadcrumbs">
            <div class="rdfa-breadcrumb">
                <div xmlns:v="http://rdf.data-vocabulary.org/#">
                    <div>
                        <span class="breadcrumbs-title"> </span>
                        <span typeof="v:Breadcrumb">
                    <a data-gtm-event="mbn-event-link" data-gtm-category="mbn-listing-nav" data-gtm-action="/"
                       rel="v:url" property="v:title" href="https://muaban.net/" class="home">Trang chủ</a>
                </span>
                        <span class="icon icon-arrow-s"></span>
                        <span typeof="v:Breadcrumb"> <a data-gtm-event="mbn-event-link"
                                                        data-gtm-category="mbn-listing-nav"
                                                        data-gtm-action="listing-nav-https://muaban.net/toan-quoc"
                                                        rel="v:url" property="v:title"
                                                        href="https://muaban.net/toan-quoc"
                                                        title="Toàn quốc">Toàn quốc</a></span>
                        <span class="icon icon-arrow-s"></span>
                        Bất động sản
                    </div>
                </div>
            </div>
        </div>

    </div>

    <div class="mbn-body container">
        <div class="mbn-box-left">
            <div class="mbn-box-list">

                <div class="list-title">
                    <h1>
                        Mua bán rao vặt bất động sản, nhà đất tại Toàn quốc
                    </h1>
                    <div id="page-description">Trang thông tin rao vặt, mua bán bất động sản uy tín tại Toàn quốc.
                        2,000,000 tin mua, bán, cho thuê phòng trọ, căn hộ ,nhà đất, khách sạn,... được cập nhật 24/7
                        tại muaban.net.
                    </div>
                </div>
                <div class="mbn-tool" data-bind="visible: visibleTool">
                    <span class="mbn-total" data-bind="text: TotalRecord"></span>
                    <div class="mbn-sort">
                        <select data-gtm-event="mbn-event-all" data-gtm-category="mbn-listing"
                                data-gtm-action="listing-sort"
                                class="hidden"
                                data-bind="chosen: { source: Sorts, selectedValue: SortValue, displayProp: 'Name', valueProp: 'Value', chosenOption: { disable_search: true } }"></select>
                    </div>
                    <ul class="nav mbn-list-nav">
                        <li>
                            <a data-gtm-event="mbn-event-link" data-gtm-category="mbn-listing-view"
                               data-gtm-action="listing-view-simple"
                               title="Hiển thị rút gọn" href="javascript:void(0)" data-bind="click:simpleClick"><span
                                        class="icon icon-display-simple "></span></a>
                        </li>
                        <li>
                            <a data-gtm-event="mbn-event-link" data-gtm-category="mbn-listing-view"
                               data-gtm-action="listing-view-gallery"
                               title="Hiển thị lưới" href="javascript:void(0)" data-bind="click:galleryClick"><span
                                        class="icon icon-display-grid "></span></a>
                        </li>
                        <li>
                            <a data-gtm-event="mbn-event-link" data-gtm-category="mbn-listing-view"
                               data-gtm-action="listing-view-list"
                               title="Hiển thị tiêu chuẩn" href="javascript:void(0)" data-bind="click:listClick"><span
                                        class="icon icon-display-list "></span></a>
                        </li>
                        <li>
                            <a data-gtm-event="mbn-event-link" data-gtm-category="mbn-listing-view"
                               data-gtm-action="listing-view-summary"
                               title="Hiển thị nội dung" href="javascript:void(0)"
                               data-bind="click:listSummaryClick"><span
                                        class="icon icon-display-list-new mbn-color-selected"></span></a>
                        </li>
                    </ul>
                </div>
            </div>

            <div class="clearfix"></div>


            <div class="mbn-box-slide">
                <div id="box-slide-special" class="mbn-box-slide-special  ">
                    <div class="mbn-title-header">
                        <span class="title-special">Tin nổi bật</span>
                        <a data-gtm-event="mbn-event-all" data-gtm-category="mbn-listing-sptop"
                           data-gtm-action="listing-sptop-posting-next" id="btnNext" class="special-ctn-next">
                            <i class="icon icon-right218"></i>
                        </a>
                        <a data-gtm-event="mbn-event-all" data-gtm-category="mbn-listing-sptop"
                           data-gtm-action="listing-sptop-posting-back" id="btnPrev" class="special-ctn-next">
                            <i class="icon icon-left207"></i>
                        </a>


                        <a class="title-qc" data-gtm-event="mbn-event-link" data-gtm-category="mbn-listing-sptop"
                           data-gtm-action="listing-sptop-help"
                           href="https://muaban.net/uploads/huong-dan/bang_gia/tin-noi-bat/index.html">Bạn muốn quảng
                            cáo tại đây?</a>
                        <div class="clearfix"></div>
                    </div>
                    <div class="clearfix"></div>
                    <div id="owl-carousel-special" class="owl-carousel">
                        <?php require_once TEMPLATE_PATH . DS . 'home_v2' . DS . 'inc' . DS . 'content-vip.php';?>
                    </div>

                    <a data-gtm-event="mbn-event-all" data-gtm-category="mbn-listing-sptop-mobile"
                       data-gtm-action="listing-sptop-posting-back"
                       class="prev carousel-control icon icon-arrow83"></a>
                    <a data-gtm-event="mbn-event-all" data-gtm-category="mbn-listing-sptop-mobile"
                       data-gtm-action="listing-sptop-posting-next"
                       class="next carousel-control icon icon-arrow89 right"></a>

                </div>

            </div>


            <div class="mbn-box-list">
                <div class="mbn-tool-mobile" data-bind="visible: visibleTool">
                    <div class="mbn-sort">
                        <a data-gtm-event="mbn-event-all" data-gtm-category="mbn-listing-mobile"
                           data-gtm-action="listing-sort"
                           aria-expanded="false" role="button" data-toggle="dropdown" class="dropdown-toggle" href="#">
                            <span><i data-bind="attr:{class: SortValueResposiveSelected}"></i></span><span
                                    class="mbn-title" data-bind="text:SortDisplayName"></span>
                        </a>
                        <ul role="menu" class="dropdown-menu" data-bind="foreach: Sorts">
                            <li data-bind="attr:{class : ($parent.SortValue() == Value ? 'color-selected' : '')}">
                                <a href="javascript:void(0)"
                                   data-bind="click: function (data, event) { $parent.SortValueResposive(Value);}">
                                    <span><i data-bind="attr:{class : ($parent.SortValue() == Value ? Icon + ' color-selected' : Icon)}"></i></span><span
                                            data-bind="text: Name"></span>
                                </a>
                            </li>
                        </ul>
                    </div>
                    <ul class="nav mbn-list-nav">
                        <li>
                            <a data-gtm-event="mbn-event-link" data-gtm-category="mbn-listing-view-mobile"
                               data-gtm-action="listing-view-simple"
                               title="Hiển thị rút gọn" href="javascript:void(0)" data-bind="click:simpleClick"><span
                                        class="icon icon-display-simple "></span></a>
                        </li>
                        <li>
                            <a data-gtm-event="mbn-event-link" data-gtm-category="mbn-listing-view-mobile"
                               data-gtm-action="listing-view-gallery"
                               title="Hiển thị lưới" href="javascript:void(0)" data-bind="click:galleryClick"><span
                                        class="icon icon-display-grid "></span></a>
                        </li>
                        <li>
                            <a data-gtm-event="mbn-event-link" data-gtm-category="mbn-listing-view-mobile"
                               data-gtm-action="listing-view-list"
                               title="Hiển thị tiêu chuẩn" href="javascript:void(0)" data-bind="click:listClick"><span
                                        class="icon icon-display-list "></span></a>
                        </li>
                    </ul>
                </div>

            </div>
            <div class="mbn-box-list">
                <?php require_once TEMPLATE_PATH . DS . 'home_v2' . DS . 'inc' . DS . 'content-lease.php';?>


                <div class="borderTop"></div>
                <div class="clearfix"></div>


                <!--Paging:Begin-->
                <div class="paging">
                    <ul class="pagination">
                        <li class="disabled"><span><i class="fa fa-angle-left"></i></span></li>
                        <li class="active"><span>1</span></li>
                        <li class=""><a href="https://muaban.net/mua-ban-nha-dat-cho-thue-toan-quoc-l0-c3?cp=2">2</a>
                        </li>
                        <li class=""><a href="https://muaban.net/mua-ban-nha-dat-cho-thue-toan-quoc-l0-c3?cp=3">3</a>
                        </li>
                        <li class=""><a href="https://muaban.net/mua-ban-nha-dat-cho-thue-toan-quoc-l0-c3?cp=4">4</a>
                        </li>
                        <li class=""><a href="https://muaban.net/mua-ban-nha-dat-cho-thue-toan-quoc-l0-c3?cp=5">5</a>
                        </li>
                        <li class="hidden-xs"><a
                                    href="https://muaban.net/mua-ban-nha-dat-cho-thue-toan-quoc-l0-c3?cp=6">6</a></li>
                        <li class="hidden-xs"><a
                                    href="https://muaban.net/mua-ban-nha-dat-cho-thue-toan-quoc-l0-c3?cp=7">7</a></li>
                        <li class="hidden-sm hidden-xs"><a
                                    href="https://muaban.net/mua-ban-nha-dat-cho-thue-toan-quoc-l0-c3?cp=8">8</a></li>
                        <li class="hidden-sm hidden-xs"><a
                                    href="https://muaban.net/mua-ban-nha-dat-cho-thue-toan-quoc-l0-c3?cp=9">9</a></li>
                        <li class="hidden-sm hidden-xs"><a
                                    href="https://muaban.net/mua-ban-nha-dat-cho-thue-toan-quoc-l0-c3?cp=10">10</a></li>
                        <li><a href="https://muaban.net/mua-ban-nha-dat-cho-thue-toan-quoc-l0-c3?cp=2"><i
                                        class="fa fa-angle-right"></i></a></li>
                    </ul>
                </div>
                <!--Paging:End-->

                <div class="clearfix"></div>
            </div>
            <div class="mbn-banner visible-lg" id="banner-bottom"></div>
        </div>
        <div class="mbn-box-right">
            <div class="banner-left">
                <div id="ads-right-top" class="hidden-xs"></div>


                <div class="mbn-box-ads">
                    <div class="mbn-title-header">
                        <span class="title-special">Tin quảng cáo</span>
                        <button id="mbn-classified-ads-next" data-gtm-event="mbn-event-all"
                                data-gtm-category="mbn-listing-spright" data-gtm-action="listing-spright-posting-next"
                                class="btn special-ctn-next">
                            <i class="icon icon-right218"></i>
                        </button>
                        <button id="mbn-classified-ads-prev" data-gtm-event="mbn-event-all"
                                data-gtm-category="mbn-listing-spright" data-gtm-action="listing-spright-posting-back"
                                class="btn special-ctn-next">
                            <i class="icon icon-left207"></i>
                        </button>

                        <span class="title-qc">
            <a data-gtm-event="mbn-event-link" data-gtm-category="mbn-listing-spright"
               data-gtm-action="listing-spright-help"
               href="https://muaban.net/uploads/huong-dan/bang_gia/tin-quang-cao/index.html"><i
                        class="icon icon-QuestionMark"></i></a>
        </span>
                        <div class="clearfix"></div>
                    </div>
                    <div class="clearfix"></div>
                    <ul id="mbn-classified-ads" class="hidden-xs">
                        <?php echo $this->sidebarReal($this->arrParam);?>


                    </ul>
                    <div id="owl-carousel-ads" class="owl-carousel visible-xs"></div>
                    <div class="clearfix"></div>
                </div>

                <div class="mbn-box-ads mbn-box-bds-link">
                    <div class="mbn-title-header">
                        <span class="title-special">Tỉnh thành</span>
                        <div class="clearfix"></div>
                    </div>
                    <div class="clearfix"></div>
                    <ul id="mbn-classified-ads" class="hidden-xs">
                        <li>
                            <a data-gtm-event="mbn-event-link" data-gtm-category="mbn-linked-box"
                               data-gtm-action="listing-category-l59-c3"
                               href="/mua-ban-nha-dat-cho-thue-ho-chi-minh-l59-c3"><i class="fa fa-caret-right"></i>&nbsp;<span>TP.HCM</span></a>&nbsp;<span>(1079513)</span>
                        </li>
                        <li>
                            <a data-gtm-event="mbn-event-link" data-gtm-category="mbn-linked-box"
                               data-gtm-action="listing-category-l24-c3"
                               href="/mua-ban-nha-dat-cho-thue-ha-noi-l24-c3"><i
                                        class="fa fa-caret-right"></i>&nbsp;<span>Hà Nội</span></a>&nbsp;<span>(349866)</span>
                        </li>
                        <li>
                            <a data-gtm-event="mbn-event-link" data-gtm-category="mbn-linked-box"
                               data-gtm-action="listing-category-l15-c3"
                               href="/mua-ban-nha-dat-cho-thue-da-nang-l15-c3"><i
                                        class="fa fa-caret-right"></i>&nbsp;<span>Đà Nẵng</span></a>&nbsp;<span>(56998)</span>
                        </li>
                        <li>
                            <a data-gtm-event="mbn-event-link" data-gtm-category="mbn-linked-box"
                               data-gtm-action="listing-category-l28-c3"
                               href="/mua-ban-nha-dat-cho-thue-hai-phong-l28-c3"><i class="fa fa-caret-right"></i>&nbsp;<span>Hải Phòng</span></a>&nbsp;<span>(11725)</span>
                        </li>
                        <li>
                            <a data-gtm-event="mbn-event-link" data-gtm-category="mbn-linked-box"
                               data-gtm-action="listing-category-l13-c3"
                               href="/mua-ban-nha-dat-cho-thue-can-tho-l13-c3"><i
                                        class="fa fa-caret-right"></i>&nbsp;<span>Cần Thơ</span></a>&nbsp;<span>(3037)</span>
                        </li>
                        <li>
                            <a data-gtm-event="mbn-event-link" data-gtm-category="mbn-linked-box"
                               data-gtm-action="listing-category-l09-c3"
                               href="/mua-ban-nha-dat-cho-thue-binh-duong-l09-c3"><i class="fa fa-caret-right"></i>&nbsp;<span>Bình Dương</span></a>&nbsp;<span>(19859)</span>
                        </li>
                        <li>
                            <a data-gtm-event="mbn-event-link" data-gtm-category="mbn-linked-box"
                               data-gtm-action="listing-category-l01-c3"
                               href="/mua-ban-nha-dat-cho-thue-an-giang-l01-c3"><i
                                        class="fa fa-caret-right"></i>&nbsp;<span>An Giang</span></a>&nbsp;<span>(195)</span>
                        </li>
                        <li>
                            <a data-gtm-event="mbn-event-link" data-gtm-category="mbn-linked-box"
                               data-gtm-action="listing-category-l02-c3"
                               href="/mua-ban-nha-dat-cho-thue-ba-ria-vung-tau-l02-c3"><i class="fa fa-caret-right"></i>&nbsp;<span>Bà Rịa - Vũng Tàu</span></a>&nbsp;<span>(5250)</span>
                        </li>
                        <li>
                            <a data-gtm-event="mbn-event-link" data-gtm-category="mbn-linked-box"
                               data-gtm-action="listing-category-l03-c3"
                               href="/mua-ban-nha-dat-cho-thue-bac-giang-l03-c3"><i class="fa fa-caret-right"></i>&nbsp;<span>Bắc Giang</span></a>&nbsp;<span>(133)</span>
                        </li>
                        <li>
                            <a data-gtm-event="mbn-event-link" data-gtm-category="mbn-linked-box"
                               data-gtm-action="listing-category-l05-c3"
                               href="/mua-ban-nha-dat-cho-thue-bac-lieu-l05-c3"><i
                                        class="fa fa-caret-right"></i>&nbsp;<span>Bạc Liêu</span></a>&nbsp;<span>(10)</span>
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>


                <div class="mbn-box-rss-blog">
                    <div class="mbn-title-header">
                        <span class="title-special">Cẩm nang mua bán</span>
                        <div class="clearfix"></div>
                    </div>
                    <div class="clearfix"></div>
                    <ul>

                        <?php echo $this->blkSlideNews();?>


                    </ul>
                    <div class="clearfix"></div>
                </div>

            </div>

        </div>
    </div>
</div>