<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:og="http://ogp.me/ns#" xmlns:fb="http://www.facebook.com/2008/fbml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <?php echo $this->headTitle();?>
   

    <!-- Meta -->
    <?php echo $this->headMeta()
            ->appendName('description', 'Chuyên trang mua bán nhà đất, bất động sản, bán nhà, bán đất - Thông tin mua, bán, nhà, đất, căn hộ, chung cư, phòng, cao ốc, biệt thự cao cấp, mặt bằng, văn phòng, kho bãi, nhà xưởng, dự án đất đai, dự án bất động sản, dự án đầu tư được cập nhật liên tục và chính xác.')
            ->prependName('keywords','Bat dong san, nha dat, mua ban nha dat, cho thue, mua, ban, nha, dat, can ho, biet thu, chung cu, phong, dat dai, du an, bang gia, luat, moi gioi, nguoi thu nhap thap, mau nha dep, phong thuy, nha o, phong khach, nha bep, huong nha, Ho Chi Minh, Ha Noi, Hai Phong, Da Nang, Binh Duong, Vung Tau, quan, huyen, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, Binh Tan, Binh Thanh, Go Vap, Phu Nhuan, Tan Binh, Tan Phu, Thu Duc, Binh Chanh, Can Gio, Cu Chi, Hoc Mon, Nha Be')
            //->appendHttpEquiv('REFRESH', '600')
            
    ?>

   <!-- Le styles -->
    <?php echo $this->headLink(array(
                  'rel' => 'shortcut icon',
                  'type' => 'image/vnd.microsoft.icon',
                  'href' => TEMPLATE_URL . '/default/images/favicon.png'
                ))
                ->appendStylesheet(TEMPLATE_URL . '/admin/css/bootstrap.css?v4.0')
                ->appendStylesheet(TEMPLATE_URL . '/admin/css/font-awesome.css?v4.0')
                ->appendStylesheet(TEMPLATE_URL . '/admin/css/style.css?v4.1.2')
                ->appendStylesheet(TEMPLATE_URL . '/admin/css/style_default.css?v4.1.2')
                ->appendStylesheet(TEMPLATE_URL . '/admin/css/jquery-ui-1.9.2.custom.css?v4.0')
                ->appendStylesheet(TEMPLATE_URL . '/admin/css/iselector.css?v4.0')
                ->appendStylesheet(TEMPLATE_URL . '/admin/css/jquery.fancybox.css?v4.0')
                ->appendStylesheet(TEMPLATE_URL . '/admin/css/imodal.css?v4.0');
    ?>

    <script type="text/javascript" src="<?php echo TEMPLATE_URL;?>/admin/js/jquery.min.js?v4.0"></script>
    

    <script type="text/javascript">        var $j = jQuery.noConflict();</script>

    <!-- Scripts -->
    <?php echo $this->headScript()
            
            ->appendFile(TEMPLATE_URL . '/admin/js/jquery-ui.min.js?v4.0')
            ->appendFile(TEMPLATE_URL . '/admin/js/common.js?v4.0')
            ->appendFile(TEMPLATE_URL . '/admin/js/iselector.js?v4.0')
            ->appendFile(TEMPLATE_URL . '/admin/js/admin.js?v4.0')
            ->appendFile(TEMPLATE_URL . '/admin/js/imodal.js?v4.0')
            ->appendFile(TEMPLATE_URL . '/admin/js/bootstrap.min.js?v4.0')
            ->appendFile(TEMPLATE_URL . '/admin/js/scripts.js?v4.0')
            ->appendFile(TEMPLATE_URL . '/admin/js/submit.js');
     ?>

      
    

    
    <script type="text/javascript">
        //<![CDATA[
        //var _MediaDomain = 'http://media.bizwebmedia.net';
        //]]>
    </script>
    
    
    <script type="text/javascript">
        function beginKeepAlive() {
            setTimeout("keepAlive()", 60000); // every 1 min
        }
        function keepAlive() {
            var rand = Math.random();
            $j.get("/Handlers/KeepAlive.ashx?rand=" + rand, null, function (data) {
                beginKeepAlive();
            }, "text");
        }
        function checkWindowSize() {
            var windowWidth = $j(window).width();
            if (windowWidth < 1024) {
                $j(".iconsupport, .linkaction").hide();
            }
            else {
                $j(".iconsupport, .linkaction").show();
            }
        }
        $j(function () {
            beginKeepAlive();
            checkWindowSize();
            window.onresize = checkWindowSize;
        });
    </script>
    <script type="text/javascript">
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date(); a = s.createElement(o),
                m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
        })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');
        ga('create', 'UA-19570215-2', 'bizwebvietnam.com');
        ga('send', 'pageview');
    </script>
    <script>(function () {
        var _fbq = window._fbq || (window._fbq = []);
        if (!_fbq.loaded) {
            var fbds = document.createElement('script');
            fbds.async = true;
            fbds.src = '//connect.facebook.net/en_US/fbds.js';
            var s = document.getElementsByTagName('script')[0];
            s.parentNode.insertBefore(fbds, s);
            _fbq.loaded = true;
        }
        _fbq.push(['addPixelId', '293334697509343']);
    })();
        window._fbq = window._fbq || [];
        window._fbq.push(['track', 'PixelInitialized', {}]);
    </script>
    <noscript><img height="1" width="1" alt="" style="display:none" src="https://www.facebook.com/tr?id=293334697509343&amp;ev=NoScript" /></noscript>

    <script>(function () {
        var _fbq = window._fbq || (window._fbq = []);
        if (!_fbq.loaded) {
            var fbds = document.createElement('script');
            fbds.async = true;
            fbds.src = '//connect.facebook.net/en_US/fbds.js';
            var s = document.getElementsByTagName('script')[0];
            s.parentNode.insertBefore(fbds, s);
            _fbq.loaded = true;
        }
        _fbq.push(['addPixelId', '293334697509343']);
    })();
            window._fbq = window._fbq || [];
            window._fbq.push(['track', 'PixelInitialized', {}]);
    </script>
    <noscript><img height="1" width="1" alt="" style="display:none" src="https://www.facebook.com/tr?id=293334697509343&amp;ev=NoScript" /></noscript>
</head>
<body class="fixed-top">
    <div id="AjaxLoading">
        <img src="<?php echo TEMPLATE_URL;?>/admin/images/ajax-load.gif" alt="" />&nbsp; Đang tải... Vui lòng chờ...</div>
   

<script type="text/javascript">
//<![CDATA[
var theForm = document.forms['form1'];
if (!theForm) {
    theForm = document.form1;
}
function __doPostBack(eventTarget, eventArgument) {
    if (!theForm.onsubmit || (theForm.onsubmit() != false)) {
        theForm.__EVENTTARGET.value = eventTarget;
        theForm.__EVENTARGUMENT.value = eventArgument;
        theForm.submit();
    }
}
//]]>
</script>



<script src="<?php echo TEMPLATE_URL;?>/admin/js/fancybox-2/jquery.mousewheel-3.0.6.pack.js" type="text/javascript"></script>
<script src="<?php echo TEMPLATE_URL;?>/admin/js/fancybox-2/jquery.fancybox.pack.js" type="text/javascript"></script>

        <div class="PageHeader">
            <?php include_once 'html/header.php';?>
        </div>



        
    <div id="container" class="row-fluid">
        <div class="clear" style="height: 10px">
        </div>
        

<style type="text/css">
.boder_menu {
    min-width: 1023px;
    width: 100%;
    background-color:#1799a3;
    border-bottom: solid 1px #14848d;
}
#menu {
    display: block;
    float: none;
    height: 39px;
    line-height: 39px;
    margin: auto;
}
#menu ul {
    float: left;
    list-style: none outside none;
    margin-left:20px;
}
#menu ul li {
    float: left;
    position: relative;
}
#menu ul li ul li {
    background: none repeat scroll 0 0 rgba(0, 0, 0, 0);
    border: medium none;
    line-height: normal;
    margin: 0;
    padding: 0;
}
#menu ul li ul li {
    width: 100%;
}
#menu ul li a {
    background-image: url("../../images/icon_sub.gif");
    background-position: right center;
    background-repeat: no-repeat;
    color: #ffffff;
    display: block;
    font-size: 14px;
    font-weight: normal;
    height: 38px;
    line-height: 38px;
    margin-right: 12px;
    padding: 0 15px 0 6px;
}
#menu li:hover a, #menu li.current a {
    background-image: url("../../images/icon_sub.gif");
    color: #FFFFFF;
    text-decoration:none;
}
#menu li {
    margin: 0 4px 0 0;
    padding-bottom: 3px;
}
#menu li:hover {
    background-color:#20AEB9;
}
#menu li ul {
    -moz-border-bottom-colors: none;
    -moz-border-left-colors: none;
    -moz-border-right-colors: none;
    -moz-border-top-colors: none;
    background-color: #20aeb9;
    border-color: #00ABC9 -moz-use-text-color -moz-use-text-color;
    border-image: none;
    border-right: medium none;
    border-style: none;
    border-width: 3px medium medium;
    /*box-shadow: 5px 5px 0 #D9D9D9;*/
    display: none;
    margin: 0;
    padding: 0;
    position: absolute;
    top: 40px;
    width: 240px;
    z-index: 100;
}
#menu li ul li {
    background: none repeat scroll 0 0 rgba(0, 0, 0, 0);
    border: medium none;
    line-height: normal;
    padding: 0;
}
#menu li ul li a, #menu li:hover ul li a {
    background: none repeat scroll 0 0 rgba(0, 0, 0, 0);
    border-bottom: 1px solid #41bbc4;
    color: #FFFFFF;
    margin: 0 12px;
    font-size:14px;
    padding-left:10px;
}

#menu li ul li a {
    padding: 0;
}
.m_icon {
    float: left;
    padding: 12px 5px 0 0;
    text-align: center;
    width: 23px;
}
#menu li:hover, #menu li.current {
    background-image: url("../../images/menu_hover.gif");
    background-position: center bottom;
    background-repeat: repeat-x;
}
#menu li ul li:hover {
    background: none repeat scroll 0 0 rgba(0, 0, 0, 0);
}
#menu li:hover ul {
    display: block;
}
#menu li ul li a:hover {
    border-bottom-color:#1799a3;
}
#menu li ul li:hover {
    background: #1799a3;
    border: medium none;
}
#menu li ul li.last a {
    border: medium none;
}
#menu .MenuText i {
    font-size:16px;
}
#menu .MenuText i.icon-shopping-cart, #menu .MenuText i.icon-gift, #menu .MenuText i.icon-globe, #menu .MenuText i.icon-signin {
    font-size:18px;
}
</style>

<div class="boder_menu">
    <?php include_once 'html/navigation.php';?>
</div>

        
        <div id="main-content">
            <div class="container-fluid">
                <div style="width: 100%; margin: 0 auto;">
                    


    <?php echo $this->content;?> 

                </div>
            </div>
            <div style="color: Gray; text-align:center;">
               Website bất động sản
            </div>
            <div style="height: 10px; margin-top: 40px;">
            </div>
        </div>
    </div>
    <span id="additionalAttr"></span>
    <script type="text/javascript">
        $j("#registerAd").fancybox({
            'width': 780,
            'height': 550,
            'autoScale': false,
            'transitionIn': 'fade',
            'transitionOut': 'fade',
            'speedIn': 500,
            'speedOut': 300,
            'titleShow': false,
            'hideOnOverlayClick': false,
            'type': 'iframe',
            onStart: function () {
                var text =
                "<style type='text/css'>" +
                "#fancybox-outer{ background: transparent; }" +
                "#fancy-bg-n, #fancy-bg-ne, #fancy-bg-e, #fancy-bg-se, #fancy-bg-s, #fancy-bg-sw, #fancy-bg-w, #fancy-bg-nw{ background-image: none; }" +
                "#fancybox-close{ right: 54px; top: 23px; background-image: url('/sites/admin/images/registerad/close.png'); background-position: center center; background-repeat: no-repeat; }" +
                "</style>";
                $j("#additionalAttr").html(text);
            },
            onCancel: function () { $j("#additionalAttr").html(''); },
            onCleanup: function () { $j("#additionalAttr").html(''); },
            onClose: function () { $j("#additionalAttr").html(''); }
        });
    </script>
    <!-- Google Code dành cho Thẻ tiếp thị lại -->
    <!--------------------------------------------------
    Không thể liên kết thẻ tiếp thị lại với thông tin nhận dạng cá nhân hay đặt thẻ tiếp thị lại trên các trang có liên quan đến danh mục nhạy cảm. Xem thêm thông tin và hướng dẫn về cách thiết lập thẻ trên: http://google.com/ads/remarketingsetup
    --------------------------------------------------->
    <script type="text/javascript">
        /* <![CDATA[ */
        var google_conversion_id = 967817189;
        var google_custom_params = window.google_tag_params;
        var google_remarketing_only = true;
        /* ]]> */
    </script>
    <script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js"></script>
    <noscript>
        <div style="display:inline;">
            <img height="1" width="1" style="border-style:none;" alt="" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/967817189/?value=0&amp;guid=ON&amp;script=0"/>
        </div>
    </noscript>
    </form>
</body>
</html>
