<?php
$myForm = $this->myForm;
$myForm->prepare();
$elementId					= $myForm->get('id');
$elementTitle 				= $myForm->get('group_name');
$elementGroup_acp			= $myForm->get('group_acp');
$elementGroup_default		= $myForm->get('group_default');
$elementStatus				= $myForm->get('status');
$elementColor 				= $myForm->get('color');
$elements = array(
	array(
		'label'				=>	$this->formLabel($elementTitle),
		'input'				=>	$this->formElement($elementTitle),
		'class'				=>	'col-sm-9',
		'required'			=>	'*',
		'tooltiptitle'		=>	'Tiêu đề',
		'tooltipmessage'	=>	'Nhập Tiêu đề',
	),
	array(
		'label'				=>	$this->formLabel($elementGroup_acp),
		'input'				=>	$this->formElement($elementGroup_acp),
		'class'				=>	'col-sm-9',
		'required'			=>	'',
		'tooltiptitle'		=>	'Admin Control Panel',
		'tooltipmessage'	=>	'Admin Control Panel',
	),
	array(
		'label'				=>	$this->formLabel($elementGroup_default),
		'input'				=>	$this->formElement($elementGroup_default),
		'class'				=>	'col-sm-9',
		'required'			=>	'',
		'tooltiptitle'		=>	'Group default',
		'tooltipmessage'	=>	'Group default',
	),
	array(
		'label'				=>	$this->formLabel($elementStatus),
		'input'				=>	$this->formElement($elementStatus),
		'class'				=>	'col-sm-9',
		'required'			=>	'',
		'tooltiptitle'		=>	'Status',
		'tooltipmessage'	=>	'Status',
	),
	array(
		'label'				=>	$this->formLabel($elementColor),
		'input'				=>	$this->formElement($elementColor),
		'class'				=>	'col-sm-9',
		'required'			=>	'',
		'tooltiptitle'		=>	'Status',
		'tooltipmessage'	=>	'Status',
	),
	
);

$messagesErrors = $this->elementErrors(array(
	'group_name'					=>	$elementTitle,

	
));





 
       


?>


<form name="appForm" method="post" action="" enctype="multipart/form-data">

<?php include('sublink/index.php');?>
    <!--Nội dung load ở đây-->                   
    <div id="cph_Main_ContentPane">
        <div class="widget">
            <?php include('toolbar/index.php');?>
            
            <div class="widget-body">
            	<?php echo $messagesErrors;?>
            	<?php echo $this->errorMessages($this->error,'admin');?>
	   			<table class="admintable" style="width: 100%;">
	    			<?php  echo $this->form()->openTag($myForm);
					echo $this->partialLoop('admin/form-group.phtml',$elements);
					echo $this->form()->closeTag();
					?>
				</table>
           	</div>
        </div> 
   	</div> 
</form>

	<link rel="stylesheet" href="<?php echo TEMPLATE_URL;?>/admin/css/colorpicker.css" type="text/css" />
	<script type="text/javascript" src="<?php echo TEMPLATE_URL;?>/admin/js/jquery.js"></script>
	<script type="text/javascript" src="<?php echo TEMPLATE_URL;?>/admin/js/colorpicker.js"></script>
    <script type="text/javascript" src="<?php echo TEMPLATE_URL;?>/admin/js/eye.js"></script>
    <script type="text/javascript" src="<?php echo TEMPLATE_URL;?>/admin/js/utils.js"></script>
    
    <script type="text/javascript">
    $('#colorpickerField1, #colorpickerField2, #colorpickerField3').ColorPicker({
	onSubmit: function(hsb, hex, rgb, el) {
		$(el).val(hex);
		$(el).ColorPickerHide();
	},
	onBeforeShow: function () {
		$(this).ColorPickerSetColor(this.value);
	}
})
.bind('keyup', function(){
	$(this).ColorPickerSetColor(this.value);
});
    </script> 


   	      	 	