<?php
$myForm = $this->myForm;
//echo $this->form()->openTag($this->myForm);
$avatar         = (!empty($this->item->avatar))  ? UPLOAD_URL .'/avatar/'.$this->item->avatar :  TEMPLATE_URL .'/admin/images/NoImage.jpg';




$messagesErrors = $this->elementErrors(array(
	'password_old'				=>	$myForm->get('password_old'),
	'password'					=>	$myForm->get('password'),
	'confirm-password'			=>	$myForm->get('confirm-password'),
	
),'user');

$xhtmlError     =  $this->errorMessages($this->error,'user');
?>
<div id="BoxExchangePass">
	<?php echo $messagesErrors .$xhtmlError;?>
	<div class="TitleBox">
        
        <h2>
            Đổi mật khẩu</h2>
	</div>
	<div class="DesBoxExchangePass">
		<form name="appForm" id="appForm" method="post" action="" enctype="multipart/form-data">
		<table cellspacing="5" cellpadding="0" border="0">
			<tbody>
				<tr>
					<td colspan="2" align="center"><span id="MainContent_ctl00_lblThongBao" style="color:Red;"></span>
					</td>
				</tr>
				<tr>
					<td align="right" width="38%"><span class="star">*</span> <label>Mật khẩu cũ:</label></td>
					<td width="62%">                   
                        <?php echo  $this->formPassword($myForm->get('password_old'));?>
                    </td>
				</tr>
				<tr>
					<td align="right"><span class="star">*</span> <label>Mật khẩu mới:</label></td>
					<td>
                         <?php echo  $this->formPassword($myForm->get('password'));?>
                    </td>
				</tr>
				<tr>
					<td align="right"><span class="star">*</span> <label>Xác định mật khẩu:</label></td>
					<td>                    
                     <?php echo  $this->formPassword($myForm->get('confirm-password'));?>
                    </td>
				</tr>
				<tr>
					<td></td>
					<td>
						<ul class="Btform">
							<li>
								<div class="Bgbutton"><div> <a href="#" onclick="OnSubmitForm('<?php echo $this->basePath($this->currentController . '/change-password/');?>')" id="MainContent_ctl00_btnDongY">Đổi mật khẩu</a>
									</div>
								</div>
							</li>                           
						</ul>
					</td>
				</tr>
			</tbody>
		</table>
	</form>
	</div>
</div>