<?php
if(!empty($this->_data)){
	$xhtml = '';
	foreach ($this->_data as $item) {
		$image        = (!empty($item['flash_image']))  ? UPLOAD_URL .'/ads/'.$item['flash_image'] :  TEMPLATE_URL .'/admin/images/NoImage.jpg';
		$xhtml .= '<a href="'.$item['url'].'" target="_BLANK" title="'.$item['name'].'" alt ="'.$item['name'].'">
		              <img src="'.$image.'" width="'.$item['width'].'" height="'.$item['height'].'" title="'.$item['name'].'" alt ="'.$item['name'].'" style="margin-bottom: 5px; margin-top: 5px" />
		          </a>';
	}
	echo $xhtml;
}
