
<?php
$isXmlHttpRequest = $this->isXmlHttpRequest;
if($isXmlHttpRequest == true){
$xhtml = '';
if(!empty($this->items)){
    foreach($this->items as $item){
       
        $id             = $item['id'];
        $title          = $item['title'];
        $description    = $item['description'];   
        $date_time      = $item['date_time'];
        $image          = (!empty($item['images']))  ? UPLOAD_URL .'/fengshui-news/'.$item['images'] :  TEMPLATE_URL .'/admin/images/NoImage.jpg';
        
        $urlDetail   = $this->url('DetailFengshuiRoute',array(
            'controller'        => 'news',
            'action'            => 'detail',
            'namecategory'      => \ZendVN\Url\FriendlyLink::filter($item['name_category']),
            'title'             => \ZendVN\Url\FriendlyLink::filter($title),
            'cid'               => $item['cat_id'],
            'id'                => $item['id'],
            'extension'         => 'html',
        ));

        $xhtml .= '<li>
                    <h3>
                        <a title="'.$title.'" href="'.$urlDetail.'">
                        <img width="204" height="153" title="'.$title.'" alt="'.$title.'" src="'.$image.'"></a>
                        <a title="'.$title.'" href="'.$urlDetail.'">'.$title.'</a> 
                    </h3>
                </li>';

                    

                             
    }
}

//Category
$xhtmlCategory = '';
if(!empty($this->listCategory)){
    foreach ($this->listCategory as $key => $item) {
        $urlCategory = $this->url('CategoryFengshuiRoute',array(
          'module'=>'home',
          'controller'  =>'fengshui',
          'action'      =>'category',
          'name'        => \ZendVN\Url\FriendlyLink::filter($item['name']),
          'page'        => '1',
          'id'          => $item['id'],
           'extension'  => 'html',
        ));
        $xhtmlCategory .= '<a title="'.$item['name'].'" href="'.$urlCategory.'">'.$item['name'].'</a>';
    }
}

?>
<ul class="leftListing3">
    <?php echo $xhtml;?>
</ul>

  
 <?php
    $paramsUrl  = array(
       'module'        => 'home',
        'controller'   => 'fengshui',
        'action'       => 'index',
        'page'         => '1',
    );
    echo $this->paginationControl($this->paginator , 'sliding' , 'home/business/paginator.phtml', array(
        'router'    => 'ListFengshuiRoute',
        'arrParam'  =>$paramsUrl,
    )); 
 ?>



<div id="MainContent_ArticleList1_SubMenu2_divContent" class="moreBox"><?php echo $xhtmlCategory;?></div>



<?php
}else{
    echo 'not ajax';
}
?>
