
<!DOCTYPE HTML>
<html lang="en-US">
<head profile="http://gmpg.org/xfn/11">
<title>AndroidDev101 &raquo; Not Found</title>

<meta charset="UTF-8" />
<meta name="generator" content="WordPress 4.0.1" />
<meta name="description" content="Android dev 101" />
<!-- leave this for stats -->
<link rel="stylesheet" href="<?php echo TEMPLATE_URL;?>/default/css/style_404.css" type="text/css" media="screen" />

<link rel='stylesheet' id='jetpack_css-css'  href='http://androiddev101.com/wp-content/plugins/jetpack/css/jetpack.css?ver=3.3' type='text/css' media='all' />
<!-- This site uses the Yoast Google Analytics plugin v5.1.2 - Universal disabled - https://yoast.com/wordpress/plugins/google-analytics/ -->
<script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-39186031-1']);
    _gaq.push(['_gat._forceSSL']);
    _gaq.push(['_trackPageview','/404.html?page=' + document.location.pathname + document.location.search + '&from=' + document.referrer]);

    (function () {
        var ga = document.createElement('script');
        ga.type = 'text/javascript';
        ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(ga, s);
    })();

</script>
<!-- / Yoast Google Analytics -->
<script type='text/javascript' src='http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js?ver=4.0.1'></script>

<meta name="generator" content="WordPress 4.0.1" />
        <style type="text/css">
            .ads {
                position: relative;
                text-align: center;
                clear: both;
            }
        </style><link rel="icon" type="image/png" href="http://androiddev101.com/wp-content/themes/pixelart101/image/favicon.png" />

<!--[if lt IE 9]>
<script src="http://androiddev101.com/wp-content/themes/pixelart101/js/html5.js" type="text/javascript"></script>
<![endif]-->

<meta name='robots' content='noindex,follow' />
<!-- This site uses the Yoast Google Analytics plugin v5.1.2 - Universal disabled - https://yoast.com/wordpress/plugins/google-analytics/ -->
<script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-39186031-1']);
    _gaq.push(['_gat._forceSSL']);
    _gaq.push(['_trackPageview','/404.html?page=' + document.location.pathname + document.location.search + '&from=' + document.referrer]);

    (function () {
        var ga = document.createElement('script');
        ga.type = 'text/javascript';
        ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(ga, s);
    })();

</script>
<!-- / Yoast Google Analytics -->
<link rel="EditURI" type="application/rsd+xml" title="RSD" href="http://androiddev101.com/xmlrpc.php?rsd" />
<link rel="wlwmanifest" type="application/wlwmanifest+xml" href="http://androiddev101.com/wp-includes/wlwmanifest.xml" /> 
<meta name="generator" content="WordPress 4.0.1" />
        <style type="text/css">
            .ads {
                position: relative;
                text-align: center;
                clear: both;
            }
        </style>

</head>
<body>

    <section id="error-page">

        <a id="back_button" href="<?php echo $this->url('home',array('module'=>'home','controller'=>'index','action'=>'index'));?>">Trở lại trang chủ</a>
        <div id="error-message" style="background:url(<?php echo TEMPLATE_URL;?>/default/images/error_message.jpg) bottom center no-repeat;">ERROR #404</div>
    </section><!-- #container -->

<div class="debug">
    <?php var_dump($this->arrParam)?>
</div>


</body>
</html>
    <script src="http://stats.wp.com/e-201509.js" type="text/javascript"></script>
    <script type="text/javascript">
    st_go({v:'ext',j:'1:3.3',blog:'48303068',post:'0',tz:'-5'});
    var load_cmc = function(){linktracker_init(48303068,0,2);};
    if ( typeof addLoadEvent != 'undefined' ) addLoadEvent(load_cmc);
    else load_cmc();
    </script>