<?php 
//require_once TEMPLATE_PATH . DS . 'home' . DS . 'inc' . DS . 'left.php';
//require_once TEMPLATE_PATH . DS . 'home' . DS . 'inc' . DS . 'right.php';
?>
<div class="ct-in-l">
	<?php require_once TEMPLATE_PATH . DS . 'home' . DS . 'box' . DS . 'breadcrumb.php';?>
	<div class="dv-ct-detail">
		<h2>Cho thuê Bất động sản, Cho thuê nhà đất</h2>
	</div>
    <?php require_once TEMPLATE_PATH . DS . 'home' . DS . 'inc' . DS . 'content-adv-top.php';?>	
	<?php require_once TEMPLATE_PATH . DS . 'home' . DS . 'box' . DS . 'content.php';?>	
	<?php require_once TEMPLATE_PATH . DS . 'home' . DS . 'inc' . DS . 'content-adv-bottom.php';?>
	
</div>
<div class="ct-in-r">
    <?php require_once TEMPLATE_PATH . DS . 'home' . DS . 'inc' . DS . 'sidebar-search.php';?>	
    <?php require_once TEMPLATE_PATH . DS . 'home' . DS . 'inc' . DS . 'sidebar-hotline.php';?>	
    <?php require_once TEMPLATE_PATH . DS . 'home' . DS . 'inc' . DS . 'sidebar-adv1.php';?>	
	<?php require_once TEMPLATE_PATH . DS . 'home' . DS . 'inc' . DS . 'sidebar-pro.php';?>
	<?php //require_once TEMPLATE_PATH . DS . 'home' . DS . 'inc' . DS . 'sidebar-price.php';?>
	<?php require_once TEMPLATE_PATH . DS . 'home' . DS . 'inc' . DS . 'sidebar-type.php';?>
	<?php require_once TEMPLATE_PATH . DS . 'home' . DS . 'inc' . DS . 'sidebar-project.php';?>
	<?php require_once TEMPLATE_PATH . DS . 'home' . DS . 'inc' . DS . 'sidebar-adv1.php';?>	
	<?php require_once TEMPLATE_PATH . DS . 'home' . DS . 'inc' . DS . 'sidebar-news.php';?>
</div>