<div class="main-container lazy">

    <div class="posting-line"></div>
    <div class="container clearfix">
        <div class="clearfix">

            <div class="breadcrumb breadcrumbs">
                <div class="rdfa-breadcrumb">
                    <div xmlns:v="http://rdf.data-vocabulary.org/#">
                        <div>
                            <span class="breadcrumbs-title"> </span>
                            <span typeof="v:Breadcrumb">
                    <a data-gtm-event="mbn-event-link" data-gtm-category="mbn-listing-nav" data-gtm-action="/"
                       rel="v:url" property="v:title" href="https://muaban.net/" class="home">Trang chủ</a>
                </span>
                            <span class="icon icon-arrow-s"></span>
                            <span typeof="v:Breadcrumb"> <a data-gtm-event="mbn-event-link" data-gtm-category="mbn-listing-nav" data-gtm-action="listing-nav-https://muaban.net/ho-chi-minh"
                                                            rel="v:url" property="v:title" href="https://muaban.net/ho-chi-minh" title="TP.HCM">TP.HCM</a></span>
                            <span class="icon icon-arrow-s"></span>
                            <span typeof="v:Breadcrumb"> <a data-gtm-event="mbn-event-link" data-gtm-category="mbn-listing-nav" data-gtm-action="listing-nav-https://muaban.net/mua-ban-nha-dat-cho-thue-ho-chi-minh-l59-c3"
                                                            rel="v:url" property="v:title" href="https://muaban.net/mua-ban-nha-dat-cho-thue-ho-chi-minh-l59-c3" title="Bất động sản">Bất động sản</a></span>
                            <span class="icon icon-arrow-s"></span>
                            <span typeof="v:Breadcrumb"> <a data-gtm-event="mbn-event-link" data-gtm-category="mbn-listing-nav" data-gtm-action="listing-nav-https://muaban.net/ban-nha-can-ho-ho-chi-minh-l59-c32"
                                                            rel="v:url" property="v:title" href="https://muaban.net/ban-nha-can-ho-ho-chi-minh-l59-c32" title="Bán nhà, Căn hộ">Bán nhà, Căn hộ</a></span>
                            <span class="icon icon-arrow-s"></span>
                            <span typeof="v:Breadcrumb"> <a data-gtm-event="mbn-event-link" data-gtm-category="mbn-listing-nav" data-gtm-action="listing-nav-https://muaban.net/nha-mat-tien-ho-chi-minh-l59-c3201"
                                                            rel="v:url" property="v:title" href="https://muaban.net/nha-mat-tien-ho-chi-minh-l59-c3201" title="Nhà mặt tiền/phố">Nhà mặt tiền/phố</a></span>

                        </div>
                    </div>
                </div>
            </div>

        </div>
        <div class="cl-detail clearfix">
            <div class="dt-content col-sm-12 col-xs-12 clearfix" id="dvContent">
                <div class="cl-title clearfix">
                    <h1>
                        Nhà bán Gò Vấp, đúc 4 tấm, 4x17m hẻm 5m Bùi Quang Là Giá 3.8 tỷ
                    </h1>
                </div>
                <div class="cl-price-sm clearfix">
                    <span class="visible-lg float-left">
                        <i class="icon icon-dollar103"></i>&nbsp;
                        3.800.000.000 đ
                    </span>
                    <span class="visible-lg float-left"><i class="icon icon-map5"></i>&nbsp;Quận Gò Vấp - TP.HCM</span>
                    <span class="float-left"><i class="icon icon-clock96"></i>&nbsp;Ngày 27/07/2017</span>
                    <span class="float-left"><i class="icon icon-tag31"></i>&nbsp;Mã tin: 39625058</span>
                </div>
                <div class="ct-image">
                    <div id="owl-carousel-detail" class="owl-carousel owl-theme">
                        <div class="item">

                            <img title="Nhà bán Gò Vấp, đúc 4 tấm, 4x17m hẻm 5m Bùi Quang Là Giá 3.8 tỷ 39625058" alt="Nhà bán Gò Vấp, đúc 4 tấm, 4x17m hẻm 5m Bùi Quang Là Giá 3.8 tỷ"
                                 class="lazyOwl"  data-src="https://cdn.muaban.net/cdn/images/thumb-detail/201707/24/145/1f43a901bf3147db868c84f2249950f1.jpg">
                        </div>
                        <div class="item">

                            <img title="Nhà bán Gò Vấp, đúc 4 tấm, 4x17m hẻm 5m Bùi Quang Là Giá 3.8 tỷ 39625058" alt="Nhà bán Gò Vấp, đúc 4 tấm, 4x17m hẻm 5m Bùi Quang Là Giá 3.8 tỷ"
                                 class="lazyOwl"  data-src="https://cdn.muaban.net/cdn/images/thumb-detail/201707/24/145/ae72b2af1a9f4ec1b2cebbc5e0f3e93c.jpg">
                        </div>
                        <div class="item">

                            <img title="Nhà bán Gò Vấp, đúc 4 tấm, 4x17m hẻm 5m Bùi Quang Là Giá 3.8 tỷ 39625058" alt="Nhà bán Gò Vấp, đúc 4 tấm, 4x17m hẻm 5m Bùi Quang Là Giá 3.8 tỷ"
                                 class="lazyOwl"  data-src="https://cdn.muaban.net/cdn/images/thumb-detail/201707/24/145/75ba373c1c1e417c9f255fc8381d4d6f.jpg">
                        </div>
                        <div class="item">

                            <img title="Nhà bán Gò Vấp, đúc 4 tấm, 4x17m hẻm 5m Bùi Quang Là Giá 3.8 tỷ 39625058" alt="Nhà bán Gò Vấp, đúc 4 tấm, 4x17m hẻm 5m Bùi Quang Là Giá 3.8 tỷ"
                                 class="lazyOwl"  data-src="https://cdn.muaban.net/cdn/images/thumb-detail/201707/24/145/a9358e50b6d142d78f4f05c7fb2e382f.jpg">
                        </div>
                        <div class="item">

                            <img title="Nhà bán Gò Vấp, đúc 4 tấm, 4x17m hẻm 5m Bùi Quang Là Giá 3.8 tỷ 39625058" alt="Nhà bán Gò Vấp, đúc 4 tấm, 4x17m hẻm 5m Bùi Quang Là Giá 3.8 tỷ"
                                 class="lazyOwl"  data-src="https://cdn.muaban.net/cdn/images/thumb-detail/201707/24/145/9cc3f764608845308e9b8afde0ac84b2.jpg">
                        </div>
                        <div class="item">

                            <img title="Nhà bán Gò Vấp, đúc 4 tấm, 4x17m hẻm 5m Bùi Quang Là Giá 3.8 tỷ 39625058" alt="Nhà bán Gò Vấp, đúc 4 tấm, 4x17m hẻm 5m Bùi Quang Là Giá 3.8 tỷ"
                                 class="lazyOwl"  data-src="https://cdn.muaban.net/cdn/images/thumb-detail/201707/24/145/56aa8341b6fe4428becf67bf45537103.jpg">
                        </div>
                        <div class="item">

                            <img title="Nhà bán Gò Vấp, đúc 4 tấm, 4x17m hẻm 5m Bùi Quang Là Giá 3.8 tỷ 39625058" alt="Nhà bán Gò Vấp, đúc 4 tấm, 4x17m hẻm 5m Bùi Quang Là Giá 3.8 tỷ"
                                 class="lazyOwl"  data-src="https://cdn.muaban.net/cdn/images/thumb-detail/201707/24/145/58a3d031ceb74091a74743fe187b7a2e.jpg">
                        </div>
                        <div class="item">

                            <img title="Nhà bán Gò Vấp, đúc 4 tấm, 4x17m hẻm 5m Bùi Quang Là Giá 3.8 tỷ 39625058" alt="Nhà bán Gò Vấp, đúc 4 tấm, 4x17m hẻm 5m Bùi Quang Là Giá 3.8 tỷ"
                                 class="lazyOwl"  data-src="https://cdn.muaban.net/cdn/images/thumb-detail/201707/24/145/fed3f61375b44b0da7e641f4a33d1694.jpg">
                        </div>
                    </div>
                </div>
                <div id="ct-approved" class="ct-approved visible-lg clearfix">
                        <span>
                                <span><i class="icon icon-check33"></i>&nbsp;Đã xác thực CMND&nbsp;</span>

                        </span>
                </div>

                <div class="ct-price clearfix">
                    <div class="col-md-2 col-sm-2 col-xs-3 price-name">Giá:</div>
                    <div class="col-md-10 col-sm-10 col-xs-9 price-value">
                        3.800.000.000 đ
                    </div>
                </div>
                <div class="ct-contact clearfix">
                    <div class="clearfix">
                        <div class="col-md-2 col-sm-2 col-xs-3 price-name">Liên hệ:</div>
                        <div class="col-md-10 col-sm-10 col-xs-9 contact-name">nguyễn tùng

                        </div>
                    </div>

                    <div class="clearfix">
                        <div class="col-md-2 col-sm-2 col-xs-3 price-name">Điện thoại:</div>
                        <div class="col-md-10 col-sm-10 col-xs-9 contact-mobile">
                            <span data-bind="visible:ShowMobile()==false">0906298947</span>

                        </div>
                    </div>
                </div>

                <div class="ct-body overflow clearfix">
                    - Nhà bán đúc kiên cố 4 tấm diện tích công nhận 4m x 17m, thiết kế sang trọng: 4 phòng ngủ, 5wc, phòng thờ, sân thượng trước sau.<br>-&#9;Nội thất cao cấp: nước nóng năng lượng, tủ rượu, tủ bếp, tay vịnh căm xe, màn cửa, thiết bị điện &#8211; vệ sinh cao cấp&#8230;<br>-&#9;Khu cao tầng, đường nhựa 5m cách Phan Huy Ích 100m, giáp quận Tân Bình<br>-&#9;Tiện ích: gần chợ, trường học, bệnh viện, khu vui chơi giải trí, bến xe bus<br>-&#9;Sổ hồng  năm 2017.<br>-&#9;Giá 3.8 tỷ<br>-&#9;Mọi chi tiết xin liên hệ:<br>o&#9;Tùng &#8211; 0938866755 &#8211; zalo &#8211; viber &#8211; tango<br>o&#9;Khương &#8211; 0906298947 &#8211; zalo &#8211; viber<br>o&#9;Email: nttung0110@gmail.com<br>-&#9;Miễn trung gian &#8211; quảng cáo !!!<br>-&#9;Xin chân thành cảm ơn!

                </div>

                <div class="ct-tech clearfix">
                    <div class=" tect-title clearfix">Thông tin bất động sản</div>
                    <ul class="clearfix">
                        <li class="col-md-12 col-sm-12 col-xs-12 tect-item">
                            <div>
                                <div class="col-md-2 col-sm-5 col-xs-5 item-name">Loại bất động sản:</div>
                                <div class="col-md-9 col-sm-7 col-xs-7 item-value">Nhà mặt tiền</div>
                            </div>
                        </li>
                        <li class="col-md-12 col-sm-12 col-xs-12 tect-item">
                            <div>
                                <div class="col-md-2 col-sm-5 col-xs-5 item-name">Địa chỉ:</div>
                                <div class="col-md-9 col-sm-7 col-xs-7 item-value">-</div>
                            </div>
                        </li>
                        <li class="col-md-12 col-sm-12 col-xs-12 tect-item">
                            <div>
                                <div class="col-md-2 col-sm-5 col-xs-5 item-name">Dự án:</div>
                                <div class="col-md-9 col-sm-7 col-xs-7 item-value">-</div>
                            </div>
                        </li>
                        <li class="col-md-6 col-sm-12 col-xs-12 tect-item">
                            <div>
                                <div class="col-md-5 col-sm-5 col-xs-5 item-name">Diện tích đất:</div>
                                <div class="col-md-7 col-sm-7 col-xs-7 item-value">-</div>
                            </div>
                        </li>
                        <li class="col-md-6 col-sm-12 col-xs-12 tect-item">
                            <div>
                                <div class="col-md-5 col-sm-5 col-xs-5 item-name">Tầng/Lầu:</div>
                                <div class="col-md-7 col-sm-7 col-xs-7 item-value">-</div>
                            </div>
                        </li>
                        <li class="col-md-6 col-sm-12 col-xs-12 tect-item">
                            <div>
                                <div class="col-md-5 col-sm-5 col-xs-5 item-name">Phòng ngủ:</div>
                                <div class="col-md-7 col-sm-7 col-xs-7 item-value">-</div>
                            </div>
                        </li>

                        <li class="col-md-6 col-sm-12 col-xs-12 tect-item" style="display:none">
                            <div>
                                <div class="col-md-5 col-sm-5 col-xs-5 item-name">Diện tích xây dựng:</div>
                                <div class="col-md-7 col-sm-7 col-xs-7 item-value"></div>
                            </div>
                        </li>
                        <li class="col-md-6 col-sm-12 col-xs-12 tect-item">
                            <div>
                                <div class="col-md-5 col-sm-5 col-xs-5 item-name">Phòng tắm:</div>
                                <div class="col-md-7 col-sm-7 col-xs-7 item-value">-</div>
                            </div>
                        </li>
                        <li class="col-md-6 col-sm-12 col-xs-12 tect-item">
                            <div>
                                <div class="col-md-5 col-sm-5 col-xs-5 item-name">Diện tích sử dụng:</div>
                                <div class="col-md-7 col-sm-7 col-xs-7 item-value">-</div>
                            </div>
                        </li>
                        <li class="col-md-6 col-sm-12 col-xs-12 tect-item" style="display:none">
                            <div>
                                <div class="col-md-5 col-sm-5 col-xs-5 item-name">Tổng số phòng:</div>
                                <div class="col-md-7 col-sm-7 col-xs-7 item-value"></div>
                            </div>
                        </li>
                        <li class="col-md-6 col-sm-12 col-xs-12 tect-item" style="display:none">
                            <div>
                                <div class="col-md-5 col-sm-5 col-xs-5 item-name">Năm xây dựng:</div>
                                <div class="col-md-7 col-sm-7 col-xs-7 item-value"></div>
                            </div>
                        </li>
                        <li class="col-md-6 col-sm-12 col-xs-12 tect-item" style="display:none">
                            <div>
                                <div class="col-md-5 col-sm-5 col-xs-5 item-name">Năm sửa chữa:</div>
                                <div class="col-md-7 col-sm-7 col-xs-7 item-value"></div>
                            </div>
                        </li>
                        <li class="col-md-6 col-sm-12 col-xs-12 tect-item">
                            <div>
                                <div class="col-md-5 col-sm-5 col-xs-5 item-name">Hướng:</div>
                                <div class="col-md-7 col-sm-7 col-xs-7 item-value"></div>
                            </div>
                        </li>
                        <li class="col-md-6 col-sm-12 col-xs-12 tect-item">
                            <div>
                                <div class="col-md-5 col-sm-5 col-xs-5 item-name">Pháp lý:</div>
                                <div class="col-md-7 col-sm-7 col-xs-7 item-value"></div>
                            </div>
                        </li>
                        <li class="col-md-6 col-sm-12 col-xs-12 tect-item" style="display:none">
                            <div>
                                <div class="col-md-5 col-sm-5 col-xs-5 item-name">Đường trước nhà:</div>
                                <div class="col-md-7 col-sm-7 col-xs-7 item-value"></div>
                            </div>
                        </li>
                        <li class="col-md-6 col-sm-12 col-xs-12 tect-item" style="display:none">
                            <div>
                                <div class="col-md-5 col-sm-5 col-xs-5 item-name">Chính chủ:</div>
                                <div class="col-md-7 col-sm-7 col-xs-7 item-value"><input type="checkbox" disabled="disabled"  /></div>
                            </div>
                        </li>
                        <li class="col-md-6 col-sm-12 col-xs-12 tect-item" style="display:none">
                            <div>
                                <div class="col-md-5 col-sm-5 col-xs-5 item-name">Thuộc dự án:</div>
                                <div class="col-md-7 col-sm-7 col-xs-7 item-value"></div>
                            </div>
                        </li>
                    </ul>
                    <div class="tect-title clearfix" style="margin-top: 15px;border-top: 1px solid #e5e5e5; padding-top:15px; display:none">Nội thất:</div>
                    <ul class="ct-safe-list clearfix" style="display:none">

                    </ul>
                    <div class="tect-title clearfix" style="margin-top: 15px;border-top: 1px solid #e5e5e5; padding-top:15px;  display:none">Các tiện nghi:</div>
                    <ul class="ct-safe-list clearfix" style="display:none">

                    </ul>
                </div>

                <div class="ct-social clearfix" id="dvEditClassified">
                    <div class="col-md-7 col-sm-7 col-xs-12 favorite" style="padding:0px">
                    <span><a data-gtm-event="mbn-event-all" data-gtm-category="mbn-detail" data-gtm-action="detail-cmd-favorite"
                             title="Bỏ thích/Thích" data-bind="click: AddOrRemoveFavorite"><i class="icon icon-common_star_favorite_bookmark_" style="font-size:18px;" data-bind="style:{color:IsFavorite()==false? '#23527c':'#eda703'}"></i><span data-bind="text:IsFavorite()?'Bỏ thích':'Thích'"></span></a></span>

                        <span><a data-gtm-event="mbn-event-link" data-gtm-category="mbn-detail" data-gtm-action="detail-cmd-feedback"
                                 title="Báo vi phạm" data-bind="click:ShowFeedBack"><i class="icon icon-exclamation3" style="font-size:18px;"></i>Báo vi phạm</a></span>
                        <span data-bind="click:PrintDetail, visible: ShowPrint" style="display:none">
                        <a data-gtm-event="mbn-event-link" data-gtm-category="mbn-detail" data-gtm-action="detail-cmd-print"
                           title="In tin"><i class="fa fa-print" style="font-size:18px;"></i>In nội dung tin</a>
                    </span>
                    </div>
                    <div class="col-md-5 col-sm-5 col-xs-12 social">

                        <span class="fb-like" data-layout="button" data-action="like" data-show-faces="true" data-share="true"></span>

                        <span>
                        <span class="g-plusone" data-size="medium" data-annotation="none"></span>
                    </span>

                        <span>
                        <a href="https://twitter.com/share" class="twitter-share-button">Tweet</a>
                    </span>


                    </div>
                </div>





            </div>

            <div class="dt-service">
                <div class="dt-service-ctl">
                    <div class="sv-link clearfix">
                        <button data-gtm-event="mbn-event-all" data-gtm-category="mbn-detail" data-gtm-action="detail-nav-search"
                                class="btn btn-default btn-result" data-bind="click: ListPage">
                            <span><i class="fa fa-angle-left"></i> Trở lại kết quả</span>
                        </button>

                        <button data-gtm-event="mbn-event-all" data-gtm-category="mbn-detail" data-gtm-action="detail-nav-next"
                                class="btn btn-default btn-next"  data-bind="click: NextPage">
                            <span><i class="fa fa-angle-right"></i>Tin sau</span>
                        </button>
                        <button data-gtm-event="mbn-event-all" data-gtm-category="mbn-detail" data-gtm-action="detail-nav-back"
                                class="btn btn-default btn-prev"  data-bind="click:PrePage">
                            <span><i class="fa fa-angle-left"></i>Tin trước</span>
                        </button>
                    </div>
                    <div class="sv-action clearfix">
                        <div data-gtm-event="mbn-event-all" data-gtm-category="mbn-detail" data-gtm-action="detail-buy-service"
                             class="sv-vip clearfix" data-bind="click: GotoSV">
                            <div class="icon-vip">
                            </div>
                            <div class="vip-description">
                                <span><i class="icon icon-buynow"></i></span>
                                <div class="note">
                                    Tin của bạn có nhiều người xem hơn
                                </div>
                            </div>
                            <div class="vip-arrow">
                                <i class="icon icon-arrow89"></i>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                    </div>
                </div>

                <div class="dt-service-ads">


                    <div class="mbn-box-ads">
                        <div class="mbn-title-header">
                            <span class="title-special">Tin quảng cáo</span>
                            <button id="mbn-classified-ads-next" data-gtm-event="mbn-event-all" data-gtm-category="mbn-listing-spright" data-gtm-action="listing-spright-posting-next" class="btn special-ctn-next">
                                <i class="icon icon-right218"></i>
                            </button>
                            <button id="mbn-classified-ads-prev" data-gtm-event="mbn-event-all" data-gtm-category="mbn-listing-spright" data-gtm-action="listing-spright-posting-back" class="btn special-ctn-next">
                                <i class="icon icon-left207"></i>
                            </button>

                            <span class="title-qc">
            <a data-gtm-event="mbn-event-link" data-gtm-category="mbn-listing-spright" data-gtm-action="listing-spright-help"
               href="https://muaban.net/uploads/huong-dan/bang_gia/tin-quang-cao/index.html"><i class="icon icon-QuestionMark"></i></a>
        </span>
                            <div class="clearfix"></div>
                        </div>
                        <div class="clearfix"></div>
                        <ul id="mbn-classified-ads" class="hidden-xs">
                            <li>
                                <a data-gtm-event="mbn-event-link" data-gtm-category="mbn-listing-spright" data-gtm-action="listing-spright-posting-id-39613009"
                                   title="Nhà hẻm Trần Bình Trọng phường 1 quận Gò Vấp" href="/nha-hem-ngo-quan-go-vap-l5920-c3202/nha-hem-tran-binh-trong-phuong-1-quan-go-vap-id39613009">
                                    <img class="spright-image" title="Nhà hẻm Trần Bình Trọng phường 1 quận Gò Vấp" alt="Nhà hẻm Trần Bình Trọng phường 1 quận Gò Vấp"  data-original="https://cdn.muaban.net/cdn/images/thumb-list/201707/24/117/d64a2c3df5014f879742fcf0518633e9.jpg" src="/content/images/1x1.gif" width="100" height="75" />
                                    <div class="spright-content">
                                        <h2>Nhà hẻm Trần Bình Trọng phường 1 quận Gò Vấp</h2>
                                        <span class="spright-price">2 tỷ 800 triệu</span>
                                    </div>
                                </a>
                            </li>
                        </ul>
                        <div id="owl-carousel-ads" class="owl-carousel visible-xs"></div>
                        <div class="clearfix"></div>
                    </div>


                    <div class="visible-lg">
                        <div class="sv-title">
                            <a href="/thong-tin/gioi-thieu-c4/an-toan-khi-giao-dich-id35" data-gtm-event="mbn-event-link" data-gtm-category="mbn-detail" data-gtm-action="detail-help-tips">Hướng dẫn giao dịch an toàn</a>
                        </div>
                        <div class="sv-sale-key">
                            <ul class="key-list">
                                <li>Không thanh toán tiền trước khi nhận hàng</li>
                                <li>Kiểm tra hàng cẩn thận trước khi mua</li>
                                <li>Giao dịch ở nơi công cộng</li>
                            </ul>
                        </div>
                    </div>

                    <div id="ads-google-right" class="hidden-xs">
                        <div class="mbn-ads-google-title"><span>Quảng cáo</span></div>
                        <!-- MBNV3 Detail Right -->
                        <ins class="adsbygoogle"
                             style="display:block"
                             data-ad-client="ca-pub-9257019901916343"
                             data-ad-slot="1987947915"
                             data-ad-format="auto"></ins>
                        <!-- MBNV3 - Detail Right -->
                        <ins class="adsbygoogle"
                             style="display:inline-block;width:300px;height:250px;margin-top:3px;"
                             data-ad-client="ca-pub-9257019901916343"
                             data-ad-slot="5882035518"></ins>
                    </div>
                </div>
            </div>

            <div class="dt-content col-sm-12 col-xs-12">
                <!--Classified Similar-->

                <div class="mbn-list-similar">
                    <h4 class="title">
                        <span>Tin rao vặt tương tự</span>
                    </h4>
                    <div class="mbn-box-list-content">
                        <a class="mbn-image" title="Bán nhanh rẻ nhà mặt tiền đường Số 3, P9, 4x18m đúc 1 lầu mới đẹp cao" href="https://muaban.net/nha-mat-tien-quan-go-vap-l5920-c3201/ban-nhanh-re-nha-mat-tien-duong-so-3-p9-4x18m-duc-1-lau-moi-dep-cao-id39688708">
                            <img title="Bán nhanh rẻ nhà mặt tiền đường Số 3, P9, 4x18m đúc 1 lầu mới đẹp cao" alt="Bán nhanh rẻ nhà mặt tiền đường Số 3, P9, 4x18m đúc 1 lầu mới đẹp cao"  data-original="https://cdn01.muaban.net/mogi/thumb-list/201707/27/617/eb1d61373a9d443ba9dad247469c1e3a.jpg" src="/content/images/1x1.gif" width="120" height="90" />
                        </a>
                        <a title="Bán nhanh rẻ nhà mặt tiền đường Số 3, P9, 4x18m đúc 1 lầu mới đẹp cao" href="https://muaban.net/nha-mat-tien-quan-go-vap-l5920-c3201/ban-nhanh-re-nha-mat-tien-duong-so-3-p9-4x18m-duc-1-lau-moi-dep-cao-id39688708" data-gtm-event=mbn-event-link data-gtm-category=mbn-detail data-gtm-action=detail-similar>
                            <div class="mbn-content">
                                <h2 class="mbn-title">Bán nhanh rẻ nhà mặt tiền đường Số 3, P9, 4x18m đúc 1 lầu mới đẹp cao</h2>
                                <span class="mbn-price">3 tỷ 945 triệu</span>
                                <span class="mbn-address"><span class="icon icon-map5"></span> Quận Gò Vấp, TP.HCM</span>
                                <span class="mbn-date">27/07/2017</span>

                                <span class="mbn-item-area">Diện tích: <b>68,00 m<sup>2</sup></b></span>


                            </div>
                        </a>
                    </div>
                    <div class="mbn-box-list-content">
                        <a class="mbn-image" title="Nhà Chính Chủ- Hot Nhất Gò Vấp" href="https://muaban.net/nha-mat-tien-quan-go-vap-l5920-c3201/nha-chinh-chu-hot-nhat-go-vap-id39680894">
                            <img title="Nhà Chính Chủ- Hot Nhất Gò Vấp" alt="Nhà Chính Chủ- Hot Nhất Gò Vấp"  data-original="https://cdn.muaban.net/cdn/images/thumb-list/201707/27/154/fd6daef713434a88a2336de05c03b66b.jpg" src="/content/images/1x1.gif" width="120" height="90" />
                        </a>
                        <a title="Nhà Chính Chủ- Hot Nhất Gò Vấp" href="https://muaban.net/nha-mat-tien-quan-go-vap-l5920-c3201/nha-chinh-chu-hot-nhat-go-vap-id39680894" data-gtm-event=mbn-event-link data-gtm-category=mbn-detail data-gtm-action=detail-similar>
                            <div class="mbn-content">
                                <h2 class="mbn-title">Nhà Chính Chủ- Hot Nhất Gò Vấp</h2>
                                <span class="mbn-price">3 tỷ 900 triệu</span>
                                <span class="mbn-address"><span class="icon icon-map5"></span> Quận Gò Vấp, TP.HCM</span>
                                <span class="mbn-date">27/07/2017</span>

                                <span class="mbn-item-area">Diện tích: <b>60,00 m<sup>2</sup></b></span>


                            </div>
                        </a>
                    </div>
                    <div class="mbn-box-list-content">
                        <a class="mbn-image" title="Nhà bán mặt tiền Nguyễn Duy Cung, phường 12, quận Gò Vấp" href="https://muaban.net/nha-mat-tien-quan-go-vap-l5920-c3201/nha-ban-mat-tien-nguyen-duy-cung-phuong-12-quan-go-vap-id39473067">
                            <img title="Nhà bán mặt tiền Nguyễn Duy Cung, phường 12, quận Gò Vấp" alt="Nhà bán mặt tiền Nguyễn Duy Cung, phường 12, quận Gò Vấp"  data-original="https://cdn.muaban.net/cdn/images/thumb-list/201707/16/007/4390716b00b44ebf9ade57c0659675f8.jpg" src="/content/images/1x1.gif" width="120" height="90" />
                        </a>
                        <a title="Nhà bán mặt tiền Nguyễn Duy Cung, phường 12, quận Gò Vấp" href="https://muaban.net/nha-mat-tien-quan-go-vap-l5920-c3201/nha-ban-mat-tien-nguyen-duy-cung-phuong-12-quan-go-vap-id39473067" data-gtm-event=mbn-event-link data-gtm-category=mbn-detail data-gtm-action=detail-similar>
                            <div class="mbn-content">
                                <h2 class="mbn-title">Nhà bán mặt tiền Nguyễn Duy Cung, phường 12, quận Gò Vấp</h2>
                                <span class="mbn-price">4 tỷ 100 triệu</span>
                                <span class="mbn-address"><span class="icon icon-map5"></span> Quận Gò Vấp, TP.HCM</span>
                                <span class="mbn-date">27/07/2017</span>

                                <span class="mbn-item-area">Diện tích: <b>86,00 m<sup>2</sup></b></span>


                            </div>
                        </a>
                    </div>
                    <div class="mbn-box-list-content">
                        <a class="mbn-image" title="Bán nhà mặt tiền Dương Quảng Hàm, Quận Gò Vấp, 46m2 nở hậu" href="https://muaban.net/nha-mat-tien-quan-go-vap-l5920-c3201/ban-nha-mat-tien-duong-quang-ham-quan-go-vap-46m2-no-hau-id37995860">
                            <img title="Bán nhà mặt tiền Dương Quảng Hàm, Quận Gò Vấp, 46m2 nở hậu" alt="Bán nhà mặt tiền Dương Quảng Hàm, Quận Gò Vấp, 46m2 nở hậu"  data-original="https://cdn01.muaban.net/images/thumb-list/201704/26/122/fdfce1e5e3634bd0bf9d0d15eec06eed.jpg" src="/content/images/1x1.gif" width="120" height="90" />
                        </a>
                        <a title="Bán nhà mặt tiền Dương Quảng Hàm, Quận Gò Vấp, 46m2 nở hậu" href="https://muaban.net/nha-mat-tien-quan-go-vap-l5920-c3201/ban-nha-mat-tien-duong-quang-ham-quan-go-vap-46m2-no-hau-id37995860" data-gtm-event=mbn-event-link data-gtm-category=mbn-detail data-gtm-action=detail-similar>
                            <div class="mbn-content">
                                <h2 class="mbn-title">Bán nhà mặt tiền Dương Quảng Hàm, Quận Gò Vấp, 46m2 nở hậu</h2>
                                <span class="mbn-price">3 tỷ 800 triệu</span>
                                <span class="mbn-address"><span class="icon icon-map5"></span> Quận Gò Vấp, TP.HCM</span>
                                <span class="mbn-date">27/07/2017</span>



                            </div>
                        </a>
                    </div>
                    <div class="mbn-box-list-content">
                        <a class="mbn-image" title="Bán nhà 455/5 Phan Huy Ích, Gò Vấp, sát ngã tư Quang Trung, 4x13,5" href="https://muaban.net/nha-mat-tien-quan-go-vap-l5920-c3201/ban-nha-455-5-phan-huy-ich-go-vap-sat-nga-tu-quang-trung-4x13-5-id39363669">
                            <img title="Bán nhà 455/5 Phan Huy Ích, Gò Vấp, sát ngã tư Quang Trung, 4x13,5" alt="Bán nhà 455/5 Phan Huy Ích, Gò Vấp, sát ngã tư Quang Trung, 4x13,5"  data-original="https://cdn.muaban.net/cdn/images/thumb-list/201707/10/306/1d78631a89644607b40223a54193e86b.jpg" src="/content/images/1x1.gif" width="120" height="90" />
                        </a>
                        <a title="Bán nhà 455/5 Phan Huy Ích, Gò Vấp, sát ngã tư Quang Trung, 4x13,5" href="https://muaban.net/nha-mat-tien-quan-go-vap-l5920-c3201/ban-nha-455-5-phan-huy-ich-go-vap-sat-nga-tu-quang-trung-4x13-5-id39363669" data-gtm-event=mbn-event-link data-gtm-category=mbn-detail data-gtm-action=detail-similar>
                            <div class="mbn-content">
                                <h2 class="mbn-title">Bán nhà 455/5 Phan Huy Ích, Gò Vấp, sát ngã tư Quang Trung, 4x13,5</h2>
                                <span class="mbn-price">3 tỷ 800 triệu</span>
                                <span class="mbn-address"><span class="icon icon-map5"></span> Quận Gò Vấp, TP.HCM</span>
                                <span class="mbn-date">27/07/2017</span>

                                <span class="mbn-item-area">Diện tích: <b>54,00 m<sup>2</sup></b></span>


                            </div>
                        </a>
                    </div>
                </div>
                <div class="borderTop"></div>
            </div>

        </div>
        <div class="cl-detail clearfix">
            <div id="ads-google-bottom" class="ads-banner-botom hidden-xs">
                <div class="mbn-ads-google-title"><span>Quảng cáo</span></div>
                <!-- MBNV3 Bottom Detail -->
                <ins class="adsbygoogle"
                     style="display:inline-block;width:728px;height:90px"
                     data-ad-client="ca-pub-9257019901916343"
                     data-ad-slot="6418147512"></ins>
                <div class="clearfix"></div>
            </div>
            <div id="ads-google-bottom-mobile" class="visible-xs">
                <!-- MBNV3 - Mobile Detail -->
                <ins class="adsbygoogle"
                     style="display:inline-block;width:300px;height:250px"
                     data-ad-client="ca-pub-9257019901916343"
                     data-ad-slot="4831046713"></ins>
            </div>
        </div>
        <div data-bind="with:ViewedItem">

            <div class="mbn-home home-viewed visible-lg clearfix" style="margin-top:30px; ">

                <div class="mbn-ctl-box">
                    <h2 class="title"><span>Tin đã xem</span></h2>
                </div>

                <div class="home-viewed-content clearfix">
                    <ul class="home-viewed-list clearfix" id="home-viewed-list">
                        <li>
                            <a data-gtm-event="mbn-event-link" data-gtm-category="mbn-detail" data-gtm-action="home-favorite-posting-click" title="Nhà bán Gò Vấp, đúc 4 tấm, 4x17m hẻm 5m Bùi Quang Là Giá 3.8 tỷ" href="https://muaban.net/nha-mat-tien-quan-go-vap-l5920-c3201/nha-ban-go-vap-duc-4-tam-4x17m-hem-5m-bui-quang-la-gia-3-8-ty-id39625058">
                            <span class="viewed-item clearfix">
                                <span class="viewed-item-img">
                                        <img title="Nhà bán Gò Vấp, đúc 4 tấm, 4x17m hẻm 5m Bùi Quang Là Giá 3.8 tỷ" alt="Nhà bán Gò Vấp, đúc 4 tấm, 4x17m hẻm 5m Bùi Quang Là Giá 3.8 tỷ"  data-original="https://cdn.muaban.net/cdn/images/thumb-list/201707/24/145/1f43a901bf3147db868c84f2249950f1.jpg" src="/content/images/1x1.gif" width="120" height="90" />
                                </span>
                                <span class="viewed-item-body">Nhà bán Gò Vấp, đúc 4 tấm, 4x17m hẻm 5m Bùi Quang Là Giá 3.8 tỷ</span>
                                <span class="viewed-item-price">3 tỷ 800 triệu</span>
                            </span>
                            </a>
                        </li>

                    </ul>
                    <!--Next Page-->
                    <ul class="home-viewed-list clearfix" data-bind="visible:ViewedItems().length>0">
                        <!--ko foreach:{data: ViewedItems, as: 'item'} -->
                        <li>
                            <a data-gtm-event="mbn-event-link" data-gtm-category="mbn-detail" data-gtm-action="home-favorite-posting-click" data-bind="attr: {href: item.DetailUrl, title: item.Subject }">
                    <span class="viewed-item clearfix">
                        <span class="viewed-item-img">
                            <!-- ko if: (item.ThumbUrl() != '') -->
                            <img data-bind="attr:{src: item.ThumbUrl, alt: item.Subject, title: item.Subject}" width="120" height="90" alt="" src="/Content/images/blank.png" />
                            <!--/ko-->
                        </span>
                        <span class="viewed-item-body" data-bind="text: item.Subject"></span>
                        <span class="viewed-item-price" data-bind="text: item.PriceDisplay"></span>
                    </span>
                            </a>
                        </li>
                        <!--/ko-->
                    </ul>
                </div>
            </div>


        </div>
        <div class="cl-detail-posting visible-sm visible-xs clearfix ">
            <span data-bind="click:GotoPosting" class="btn-primary"><i class="icon icon-pencil84"></i> ĐĂNG TIN RAO VẶT MIỄN PHÍ</span>
        </div>
    </div>


    <div class="container bottom-cat-listing visible-lg clearfix">
        <div class="clearfix hidden-sm hidden-xs">
            <div class="container float-left">
                <h2 class="title">
                    <span>Tin rao vặt  - TP.HCM</span>
                </h2>
            </div>
            <div class="container cat-item">
                <a  data-gtm-event="mbn-event-link" data-gtm-category="mbn-listing" data-gtm-action="home-bottom-category-l59-c3" href="https://muaban.net/mua-ban-nha-dat-cho-thue-ho-chi-minh-l59-c3"><i class="icon icon-cat-3"></i><span>Bất động sản</span></a>
                <a  data-gtm-event="mbn-event-link" data-gtm-category="mbn-listing" data-gtm-action="home-bottom-category-l59-c6" href="https://muaban.net/do-dien-tu-ho-chi-minh-l59-c6"><i class="icon icon-cat-6"></i><span>Đồ điện tử</span></a>
                <a  data-gtm-event="mbn-event-link" data-gtm-category="mbn-listing" data-gtm-action="home-bottom-category-l59-c1" href="https://muaban.net/viec-lam-tuyen-sinh-ho-chi-minh-l59-c1"><i class="icon icon-cat-1"></i><span>Việc làm, Tuyển sinh</span></a>
                <a  data-gtm-event="mbn-event-link" data-gtm-category="mbn-listing" data-gtm-action="home-bottom-category-l59-c9" href="https://muaban.net/dich-vu-ho-chi-minh-l59-c9"><i class="icon icon-cat-9"></i><span>Dịch vụ</span></a>
                <a  data-gtm-event="mbn-event-link" data-gtm-category="mbn-listing" data-gtm-action="home-bottom-category-l59-c4" href="https://muaban.net/o-to-ho-chi-minh-l59-c4"><i class="icon icon-cat-4"></i><span>Ô tô</span></a>
                <a  data-gtm-event="mbn-event-link" data-gtm-category="mbn-listing" data-gtm-action="home-bottom-category-l59-c7" href="https://muaban.net/dien-may-do-gia-dung-ho-chi-minh-l59-c7"><i class="icon icon-cat-7"></i><span>Điện máy, Đồ gia dụng</span></a>
                <a  data-gtm-event="mbn-event-link" data-gtm-category="mbn-listing" data-gtm-action="home-bottom-category-l59-c5" href="https://muaban.net/xe-may-ho-chi-minh-l59-c5"><i class="icon icon-cat-5"></i><span>Xe máy</span></a>
                <a  data-gtm-event="mbn-event-link" data-gtm-category="mbn-listing" data-gtm-action="home-bottom-category-l59-c2" href="https://muaban.net/thoi-trang-my-pham-ho-chi-minh-l59-c2"><i class="icon icon-cat-2"></i><span>Thời trang, Mỹ phẩm</span></a>
                <a  data-gtm-event="mbn-event-link" data-gtm-category="mbn-listing" data-gtm-action="home-bottom-category-l59-c8" href="https://muaban.net/so-thich-mat-hang-khac-ho-chi-minh-l59-c8"><i class="icon icon-cat-8"></i><span>Sở thích, Mặt hàng khác</span></a>
                <a  data-gtm-event="mbn-event-link" data-gtm-category="mbn-listing" data-gtm-action="home-bottom-category-l59-cA" href="https://muaban.net/doi-tac-cong-dong-ho-chi-minh-l59-ca"><i class="icon icon-cat-A"></i><span>Đối tác, Cộng đồng</span></a>
            </div>

        </div>
    </div>






    <div class="mbn-list">
        <div class="mbn-title-link hidden-xs">
            <div class="container">


                <div class="mbn-box-sub-last-link visible-lg">

                    <h2 class="title">
                        <span>Bất động sản Quận Gò Vấp</span>
                    </h2>
                    <div class="mbn-box-sub-list-link ">
                        <ul class="nav mbn-list-nav col4">

                            <li>
                                <a data-gtm-event="mbn-event-link" data-gtm-category="mbn-listing" data-gtm-action="listing-category-l5920-c31"
                                   href="https://muaban.net/ban-dat-quan-go-vap-l5920-c31" title="Bán đất" ><h2>Bán đất</h2></a>
                            </li>


                            <li>
                                <a data-gtm-event="mbn-event-link" data-gtm-category="mbn-listing" data-gtm-action="listing-category-l5920-c32"
                                   href="https://muaban.net/ban-nha-can-ho-quan-go-vap-l5920-c32" title="Bán nhà, Căn hộ" ><h2>Bán nhà, Căn hộ</h2></a>
                            </li>


                            <li>
                                <a data-gtm-event="mbn-event-link" data-gtm-category="mbn-listing" data-gtm-action="listing-category-l5920-c33"
                                   href="https://muaban.net/sang-nhuong-cua-hang-quan-go-vap-l5920-c33" title="Sang nhượng cửa hàng" ><h2>Sang nhượng cửa hàng</h2></a>
                            </li>


                            <li>
                                <a data-gtm-event="mbn-event-link" data-gtm-category="mbn-listing" data-gtm-action="listing-category-l5920-c34"
                                   href="https://muaban.net/cho-thue-nha-dat-quan-go-vap-l5920-c34" title="Cho thuê nhà đất" ><h2>Cho thuê nhà đất</h2></a>
                            </li>


                            <li>
                                <a data-gtm-event="mbn-event-link" data-gtm-category="mbn-listing" data-gtm-action="listing-category-l5920-c35"
                                   href="https://muaban.net/can-mua-nha-dat-quan-go-vap-l5920-c35" title="Cần mua nhà đất" ><h2>Cần mua nhà đất</h2></a>
                            </li>


                            <li>
                                <a data-gtm-event="mbn-event-link" data-gtm-category="mbn-listing" data-gtm-action="listing-category-l5920-c36"
                                   href="https://muaban.net/can-thue-nha-dat-quan-go-vap-l5920-c36" title="Cần thuê nhà đất" ><h2>Cần thuê nhà đất</h2></a>
                            </li>


                            <li>
                                <a data-gtm-event="mbn-event-link" data-gtm-category="mbn-listing" data-gtm-action="listing-category-l5920-c37"
                                   href="https://muaban.net/dich-vu-nha-dat-quan-go-vap-l5920-c37" title="Dịch vụ nhà đất" ><h2>Dịch vụ nhà đất</h2></a>
                            </li>


                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="clearfix"></div>
                </div>


            </div>
        </div>
    </div>

    <div class="modal fade" id="modalFeedback" data-bind="with:FeedBack">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Tôi muốn báo vi phạm</h4>
                </div>
                <div class="modal-body">
                    <form class="form-horizontal" role="form" id="frmFeedBack">
                        <div class="form-group">
                            <!-- ko foreach:{data: FeedBackMessage, as: 'item'} -->
                            <div class="col-md-12 col-ms-12 col-xm-12">
                                <label style="width:100%; font-weight:normal">
                                    <input type="checkbox" data-bind="checked: item.Selected">
                                    <span data-bind="text: item.Name"></span>
                                </label>
                            </div>
                            <!-- /ko -->
                            <input type="hidden" data-bind="value:MessageId" />
                            <div class="col-md-12 col-ms-12 col-xm-12">
                                <p data-bind="validationMessage: MessageId" class="validationMessage"></p>
                            </div>
                        </div>
                        <hr />
                        <div class="form-group">
                            <div class="col-md-12 col-xs-12 col-sm-12">
                                <div class="row">
                                    <label for="txtContactName" class="col-md-4">
                                        Tôi tên là
                                    </label>
                                    <div class="col-md-8">
                                        <input class="form-control" data-bind="value: ContactName" placeholder="Nhập tên của bạn" type="text" id="txtContactName">
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-12 col-ms-12 col-xm-12">
                                <p data-bind="validationMessage: ContactName" class="validationMessage"></p>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-12 col-xs-12 col-sm-12">
                                <div class="row">
                                    <label for="txtContactName" class="col-md-4">
                                        Email hoặc Điện thoại
                                    </label>
                                    <div class="col-md-8">
                                        <input class="form-control" data-bind="value: ContactInfo" placeholder="Nhập Email hoặc Điện thoại của bạn" type="text" id="txtContactInfo">
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-12 col-ms-12 col-xm-12">
                                <p data-bind="validationMessage: ContactInfo" class="validationMessage"></p>
                            </div>
                        </div>
                        <div class="form-group" data-bind="visible: ShowCaptcha">
                            <div class="col-md-12 col-sm-12 col-xm-12">
                                Mã bảo mật:
                            </div>
                            <div class="col-md-12 col-sm-12 col-xm-12"><div style="vertical-align:middle;">
                                    <input type="text" class="form-control" style="width:120px; float:left;" id="ConfirmCaptcha" name="ConfirmCaptcha" data-bind="value: ConfirmCaptcha" autocomplete="off" placeholder="Mã an toàn" maxlength="5" />
                                    <div style="display:inline-block;width:160px;padding-left:10px;">
                                        <input type="hidden" id="Captcha" name="Captcha" value="d4ae57d2-7491-4a4f-87c3-90cdd9d91c96" />
                                        <img id="ImgCaptcha" src="/captcha.ashx?guid=d4ae57d2-7491-4a4f-87c3-90cdd9d91c96" alt="Captcha" width="100" height="30" /> <button type="button" class="btn btn-default" data-bind="click: RefreshCaptcha" title="Làm mới mã an toàn"><i class="fa fa-refresh"></i></button>
                                    </div>
                                    <div class="clearfix"></div>
                                    <div>
                                        <p data-bind="validationMessage: ConfirmCaptcha" class="validationMessage"></p>

                                    </div>
                                </div>


                            </div>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Đóng</button>
                    <button type="button" class="btn btn-primary" data-bind="click: SendFeedBack">Gửi</button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->

</div>