<?php 
//require_once TEMPLATE_PATH . DS . 'home' . DS . 'inc' . DS . 'left.php';
//require_once TEMPLATE_PATH . DS . 'home' . DS . 'inc' . DS . 'right.php';
?>
<div class="ct-in-l">
	<?php require_once TEMPLATE_PATH . DS . 'home' . DS . 'box' . DS . 'breadcrumb.php';?>
	<div class="dv-ct-detail">
		<h2>Mua bán nhà đất, cho thuê nhà đất, thông tin nhà đất, bất động sản</h2>
	</div>
    <?php require_once TEMPLATE_PATH . DS . 'home' . DS . 'inc' . DS . 'content-adv-top.php';?>	
	<?php require_once TEMPLATE_PATH . DS . 'home' . DS . 'inc' . DS . 'content-vip.php';?>	
	<?php require_once TEMPLATE_PATH . DS . 'home' . DS . 'box' . DS . 'content-lease.php';?>
	<?php require_once TEMPLATE_PATH . DS . 'home' . DS . 'inc' . DS . 'content-adv-bottom.php';?>
	
</div>
<div class="ct-in-r">
    <?php require_once TEMPLATE_PATH . DS . 'home' . DS . 'inc' . DS . 'sidebar-search.php';?>	
    <?php require_once TEMPLATE_PATH . DS . 'home' . DS . 'inc' . DS . 'sidebar-hotline.php';?>	
    <?php require_once TEMPLATE_PATH . DS . 'home' . DS . 'inc' . DS . 'sidebar-adv1.php';?>	
	<?php require_once TEMPLATE_PATH . DS . 'home' . DS . 'inc' . DS . 'sidebar-pro.php';?>
	<?php //require_once TEMPLATE_PATH . DS . 'home' . DS . 'inc' . DS . 'sidebar-price.php';?>
	<?php require_once TEMPLATE_PATH . DS . 'home' . DS . 'inc' . DS . 'sidebar-type.php';?>
	<?php require_once TEMPLATE_PATH . DS . 'home' . DS . 'inc' . DS . 'sidebar-project.php';?>
	<?php require_once TEMPLATE_PATH . DS . 'home' . DS . 'inc' . DS . 'sidebar-adv1.php';?>	
	<?php require_once TEMPLATE_PATH . DS . 'home' . DS . 'inc' . DS . 'sidebar-news.php';?>
</div>


<div class="debug">
    <?php var_dump($this->arrParam)?>
</div>
