<?php

//Doanh nghiệp thành phố lớn
$xhtmlCity          = '';
if(!empty($this->listCity)){
    foreach($this->listCity as $item){
        $urlCity    = $this->url(
            'CityBusinessRoute',
            array(
                'action'=>'category',
                'cityname'=>\ZendVN\Url\FriendlyLink::filter($item['name']),
                'page'=>1,
                'id'=>$item['id']
        ));
        $xhtmlCity      .= '<li>  <a href="'.$urlCity.'" title="'.$item['name'].'">'.$item['name'].' <span></span>  </a></li>';
    }  
}

//Doanh nghiệp nổi bật
$itemBusinessHighlight = '';
if(!empty($this->itemBusinessHighlight)){
    foreach($this->itemBusinessHighlight as $item){
        $linkIntro      = $this->url('IntroBusinessRoute',array('action'=>'detail','alias'=>$item['alias']));
        
        $logo           = (!empty($item['logo']))  ? UPLOAD_URL .'/logo-business/'.$item['logo'] :  TEMPLATE_URL .'/admin/images/NoImage.jpg';
        
        $itemBusinessHighlight      .= '<li><a href="'.$linkIntro.'" title="'.$item['name'].'"><img src="'.$logo.'" width="113" alt="'.$item['name'].'" title="'.$item['name'].'"></a><h3><a href="'.$linkIntro.'" title="'.$item['name'].'">'.\ZendVN\Filter\ReadMore::create($item['name'],0,30).'</a></h3></li>';
    }  
}

$linkLoadDistrict    = $this->url('MVC_HomeRouter/action',array(
    'module'=>'home',
    'controller'=>'business',
    'action'=>'load-select-district'
));

//Search Name
$linkSearch         = $this->url('MVC_HomeRouter/action',array('controller'=>'business','action'=>'search'));

?>
<div class="pageWrap">
<?php echo $this->cmsBreadcrumb($this->title,array('task'=>'no-data')) .' '.$this->blkAccountGroup($this->identity());?>
</div>
<div class="pageWrap">
	<div class="leftMainContent">
        <?php echo $this->formSearchBusiness;?>
         <script type="text/javascript">

        $(document).ready(function(){

             //Load quận huyện
            $("#city").change(function(){
                var city = $("#city option:selected").val();
                
                loadDistrict(city);
            });

           $("#search-business-form #search-submit-business").click(function(){
                var q           = $("#txtTenDN").val();
                var type        = $("#type option:selected").val();
                var city        = $("#city option:selected").val();
                var district    = $("#district option:selected").val();

                var linkSearchProject = '<?php echo $linkSearch;?>?q='+ q + '&type=' + type + '&city=' + city + '&district=' + district + '&page=1';

                //Tìm kiếm tất cả thông tin
                if(q != '' || type != '' || city != ''  || district != ''){
                    window.location = linkSearchProject;
                }else if(q == '' && type == '' && city == ''  && district == ''){
                     alert("Bạn phải nhập từ khóa, hoặc chọn các tiêu chí");
                }
                
            });

            
        });

         function loadDistrict(city){
            $.ajax({
                url     : '<?php echo $linkLoadDistrict;?>',
                type    : 'GET',
                data    : {city : city},
                success: function(data){
                    $("#district").html(data);
                },
                complete: function(){

                }
            });
        }

        </script>
        <div class="vipObject company">
            <h2 class="leftTitle"><b>Doanh nghiệp nổi bật</b></h2>
            <div class="leftSmallContent">
                <div id="nodegalleryDa" style="left:0;"><ul style="width: 1197px; position: relative; left: -283.0664157292731px;">
                    <?php echo $itemBusinessHighlight;?>

                </ul><a onclick="SlideCaroulse(&quot;l&quot;);" href="javascript:" class="previousButton grey" title="Previous"></a><a onclick="SlideCaroulse(&quot;r&quot;);" href="javascript:" class="nextButton grey" title="Next"></a></div>
                
            </div>
        </div>
         <script type="text/javascript">
             self.setInterval("SlideCaroulse('l')", 3000);
             var previousB = 5;
             var noOfSlide = 5;
             var selectedUl = 'div#nodegalleryDa ul';
             var ulWidth = $(selectedUl).width();
             var liWidth = 133;
             
             
        </script>

            		
        <div class="companyList">
            <h2 class="leftTitle"><b>Danh sách các doanh nghiệp</b></h2>
            <div class="leftSmallContent">
                <ul class="leftListing2">
                   <?php echo $this->xhtmlBusiness;?>
                </ul>
            </div>
        </div>

		<div class="companyProvince">
          <h2 class="leftTitle"><b>Doanh nghiệp BĐS ở các tỉnh/thành</b></h2>
        		
        	<div class="leftSmallContent">		
        		<ul class="leftLine">
        			<?php echo $xhtmlCity;?>
        		</ul>
        		<div class="clr_both"></div>
        	</div>
        </div>

	</div>


	<div class="rightMainContent">
  <?php echo $this->blkAdsColumnRight();?>     


  <script type="text/javascript">
      function DisplayMe(div) {
          document.getElementById(div).style.display = '';
      }

      $('#txtEmailNL').click(function (event) {$('html').one('click', function () {$("#infoDiv").hide();});event.stopPropagation();});$('#txtFullName').click(function (event) {$('html').one('click', function () {$("#infoDiv").hide();});event.stopPropagation();});
  </script>



 

    <script type="text/javascript">
        $("#divTopAgent .padded .infoGroup img").error(function (event) {
            $(this).attr("src", "http://images.videonhadat.com.vn/avatar_male_84x94.gif");
        })
    </script> 
      
  <?php echo $this->blkRegisterEmail();?> 
  <?php echo $this->blkNhanXet();?> 
  <?php echo $this->blkLienKet();?> 
  </div>

</div>