
<?php
$isXmlHttpRequest = $this->isXmlHttpRequest;
if($isXmlHttpRequest == true){
$xhtml = '';
if(!empty($this->items)){
    foreach($this->items as $item){
       

        $id         = $item['id'];
        $name       = $item['name'];
        $address    = $item['name_district'] . ' - '.$item['name_city'];
        $phone      = $item['phone'];
        $fax        = $item['fax'];            
        $logo           = (!empty($item['logo']))  ? UPLOAD_URL .'/logo-business/'.$item['logo'] :  TEMPLATE_URL .'/admin/images/NoImage.jpg';
        $intro      = $item['intro'];
        $website    = $item['website'];
        $alias      = $item['alias'];
        $linkIntro  = $this->url('IntroBusinessRoute',array('action'=>'detail','alias'=>$alias));

        $xhtml .= '<li>
                    <div class="content">
                        <div class="infoGroup" onmouseover="javascript:$(\'#div_enb0000027\').show();" onmouseout="javascript:$(\'#div_enb0000027\').hide();">
                                <a href="'.$linkIntro.'" title="'.$name.'" class="avatar">
                                <img src="'.$logo.'" width="95" alt="'.$name.'" title="'.$name.'">
                                </a>
                                <div class="text">
                                <h3>
                                  <a href="'.$linkIntro.'" title="'.$name.'">'.$name.'</a>
                                  <span>'.$address.'</span>
                                  <span>ĐT: '.$phone.' &nbsp;&nbsp;|&nbsp;&nbsp; Fax: '.$fax.'</span>
                                </h3>
                                <p>
                                 '.\ZendVN\Filter\ReadMore::create($intro,0,300).'<a href="'.$website.'" title="'.$website.'">'.$website.'</a>
                                </p>
                                </div>
                        </div>

                        
                    </div>
                </li>
                    ';
                             
    }
}

?>



 <div id="MainContent_Business_SearchResult1_divAllContent" class="companyList">
    <h2 class="leftTitle">
        <span id="MainContent_Business_SearchResult1_Label1"><?php echo $this->totalItem;?> </span>
        <span id="MainContent_Business_SearchResult1_Label2">Doanh nghiệp</span></h2>
    
    <div class="leftSmallContent">
        <div id="MainContent_Business_SearchResult1_dnCondition" class="messageBox1 companyKey">
        <p>Thành phố: <?php echo $this->itemCity['name'];?></p>
         </div>
        <div id="MainContent_Business_SearchResult1_divAgl"><input id="hCurrentPage" type="hidden" value="1"><input id="hTotalRows" type="hidden" value="71">

            <ul class="leftListing2">

            <?php echo $xhtml;?>

            </ul>

    <?php
    
     
    $paramsUrl  = array(
        'module'        => 'home',
        'controller'    => 'business',
        'action'        => 'city',
        'cityname'      =>  $this->arrParam['cityname'],
        'page'          => '1',
        'cityid'        => $this->arrParam['cityid'],
        'extension'     => 'html',
    );
    echo $this->paginationControl($this->paginator , 'sliding' , 'home/business/paginator.phtml', array(
        'router'    => 'CityBusinessRoute',
        'arrParam'  =>$paramsUrl,
    )); 
  
 ?>



        
</div>

</div>








<?php
}else{
    echo 'not ajax';
}
?>
