<?php
$name               = $this->item['name'];
$address            = $this->item['address'] .' - '.$this->item['name_ward'] . ' - '.$this->item['name_district'] . ' - '.$this->item['name_city'];

$phone              = $this->item['phone'];
$fax                = (!empty($this->item['fax'])) ? $this->item['fax'] : 'Updating...';
$website            = (!empty($this->item['website'])) ? $this->item['website'] : '#Updating';
$logo               = (!empty($item['logo']))  ? UPLOAD_URL .'/logo-business/'.$item['logo'] :  TEMPLATE_URL .'/admin/images/NoImage.jpg';

$intro              = $this->item['intro'];

$contact            = $this->item['contact'];

$linkIntroBusiness          = $this->url('IntroBusinessRoute',array('action'=>'detail','alias'=>$this->arrParam['alias']));

$linkContact        = $this->url('ContactBusinessRoute',array('action'=>'contact','alias'=>$this->arrParam['alias']));
$linkDepartment     = $this->url('DepartmentBusinessRoute',array('action'=>'department','alias'=>$this->arrParam['alias']));

$linkLandSale       = $this->url('LandSaleBusinessRoute',array('action'=>'landsale','alias'=>$this->arrParam['alias']));

$linkLandForRent    = $this->url('LandForRentBusinessRoute',array('action'=>'landforrent','alias'=>$this->arrParam['alias']));

$linkInvestors      = $this->url('investorsBusinessRoute',array('action'=>'investors','alias'=>$this->arrParam['alias']));

$linkConstruction   = $this->url('constructionBusinessRoute',array('action'=>'construction','alias'=>$this->arrParam['alias']));

$linkManagement     = $this->url('managementBusinessRoute',array('action'=>'management','alias'=>$this->arrParam['alias']));

$linkDesign         = $this->url('designBusinessRoute',array('action'=>'design','alias'=>$this->arrParam['alias']));

$linkDistributors   = $this->url('distributorsBusinessRoute',array('action'=>'distributors','alias'=>$this->arrParam['alias']));
?>
<div class="pageWrap">
<?php echo $this->cmsBreadcrumb($this->title,array('task'=>'no-data')) .' '.$this->blkAccountGroup($this->identity());?>
</div>
<div class="pageWrap">
        <div class="leftMainContent">
            <div class="companyDetail">
                <div class="contentDetail">
                    <div class="leftSmallContent">
                        
<div class="topObjectTitle">
    <a href="<?php echo $website;?>" target="_blank" title="<?php echo $name;?>" class="avatar">
        <img src="<?php echo $logo ;?>" width="95" alt="<?php echo $name;?>" title="<?php echo $name;?>"></a>
    <div class="text">
        <h1>
            <?php echo $name;?><span><?php echo $address;?></span><span>ĐT:
                <?php echo $phone ;?>
                &nbsp;&nbsp;|&nbsp;&nbsp; Fax: <?php echo $fax;?>
                </span></h1>
        <a href="<?php echo $website;?>" target="_blank">
            <?php echo $website;?></a>
    </div>
</div>
<script type="text/javascript">
$(document).ready(function() {
    $(".topObjectTitle img").error(function () {
        $(this).attr("src", "http://muabannhadat.com.vn/images/users/imageUser.gif");
    });
});
</script>
                        
<ul class="tabS">
    <li><h4><a href="<?php echo $linkIntroBusiness;?>" title="Giới thiệu" >Giới thiệu</a></h4></li>
    <li style="display:inline-block;"><h4><a href="<?php echo $linkContact;?>" class="current">Liên hệ</a></h4></li>   
    <li style="display:inline-block;"><h4><a href="<?php echo $linkDepartment;?>" >Chi nhánh</a></h4></li> 
    <li style="display:inline-block;"><h4><a href="<?php echo $linkLandSale;?>" >Nhà đất bán (<?php echo $this->countLandSale;?>)</a></h4></li>
    <li style="display:inline-block;"><h4><a href="<?php echo $linkLandForRent;?>" >Nhà đất cho thuê (<?php echo $this->countLandForRent;?>)</a></h4></li>
   <li id="MainContent_VPMG_Leftmenu1_thongTinThem" class="moreInfo"><a href="#" title="Dự án của doanh nghiệp">
        Dự án của DN</a>
        <ul>
            
            <li><h4><a href="<?php echo $linkInvestors;?>" title="Dự án Chủ đầu tư">Dự án Chủ đầu tư (<?php echo $this->countInvestors;?>)</a></h4></li>
            <li><h4><a href="<?php echo $linkConstruction;?>" title="Dự án Thi công">Dự án Thi công (<?php echo $this->countConstruction;?>)</a></h4></li>
            <li><h4><a href="<?php echo $linkManagement;?>" title="Dự án Quản lý">Dự án Quản lý (<?php echo $this->countManagement;?>)</a></h4></li>
            <li><h4><a href="<?php echo $linkDesign;?>" title="Dự án thiết kế">Dự án Thiết kế (<?php echo $this->countDesign;?>)</a></h4></li>
            <li><h4><a href="<?php echo $linkDistributors;?>" title="Dự án Phân phối">Dự án Phân phối (<?php echo $this->countDistributors;?>)</a></h4></li>
            
             
        </ul>
    </li>
</ul>




                        
<script type="text/javascript">
    //<!--
    var vpmg_contact = {
        Send_Mail_VpMoigioi: function (kind, idStatistics, isMBND) {
            if ($("#txtName").val() == "") { alert("Vui lòng nhập tên của bạn!"); $("#txtName").focus(); return false; }
            if ($("#txtEmail").val() == "") { alert("Vui lòng nhập email của bạn!"); $("#txtEmail").focus(); return false; }
            if (!mjIsEmailvp(document.getElementById("txtEmail"))) { alert("Email không hợp lệ!"); $("#txtEmail").focus(); return false; }
            if (
				$("#txtPhone").val() == "" || (!$("#txtPhone").val() == ""
				&& !CheckPhoneNumbervp($("#txtPhone").val()))
				)
            { alert("Chưa nhập số điện thoại của bạn !"); $("#txtPhone").focus(); return false; }
            if ($("#txtSubject").val() == "") { alert("Vui lòng nhập tiêu đề!"); $("#txtSubject").focus(); return false; }
            if ($("#Message").val() == "") { alert("Vui lòng nhập nội dung !"); $("#Message").focus(); return false; }
            //$("#btnSendvpmg").disabled = false;			

            var fto = encodeURI($("#hEmail").val());
            var fn = encodeURI($("#txtName").val());
            var ffrom = encodeURI($("#txtEmail").val());
            var ftel = encodeURI($("#txtPhone").val());

            ShowProccessButton('loadingContactBroker', 'contactBroker', 1);

            var url = pathClientAjax + "Services/Misc.asmx/SendEmailVPMoiGioi";
            $.post(url, { subject: "Liên hệ doanh nghiệp", content: $("#Message").val(), phone: ftel, name: fn, from: ffrom, to: fto },
				function (data) {
				    if (data == "Success") {
				        StatisticsClick(kind, idStatistics, isMBND);
				        alert("Thư của bạn đã gửi thành công!");
				        ShowProccessButton('loadingContactBroker', 'contactBroker', 2);
				    }
				    else {
				        alert("Đã có lỗi lúc gửi, vui lòng thử lại !");
				        ShowProccessButton('loadingContactBroker', 'contactBroker', 2);
				    }
				});
        },
        resetForm: function () {
            $("#txtName").val("");
            $("#txtEmail").val("");
            $("#txtPhone").val("");
            $("#txtSubject").val("");
            $("#Message").val("");
        }
    }
    //-->
</script>
<h4>
    Thông tin liên hệ</h4>
<?php echo $contact;?>
<h4>
    Liên hệ</h4>
    <!-- LIÊN HỆ -->
            <?php 
            $contactMeForm = $this->contactMeForm;
            $contactMeForm->setAttribute('action', $this->url('MVC_HomeRouter/action', array(
                'module'    =>  'home',
                'controller'    => 'business',
                'action'        => 'contact-me'
            )));
            echo $this->form()->openTag($contactMeForm);
            ?>          
<div class="formSendEmail">
                <div id="contact-me-success" style="display: none;"><b>&nbsp;</b>
                        <span><div id="contact-me-message-success" ></div></span>
                </div>

                <div class="selectedValues marB15">
                    
                    <?php  echo $this->formText($contactMeForm->get('contact-me-fullname'));?>
                    <span class="btDropdown del" title="Xóa" onclick="$('#contact_me_txtName').val('');"></span>
                    <div id="contact-me-error-fullname" style="display: none;"><b>&nbsp;</b>
                    <span><em id="contact-me-error-message-fullname" ></em></span>
                    </div>
                </div>
                <div class="selectedValues marL15 marB15">
                    <?php  echo $this->formText($contactMeForm->get('contact-me-phone'));?>
                    <span class="btDropdown del" title="Xóa" onclick="$('#contact_me_txtPhone').val('');"></span>
                    <div id="contact-me-error-phone" style="display: none;"><b>&nbsp;</b>
                    <span><em id="contact-me-error-message-phone"></em></span>
                    </div>
                </div>
                <div class="selectedValues marL15 marB15">
                    <?php  echo $this->formText($contactMeForm->get('contact-me-email'));?>
                    <span class="btDropdown del" title="Xóa" onclick="$('#contact_me_txtEmail').val('');"></span>
                    <div id="contact-me-error-email" style="display: none;"><b>&nbsp;</b>
                    <span><em id="contact-me-error-message-email"></em></span>
                    </div>
                </div>
                <?php  echo $this->formTextarea($contactMeForm->get('contact-me-content'));?>
                <div id="contact-me-error-content" style="display: none;"><b>&nbsp;</b>
                    <span><em id="contact-me-error-message-content"></em></span>
                </div>
              <div id="btSendMail">
                    <?php  echo $this->formHidden($contactMeForm->get('contact-me-realestate-id'));?>
                    <?php  echo $this->formHidden($contactMeForm->get('contact-me-user-id'));?>
                    <?php  echo $this->formSubmit($contactMeForm->get('contact-me-submit'));?>
              </div>
            </div>

            
            <?php echo $this->form()->closeTag();?>
            <script type="text/javascript" src="<?php echo TEMPLATE_URL;?>/default/js/jquery.min.js"></script>
            <script type="text/javascript" src="<?php echo TEMPLATE_URL;?>/default/js/jquery.form.js"></script>

            <script type="text/javascript">
            $(document).ready(function () {
               

                //Liên hệ
                $('#contact-me').submit(function(){
                    $(this).ajaxSubmit(options); 
                    return false; 
                });
    
            });
            //Liên hệ
            var options = { 
                target      : '#ajax-info',
                dataType    : 'json',
                success     : showResponse  
         
            }; 

            function showResponse(data){
                if(data.status == 'success'){
                    
                    $('#contact-me-success').removeAttr('style');
                    $('#contact-me-error-message-fullname, #contact-me-error-message-phone,#contact-me-error-message-email, #contact-me-error-message-content').removeAttr('style');

                    $('#contact-me-error-fullname, #contact-me-error-phone, #contact-me-error-email, #contact-me-error-content').css({'display':'none'});

                    $('#contact-me-message-success').html(data.messages['success'])
                                        .removeClass()
                                        .addClass('content-success')
                                        .css({'width':'684px','background':'green','padding':'5px','color':'white'});
                    
                    //refresh                    
                    $('#contact_me_txtName').val('');
                    $('#contact_me_txtPhone').val('');
                    $('#contact_me_txtEmail').val('');
                    $('#contact_me_txtContent').val('');
                   
                }else if(data.status == 'error'){
                    
                    $('#contact-me-success').css({'display':'none'});

                    $('#contact-me-error-fullname, #contact-me-error-phone, #contact-me-error-email, #contact-me-error-content').removeAttr('style');

                    $('#contact-me-error-message-fullname').html(data.messages['fullname'])
                                         .removeClass()
                                         .addClass('content-error')
                                         .css({'width':'386px','color':'red'});
                    $('#contact-me-error-message-phone').html(data.messages['phone'])
                                            .removeClass()
                                            .addClass('content-error')
                                            .css({'width':'386px','color':'red'});
                    $('#contact-me-error-message-email').html(data.messages['email'])
                                            .removeClass()
                                            .css({'width':'386px','color':'red'});
                    $('#contact-me-error-message-content').html(data.messages['content'])
                                            .removeClass()
                                            .css({'width':'386px','color':'red'});                                               
                    
                }else if(data.status == undefined){
                    $('#ajax-info').html('Có lỗi trong quá trình xử lý').removeClass().addClass('content-warning');
                }
            }

            //end liện hệ
            </script>
            <!-- END LIÊN HỆ -->



<script type="text/javascript">
    function StatisticsClick(kind, idStatistics, isMBND) {
        var param = {
            kind: kind,
            idStatistics: idStatistics,
            isMBND: isMBND
        };
        $.post(pathClientAjax + "services/PropertyHandler.asmx/StatisticsClick", param);
    }
</script>
                    </div>
                </div>
            </div>
        </div>
        <div class="rightMainContent">
  <?php echo $this->blkAdsColumnRight();?>     


  <script type="text/javascript">
      function DisplayMe(div) {
          document.getElementById(div).style.display = '';
      }

      $('#txtEmailNL').click(function (event) {$('html').one('click', function () {$("#infoDiv").hide();});event.stopPropagation();});$('#txtFullName').click(function (event) {$('html').one('click', function () {$("#infoDiv").hide();});event.stopPropagation();});
  </script>



 

    <script type="text/javascript">
        $("#divTopAgent .padded .infoGroup img").error(function (event) {
            $(this).attr("src", "http://images.videonhadat.com.vn/avatar_male_84x94.gif");
        })
    </script> 
      
  <?php echo $this->blkRegisterEmail();?> 
  <?php echo $this->blkNhanXet();?> 
  <?php echo $this->blkLienKet();?> 
  </div>
    </div>