<?php
$myForm = $this->myForm;
$myForm->prepare();
$elementId			= $myForm->get('id');
$elementTitle 		= $myForm->get('title');
$elementFile		= $myForm->get('file');
$file 				= (!empty($this->item->file)) ? $this->item->file : 'Updating...';
$elements = array(
	array(
		'label'				=>	$this->formLabel($elementTitle),
		'input'				=>	$this->formElement($elementTitle),
		'class'				=>	'col-sm-9',
		'required'			=>	'*',
		'tooltiptitle'		=>	'Tiêu đề',
		'tooltipmessage'	=>	'Nhập Tiêu đề',
	),
	
	array(
		'label'				=>	'Danh mục',
		'input'				=>	$this->cmsSelect('cat_id',$this->item->cat_id,$this->itemsCategoryNews,'no-level',array('style' =>'padding: 4px 8px; width:206px;')),
		'class'				=>	'col-sm-9',
		'required'			=>	'*',
		'tooltiptitle'		=>	'Chọn Danh mục',
		'tooltipmessage'	=>	'Chọn Danh mục',
	),
	
	
	array(
		'label'				=>	$this->formLabel($elementFile),
		'input'				=>	'<div id="load-avatar">'.$file.'
								<input name="image_hidden" type="hidden" value="'.$this->item->file.'"/>
								</div><br>
								
								<input name="file" type="file" />
								<button class="Button btn btn-small">Tải lên</button>
								',
		'class'				=>	'col-sm-9',
		'required'			=>	'',
		'tooltiptitle'		=>	'Tập tin biểu mẫu hợp đồng',
		'tooltipmessage'	=>	'Tập tin biểu mẫu hợp đồng',
	),
	
	
);

$messagesErrors = $this->elementErrors(array(
	'title'					=>	$elementTitle,

	
));



 
       


?>


<form name="appForm" method="post" action="" enctype="multipart/form-data">

<?php include('sublink/index.php');?>
    <!--Nội dung load ở đây-->                   
    <div id="cph_Main_ContentPane">
        <div class="widget">
            <?php include('toolbar/index.php');?>
            
            <div class="widget-body">
            	<?php echo $messagesErrors;?>
            	<?php echo $this->errorMessages($this->error,'admin');?>
	   			<table class="admintable" style="width: 100%;">
	    			<?php  echo $this->form()->openTag($myForm);
	    			echo $this->formElement($elementId);
					echo $this->partialLoop('admin/form-group.phtml',$elements);
					echo $this->form()->closeTag();
					?>
				</table>
           	</div>
        </div> 
   	</div> 
</form>

<script type="text/javascript" src="<?php echo TEMPLATE_URL;?>/admin/js/1.8.3/jquery.min.js"></script>
<script type="text/javascript" src="<?php echo TEMPLATE_URL;?>/admin/js/jquery-ui.js"></script>


<script type="text/javascript">
		$(function() {
			

		    //upload avatar
			$j("#appForm").submit(function(){
			    var formData = new FormData($(this)[0]);
			    
			    $j.ajax({
			        url: "<?php echo $this->url(null,array('module'=>'admin','controller'=>'contractform','action'=>'upload'));?>",
			        type: 'POST',
			        data: formData,
			        async: false,
			        success: function (data) {
			        	$j("#load-avatar").html(data);
			        },
			        cache: false,
			        contentType: false,
			        processData: false
			    });

			    return false;
			});


		});

	  </script>   	
   	      	 	