<?php



$title  		= $this->item['title'];
$name_category 	= $this->item['name_category'];
$file 			= $this->item['file'];

?>

<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<link href="<?php echo TEMPLATE_URL;?>/admin/css/layout.css" media="screen" rel="stylesheet" type="text/css" >


<div class='message info'><h5>Xem nhanh</h5>
<p class='detail-info even'><span></p>
<p class='detail-info even'><label>Tiêu đề:</label><span><?php echo $title ;?></span></p>
<p class='detail-info even'><label>Danh mục:</label><span><?php echo $name_category;?></span></p>
<p class='detail-info even'><label>Tập tin:</label><span><?php echo $file;?></span></p>

</div>