<div class="page-content container mbn-posting clearfix">
    <div class="row">
        <div class="col-md-3 col-sm-2 hidden-xs"></div>
        <div class="col-md-6 col-xs-12 col-sm-8">

    <div id="form-register">
        <form action="/" class="form" method="post"><input name="__RequestVerificationToken" type="hidden" value="ZVoZBEZeZQgLRXVHjTGkCXMFYz0YLwOSXWLM4fRzF1EzUXJPOaH0hIJGD2LaNm0ePw-eIU0CEra7HZ5ikcfB_wSc7FY1" /><input id="sid" name="sid" type="hidden" value="858d4d8cf4e3421a8f5738ebaa2ec0d3" /><input data-val="true" data-val-number="The field mode must be a number." data-val-required="The mode field is required." id="mode" name="mode" type="hidden" value="0" /><input id="AppName" name="AppName" type="hidden" value="muabannet" /><input id="Services" name="Services" type="hidden" value="mbnv2" /><input id="returnUrl" name="returnUrl" type="hidden" value="https://muaban.net/dang-tin" /><input id="callbackUrl" name="callbackUrl" type="hidden" value="https://muaban.net/trang-ca-nhan/SignInCallback" /><input data-val="true" data-val-required="The IsShowCaptCha field is required." id="IsShowCaptCha" name="IsShowCaptCha" type="hidden" value="False" />        <div class="col-md-12 content">
                <div data-gtm-event="mbn-event-all"
                     data-gtm-category="mbn-user"
                     data-gtm-action="sign-in"
                     class="button-social button-facebook" onclick="javascript: goSocial('facebook')">
                    <span class="icon-facebook"></span>
                    Đăng nhập bằng Facebook
                </div>
                <div class="button-space"></div>
                <div data-gtm-event="mbn-event-all"
                     data-gtm-category="mbn-user"
                     data-gtm-action="sign-in"
                     class="button-social button-google" onclick="javascript:goSocial('google')">
                    <span class="icon-google-plus"></span>
                    Đăng nhập bằng Google
                </div>
                <div class="button-space"></div>

                <div data-gtm-event="mbn-event-all"
                     data-gtm-category="mbn-user"
                     data-gtm-action="sign-in"
                     class="button-social button-yahoo" onclick="javascript: goSocial('yahoo')">
                    <span class="icon-yahoo"></span>
                    Đăng nhập bằng Yahoo
                </div>
                <div class="button-space"></div>
                <div class="divider">
                    <hr class="left" />Hoặc đăng nhập bằng Email / Điện thoại<hr class="right" />
                </div>

                <div class="form-group">
                    <input class="form-control" data-val="true" data-val-required="Bạn vui lòng nhập Email / Điện thoại / tên đăng nhập" id="UserName" maxlength="256" name="UserName" placeholder="Email / Điện thoại đăng nhập *" type="text" value="" />
                    <span class="field-validation-valid" data-valmsg-for="UserName" data-valmsg-replace="true"></span>
                </div>
                <div class="form-group">
                    <input class="form-control" data-val="true" data-val-maxlength="Mật khẩu tối đa 50 ký tự" data-val-maxlength-max="50" data-val-required="Bạn vui lòng nhập Mật khẩu" id="Password" maxlength="51" name="Password" placeholder="Mật khẩu *" type="password" />
                    <span class="field-validation-valid" data-valmsg-for="Password" data-valmsg-replace="true"></span>
                </div>


                <div class="form-group">
                    <div class="btn-submit">
                        <div id="errorSummary">

                        </div>
                        <div style="color:#555">
                            Bạn là khách hàng thường xuyên đăng tin lên web muaban.net và tin của bạn cần ĐĂNG GẤP NGAY LẬP TỨC.
                            Hãy đến <a href="https://muaban.net/thong-tin/dia-diem-dang-tin" target="_blank">văn phòng giao dịch</a> của chúng tôi để xác thực chứng minh nhân dân hoặc gọi tổng đài hỗ trợ 1900 6868, 028.7300 1234 (HCM), 024.7300 1234 (HN)
                        </div>
                        <input data-gtm-event="mbn-event-all"
                               data-gtm-category="mbn-user"
                               data-gtm-action="sign-in"
                               type="submit" onclick="clearValidationSum();" value="Đăng nhập" class="button" />&nbsp;&nbsp;<a href="javascript:void(0);" onclick="javascript:goForgot();">Quên mật khẩu</a>?
                    </div>
                </div>
                <div class="form-group">
                    <input checked="checked" data-val="true" data-val-required="The Lưu đăng nhập? field is required." id="RememberMe" name="RememberMe" type="checkbox" value="true" /><input name="RememberMe" type="hidden" value="false" /> <label for="RememberMe" style="color: #555555; font-weight: normal;">Lưu đăng nhập trên máy này</label>
                </div>
            </div>
        </form></div>
        </div>
        <div class="col-md-3 col-sm-2 hidden-xs"></div>
    </div>
</div>