<!DOCTYPE html>
<!--[if lt IE 7]><html class="lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]><html class="lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]> <html class="lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html>
<!--<![endif]-->
<head><?php require_once 'inc/head.php';?></head>
    <body>

    		<div id="wrapper">
    			<?php require_once 'inc/header.php';?>
    			<div id="content">
    				<div class="ct-in-all">
    					<?php echo $this->content;?>
    				</div>
    			</div>
    			<?php require_once 'inc/content-bottom.php';?>
    			<?php require_once 'inc/footer.php';?>
    		</div>

    </body>
</html>
