<?php


$xhtml = '';
if(!empty($this->items)){
	foreach($this->items as $item){
		$xhtml .= sprintf(' <tr>
							<td>%s</td>
							<td>%s</td>
							</tr>
							',$item->id,$item->username);	
	}
}
?>

<table class="table table-striped table-bordered dataTable table-hover" cellspacing="0" id="cph_Main_ctl00_ctl00_grvProducts" style="border-collapse:collapse;">
<tr>
	<th width="5%">ID</th>
	<th>Name</th>
</tr>
<?php echo $xhtml;?>
</table>

<?php
	$currentUrl = $this->url('MVCAdminRouter/pagination');
 	echo $this->paginationControl($this->paginator , 'sliding' , 'paginator.phtml', array('currentUrl'=>$currentUrl)); 

 ?>

 <a href="<?php echo $this->url(null,array('module'=>'admin','controller'=>'user','action'=>'index'));?>">Index</a>
| <a href="<?php echo $this->url(null,array('module'=>'admin','controller'=>'user','action'=>'add'));?>">Add</a>
| <a href="<?php echo $this->url(null,array('module'=>'admin','controller'=>'user','action'=>'delete'));?>">Delete</a>
| <a href="<?php echo $this->url(null,array('module'=>'admin','controller'=>'user','action'=>'edit'));?>">Edit</a>



