
<form name="appForm" method="post" action="">
<div id="BoxListStaff">
	<div class="TitleBox">
		<h2><?php echo $this->title;?></h2>
	</div>
	
	
	<div class="dataTables_wrapper">
                        <!-- V? tri load datat-->
    </div>	
<?php
$page       = !empty($this->arrParam['page']) ? $this->arrParam['page'] : 1;
$LinkPage   = $this->basePath()."/".$this->arrParam['module']."/contactbusiness/list/page/".$page;
?>
<script type="text/javascript">

$(document).ready(function(){
    $(".loading").show();
    $.ajax({
        url     : '<?php echo $LinkPage;?>',
        type    : 'GET',
        data    : {page : <?php echo $page;?>},
        cache   : false,
        success : function(data,status){
            $("div.dataTables_wrapper").html(data);
            $(".loading").fadeOut(1000);
        }
    });
})



</script>

<script type="text/javascript">


function deleteStaff(id)
{   
    if(!confirm("Bạn có chắc xóa dữ liệu này?")) return;
    else
    {
        window.location = '<?php echo $this->url(null,array("module"=>"user","controller"=>"contactbusiness","action"=>"delete"));?>' + id;
    }   
}

</script>
	<div class="PagesNumber" id="dvPaging" style="display: none;"></div>
</div>
</form>