<?php

//List danh mục
$urlAll           = $this->url('ListNiceHouseRoute',array('module'=>'home','controller'=>'nicehouse','action'=>'index'));
$xhtmlTabCategory = '<li id="tab-0" class="current">
                          <h4><a href="'.$urlAll.'" title="Tất cả">
                          Tất cả</a></h4></li>';
if(!empty($this->listItemsCategory)){
  foreach ($this->listItemsCategory as $key => $item) {
 
    $urlCategory = $this->url('CategoryNiceHouseRoute',array(
      'module'=>'home',
      'controller'  =>'nicehouse',
      'action'      =>'category',
      'name'        => \ZendVN\Url\FriendlyLink::filter($item['name']),
      'page'        => '1',
      'id'          => $item['id'],
       'extension'  => 'html',
    ));
    $xhtmlTabCategory .= '<li id="tab-'.$item['id'].'">
                          <h4><a href="'.$urlCategory.'" title="'.$item['name'].'">
                          '.$item['name'].'</a></h4></li>
                          ';
  }
}


?>
  
  
<div class="pageWrap">
<?php echo $this->cmsBreadcrumb($this->breadcrumb,array('task'=>'data')) .' '.$this->blkAccountGroup($this->identity());?>
</div>
  
  
<div class="pageWrap">
  <div class="leftMainContent">      
    <?php echo $this->blkSlideNiceHouse();?>
          
    <div class="boxTab niceHouseTab">
      <ul>
          <?php echo $xhtmlTabCategory;?>
      </ul>
    </div>


 <div class="dataTables_wrapper"><!--load--></div>
        <?php
        $page       = !empty($this->arrParam['page']) ? $this->arrParam['page'] : 1;
        $LinkPage   = $this->basePath()."/".$this->arrParam['module']."/nicehouse/list/page/".$page;
        $catid      = (!empty($this->arrParam["id"])) ? $this->arrParam["id"] : "" ;
        $name       = $this->arrParam["name"];
        ?>
        <script type="text/javascript">

        $(document).ready(function(){

            var classCurrent = '<?php echo $this->arrParam['id'];?>';
            if(classCurrent != '0'){
                $('#tab-0').removeClass();
            }    
            $('#tab-' + classCurrent).addClass("current");

            $(".loading").show();
            var page        = '<?php echo $page;?>';
            var catid       = '<?php echo $catid ?>';
            var name        = '<?php echo $name;?>';
            $.ajax({
                url     : '<?php echo $LinkPage;?>',
                type    : 'GET',
                data    : {page: page, catid: catid, name: name},
                cache   : false,
                success : function(data,status){
                    $("div.dataTables_wrapper").html(data);
                    $(".loading").fadeOut(1000);
                }
            });
        });

        </script>

        </div>
  <div class="rightMainContent">
  <?php echo $this->blkAdsColumnRight();?>     


  <script type="text/javascript">
      function DisplayMe(div) {
          document.getElementById(div).style.display = '';
      }

      $('#txtEmailNL').click(function (event) {$('html').one('click', function () {$("#infoDiv").hide();});event.stopPropagation();});$('#txtFullName').click(function (event) {$('html').one('click', function () {$("#infoDiv").hide();});event.stopPropagation();});
  </script>



 

    <script type="text/javascript">
        $("#divTopAgent .padded .infoGroup img").error(function (event) {
            $(this).attr("src", "http://images.videonhadat.com.vn/avatar_male_84x94.gif");
        })
    </script> 
      
  <?php echo $this->blkRegisterEmail();?> 
  <?php echo $this->blkNhanXet();?> 
  <?php echo $this->blkLienKet();?> 
  </div>
</div>