

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Đăng nhập hệ thống</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8 " />
    <meta name="ROBOTS" content="NOINDEX, NOFOLLOW" />
    <link rel="Shortcut Icon" href="http://static.bizwebmedia.net/favicon.ico" type="image/x-icon" />
    <link type="text/css" rel="stylesheet" href="<?php echo TEMPLATE_URL;?>/default/css/bootstrap.css?v1.5" />
    <link type="text/css" rel="stylesheet" href="<?php echo TEMPLATE_URL;?>/default/css/font-awesome.css" />
    <link type="text/css" rel="stylesheet" href="<?php echo TEMPLATE_URL;?>/default/css/style2.css?v1.5" />
    <link type="text/css" rel="stylesheet" href="<?php echo TEMPLATE_URL;?>/default/css/style_default.css?v1.5" />
    <link href="<?php echo TEMPLATE_URL;?>/default/css/login.css" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="<?php echo TEMPLATE_URL;?>/default/js/jquery-1.3.1.min.js"></script>
</head>
<body>
    <form method="post" action="" id="form1" name="login-form" id="login-form">
<div class="aspNetHidden">

</div>

<script type="text/javascript">
//<![CDATA[
var theForm = document.forms['form1'];
if (!theForm) {
    theForm = document.form1;
}
function __doPostBack(eventTarget, eventArgument) {
    if (!theForm.onsubmit || (theForm.onsubmit() != false)) {
        theForm.__EVENTTARGET.value = eventTarget;
        theForm.__EVENTARGUMENT.value = eventArgument;
        theForm.submit();
    }
}
//]]>
</script>





<div class="aspNetHidden">

 
</div>
    <script type="text/javascript">var $j = jQuery.noConflict();</script>
    <script type="text/javascript" src="/Extensions/Js/jquery-ui-1.6rc6.min.js"></script>
    <div style="width: 100%; margin: 0 auto;">
        <div class="content">
            <div style="width: 100%; margin: 0 auto;">
                    
    <div id="cphMain_Content">
<script type="text/javascript">
    function sizeBox() {
        var w = $j(window).width();
        var h = document.getElementsByTagName('html')[0].clientHeight
        $j('#box').css('position', 'absolute');
        $j('#box').css('top', h / 2 - ($j('#box').height() / 2) - 30);
        $j('#box').css('left', w / 2 - ($j('#box').width() / 2));
    }
    $j(document).ready(function () {
        sizeBox();
        $j('#txtUserName').focus();
    });
    $j(window).resize(function () {
        sizeBox();
    });
</script>

<?php echo $this->content;?> 
<div id="cphMain_ctl00_Passport_Reg">
</div>
</div>

            </div>
        </div>
    </div>
    

<script type="text/javascript">
//<![CDATA[
WebForm_AutoFocus('cphMain_ctl00_txtUserName');//]]>
</script>
</form>
</body>
</html>
