<?php
$menuHome       = $this->url('home',array('module'=>'home','controller'=>'index','action'=>'index'));
$menuBds        = $this->url('ListBatDongSanRoute',array('controller'=>'realestate','action'=>'index'));
$menuProject    = $this->url('ListProjectRoute',array('module'=>'home','controller'=>'project','action'=>'index'));

?>

<div class="pageWrap">
<?php echo $this->cmsBreadcrumb($this->title,array('task'=>'no-data')) .' '.$this->blkAccountGroup($this->identity());?>
</div>

<div class="pageWrap">
        <div class="leftMainContent">
            <div id="MainContent_DetailItem11_divMesStt" class="messageBox1 outside">
                        <div class="colImgs"></div>
                        <div class="colNews">
                            <h5>Bạn không có quyền truy cập vào chức năng này !  </h5>
                            
                        </div>
        </div>




            
        </div>
        <div class="rightMainContent">
             <?php echo $this->blkAdsColumnRight();?>     

        </div>
    </div>