<?php




//Doanh nghiệp thành phố lớn
$xhtmlCity = '';
if(!empty($this->listCity)){
    foreach($this->listCity as $item){
        $urlCity   = $this->url(
            'CityBatDongSanRoute',
            array('controller'=>'realestate','action'=>'city','cityname'=>\ZendVN\Url\FriendlyLink::filter($item['name']),'page'=>1,'cityid'=>$item['id']
        ));
        $xhtmlCity      .= '<li>  <a href="'.$urlCity.'" title="'.$item['name'].'">'.$item['name'].' <span></span>  </a></li>';
    }  
}


?>

<div class="pageWrap">
<?php echo $this->cmsBreadcrumb(null,array('task'=>'no-data')) .' '.$this->blkAccountGroup($this->identity());?>
</div>
<div class="pageWrap">
    <div class="leftMainContent">
        

        <div class="boxTab">
            <ul>
                
                <li id="MainContent_ListItems1_srchli2"><h4><a href="#"id="MainContent_ListItems1_ali2">Kết quả tìm kiếm <span></span></a></h4></li>                          
                
               

            </ul>
             
        </div>

        <div class="resultList">
            <div class="contentDetail">
            <div class="leftSmallContent">
              
                
                <div class="dataTables_wrapper"><!--load--></div>
                <?php
                $page       = !empty($this->arrParam['page']) ? $this->arrParam['page'] : 1;
                $LinkPage   = $this->basePath()."/".$this->arrParam['module']."/realestate/search-ajax/page/".$page;
                ?>
                <script type="text/javascript">

               $(document).ready(function(){
                $(".loading").show();
                 $("#MainContent_ListItems1_srchli2").addClass("current");
                var page        = '<?php echo $page;?>';
                var cat         = '<?php echo $this->arrParam["cat"];?>';
                var city        = '<?php echo $this->arrParam["city"];?>';
                var district    = '<?php echo $this->arrParam["district"];?>';
                var price       = '<?php echo $this->arrParam["price"];?>';
                var area        = '<?php echo $this->arrParam["area"];?>';
                var transaction = '<?php echo $this->arrParam["transaction"];?>';
                $.ajax({
                    url     : '<?php echo $LinkPage;?>',
                    type    : 'GET',
                    data    : {page: page, transaction : transaction, cat: cat, city: city, district: district, price: price, area: area},
                    cache   : false,
                    success : function(data,status){
                        $("div.dataTables_wrapper").html(data);
                        $(".loading").fadeOut(1000);
                    }
                });
            });

                </script>


                
                 <script>
        ga('send' ,'timing', 'SearchResult', 'Sql time', 408);
        </script>
                 
            </div>
        </div>
        </div>

        <script language="javascript" type="text/javascript">
            //<!--
            SetLstSearch('#tab=rv&tck=res-sale-home&z=nha-ban');
            //-->
     </script>



    <input name="ctl00$MainContent$ListItems1$hdOderBy" type="hidden" id="MainContent_ListItems1_hdOderBy"> 
        <input name="ctl00$MainContent$ListItems1$hdDtqc" type="hidden" id="MainContent_ListItems1_hdDtqc">
        <input name="ctl00$MainContent$ListItems1$hdMaxPage" type="hidden" id="MainContent_ListItems1_hdMaxPage" value="20">
      <input name="ctl00$MainContent$ListItems1$hdPriceType" type="hidden" id="MainContent_ListItems1_hdPriceType">
      <script language="javascript" type="text/javascript">
          //<!--
          var _ctrRes = "MainContent_ListItems1_";
          if (document.getElementById(_ctrRes + 'hdDtqc').value != "")
              $('#li_dtqc').addClass("current");
          else if (document.getElementById(_ctrRes + 'hdOderBy').value != "") {
              $('#li_' + document.getElementById(_ctrRes + 'hdOderBy').value).addClass("current");
          }
    //      else {
    //          $('#li_ranking').addClass("current");
    //      }

          if (document.getElementById(_ctrRes + 'hdMaxPage').value != "") document.getElementById('cbDisplay').value = document.getElementById(_ctrRes + 'hdMaxPage').value;


          $("#" + _ctrRes + "DivPropertyList1 img").error(function () {
              $(this).attr("src", "http://muabannhadat.com.vn/images/noimages.gif");
          });
          //-->
          $('#MainContent_ListItems1_ali5').on('click', function () {
              ga('send', 'event', 'category-listing', 'click', 'co-hinh-buttons');
          });

          $('#MainContent_ListItems1_ali4').on('click', function () {
              ga('send', 'event', 'category-listing', 'click', 'chinh-chu-buttons');
          });

          $('.acceptEmail').on('click', function () {
              ga('send', 'event', 'category-listing', 'click', 'nhan-bds-email-buttons');
          });

          $('.saveProperty').on('click', function () {
              ga('send', 'event', 'category-listing', 'click', 'luu-bds-buttons');
          });

      </script>




        <div class="catalogDistrict">
            <h2 class="leftTitle"><b>Nhà đất ở các tỉnh thành</b></h2>
            <div class="leftSmallContent">
                <ul class="leftLine">
                    <?php echo  $xhtmlCity;?>
                </ul>
          </div>
        </div>


  </div>
  <div class="rightMainContent">
        <?php echo $this->contentRightColumn;?>
  </div>
</div>