
<?php
$isXmlHttpRequest = $this->isXmlHttpRequest;
if($isXmlHttpRequest == true){
$xhtml = '';
if(!empty($this->items)){
    foreach($this->items as $item){
       
        $id             = $item['id'];
        $name           = $item['name'];
        $name_category  = $item['name_category'];
        $area           = $item['area'];
        $cat_id         = $item['cat_id'];
       
        $address        = $item['address'] . ' - '. $item['name_district'] .' - '.$item['name_city'];
        $image          =  TEMPLATE_URL .'/admin/images/NoImage.jpg';
        $i              = 1;
        if(!empty($item['images'])){
            $images  = \Zend\Json\Json::decode($item['images']);
            foreach ($images as $key => $image) {
                if($i == 1){
                    $image = UPLOAD_URL .'/project/'.$image;
                    break;
                } 
            }
        }

        

        $linkDetail = $this->url('IntroProjectRoute',array(
            'module'        =>  'home',
            'controller'    =>  'project',
            'action'        =>  'intro',
            'title'         =>  \ZendVN\Url\FriendlyLink::filter($name),
            'id'            =>  $id,
            'extension'     =>  'html',
        ));

       

      
       
        

        $xhtml .= '<li><a href="'.$linkDetail.'" class="illustrationPic"><img width="150" height="112" src="'.$image.'" alt="'.$name.'" title="'.$name.'"></a>
                        <div class="text">
                            <h3><a href="'.$linkDetail.'" title="'.$name.'">'.$name.'</a></h3>
                            <h4><span>'.$address.'</span></h4>
                            <p>'.$name.'</p>
              <div class="typeSize">
                                <span>Loại hình: <em>'.$name_category.'</em></span><span>Diện tích tổng thể: <em>'.$area.' m2</em></span>
                            </div>
              
                        </div></li>';

                    

                             
    }
}

?>
 <ul class="leftListing1">
    <?php echo $xhtml;?>

 </ul>

  
 <?php
    $paramsUrl  = array(
        'module'        => 'home',
        'controller'   => 'project',
        'action'       => 'index',
        'page'         => '1',
    );
    echo $this->paginationControl($this->paginator , 'sliding' , 'home/business/paginator.phtml', array(
        'router'    => 'ListProjectRoute',
        'arrParam'  =>$paramsUrl,
    )); 
 ?>







<?php
}else{
    echo 'not ajax';
}
?>
