<?php
$isXmlHttpRequest = $this->isXmlHttpRequest;
if($isXmlHttpRequest == true){
	$xhtml  = '';
	if(!empty($this->items)){
	    foreach($this->items as $item){
	    	$date_time 	= $item['date_time'];
	    	$service_id = $item['service_id'];
	    	$name_type 	= $item['name_type'];
	    	$day 		= $item['day'];
	    	$fullname	= $item['fullname'];
	    	$xhtml .= ' <tr>
					    <td>'.$date_time.'</td>
					    <td>Kích hoạt id '.$service_id.'</td>
					    <td>'.$name_type.'</td>
					    <td>'.$day.'</td>
					    <td>'.$fullname.'</td>
					</tr>';
	   	}     
	}    	
?>	

<table class="gridAcc result">
  <tbody><tr class="title">
    <td width="15%">Ngày</td>
    <td width="30%">Nội dung</td>
    <td width="15%">Loại tin</td>
    <td width="15%">Số ngày</td>
    <td width="20%">Tài khoản</td>    
  </tr>
  <?php echo $xhtml;?>
  
</tbody></table>
<?php
    
    $currentUrl =  $this->basePath('/user/statistic/service/page/');
    echo $this->paginationControl($this->paginator , 'sliding' , 'user/paginator.phtml', array('currentUrl'=>$currentUrl)); 
 ?>

<?php
}else{
    echo 'not ajax';
}
?>
