<?php
$isXmlHttpRequest = $this->isXmlHttpRequest;
if($isXmlHttpRequest == true){

$ssFilter               = $this->arrParam['ssFilter'];

//Loại giao dịch
$arrOptions = array(
    array('id'=>'1','name'=>'Logo Text'),
    array('id'=>'2','name'=>'Logo Images'),
    array('id'=>'3','name'=>'Không hiển thị Logo'),
);
$frmType         = $this->cmsSelect('type','',$arrOptions,'no-level',array('style' =>'padding: 4px 8px; width:206px;'));


$arrConfigLogo = \Zend\Json\Json::decode($this->item->config_logo);

$image     = (!empty($arrConfigLogo->logo))  ? UPLOAD_URL .'/skin/'.$arrConfigLogo->logo :  TEMPLATE_URL .'/admin/images/NoImage.jpg';

$myForm = $this->myForm;
$myForm->prepare();
$elementName        = $myForm->get('name');
          
?>

<table class="admintable" width="100%">
    <tbody><tr>
            <td style="vertical-align: top;" class="key" nowrap="">
                Cầu hình Logo
            </td>
            <td>
            
            <div style="height: 18px; margin-top: 10px; width: 330px; padding: 3px 0px 0px 5px;
                background-color: #F6F6F6; border-bottom: 1px solid #E9E9E9; border-right: 1px solid #E9E9E9;
                color: #666666; font-weight: bold;">
                Chọn Logo</div>
            
            <div id="cph_Main_ctl00_ctl00_plLogoImage">

                <div id="LogoImage">
                                            
                <table id="tblUpload" cellspacing="0" cellpadding="0" width="100%">
                    <tbody><tr>
                        <td>
                            
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <div id="load-avatar"><img src="<?php echo $image;?>">
                                <input name="image_hidden" type="hidden" value="<?php echo $arrConfigLogo->logo;?>"/>
                                <input name="type_hidden" type="hidden" value="upload_logo"/>
                                </div><br>
                                
                                <input name="image" type="file" />
                                <button class="Button btn btn-small">Tải lên</button>
                        </td>
                    </tr>
                    <tr>
                                <td>
                                    Slogan
                                </td>
                                <td>
                                    <?php echo $this->formElement($elementName);?>
                                    <img id="helpLogoText" alt="" border="0" style="margin-top: 5px; display: none;" src="/images/help.png" onmouseover="ShowHelp('helpLogoText', 'Nội dung Logo', '')" onmouseout="HideHelp('helpLogoText');">
                                </td>
                            </tr>
                           

                    
                </tbody></table>
                <input type="hidden" name="ctl00$cph_Main$ctl00$ctl00$UploadLogo$hdImageUpload" id="cph_Main_ctl00_ctl00_UploadLogo_hdImageUpload" value="~/sites/60524/upload/Logo/201472992658309.png">

                <div class="Footer" style="padding-left: 20px;">
                    <li>Logo là các loại ảnh gif,jpg vượt quá kích thước 200x200.</li><li>Nếu bạn không
                        upload logo, hệ thống sẽ lấy logo mặc định.</li></div>
                    </div>
    
                    
                                    

                                    
            </div>
                                </td>
                            </tr>
</tbody></table>




    <script type="text/javascript" src="<?php echo TEMPLATE_URL;?>/admin/js/1.8.3/jquery.min.js"></script>
    <script type="text/javascript" src="<?php echo TEMPLATE_URL;?>/admin/js/jquery-ui.js"></script>
    <script type="text/javascript">
        $j(document).ready(function(){
      
           

             //upload avatar
            $("#appForm").submit(function(){
                var formData = new FormData($(this)[0]);
                
                $.ajax({
                    url: "<?php echo $this->url(null,array('module'=>'admin','controller'=>'skin','action'=>'upload'));?>",
                    type: 'POST',
                    data: formData,
                    async: false,
                    success: function (data) {
                        $j("#load-avatar").html(data);
                    },
                    cache: false,
                    contentType: false,
                    processData: false
                });

                return false;
            });

        })

       
        
    </script>


<?php
}else{
    echo 'not ajax';
}
?>




