<div class="minorElement">
    <h5 class="rightTitle">
        Cafe luật</h5>
    <div class="rightSmallContent">
        <h3><a href="http://muabannhadat.com.vn/phap-li-nha-dat/cach-lam-ho-so-the-chap-nha-hinh-thanh-trong-tuong-lai-newsid37556.html" title="Cách làm hồ sơ thế chấp nhà hình thành trong tương lai">Cách làm hồ sơ thế chấp nhà hình thành trong tương lai</a><a href="http://muabannhadat.com.vn/phap-li-nha-dat/cach-lam-ho-so-the-chap-nha-hinh-thanh-trong-tuong-lai-newsid37556.html" title="Cách làm hồ sơ thế chấp nhà hình thành trong tương lai"><img src="http://uploads.videonhadat.com.vn/News/37556/Photos/S/270x203/2482014125824126.jpg" width="266" height="199" alt="Cách làm hồ sơ thế chấp nhà hình thành trong tương lai" title="Cách làm hồ sơ thế chấp nhà hình thành trong tương lai"></a></h3>
        <ul class="rightLine">
            <li><a href="http://muabannhadat.com.vn/phap-li-nha-dat/phap-ly-nha-chung-cu-thu-va-su-dung-quy-bao-tri-nhu-the-nao-newsid37448.html" title="Pháp lý nhà chung cư: Thu và sử dụng quỹ bảo trì như thế nào?">Pháp lý nhà chung cư: Thu và sử dụng quỹ bảo trì như thế nào? <span> (28/07/2014)</span></a></li><li><a href="http://muabannhadat.com.vn/phap-li-nha-dat/doanh-nghiep-dau-tu-bds-hoang-mang-vi-luat-thay-doi-newsid37421.html" title=" Doanh nghiệp đầu tư BĐS: Hoang mang vì luật thay đổi"> Doanh nghiệp đầu tư BĐS: Hoang mang vì luật thay đổi <span> (22/07/2014)</span></a></li>
        </ul>
        <div class="otherChosen">
            <a href="http://muabannhadat.com.vn/phap-li-nha-dat/">Tư vấn pháp lí</a><a href="http://muabannhadat.com.vn/hop-dong-nha-dat/">Biểu mẫu hợp đồng</a><a href="http://muabannhadat.com.vn/van-ban-luat-nha-dat/">Văn bản luật nhà đất</a>
            
        </div>
    </div>
</div>