<?php



$content = $this->item['content'];
$title   = $this->item['name'];
$nguoi_nhan = $this->item['fullname_receive'];
$nguoi_gui = $this->item['fullname_send'];

?>

<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<link href="<?php echo TEMPLATE_URL;?>/admin/css/layout.css" media="screen" rel="stylesheet" type="text/css" >


<div class='message info'><h5>Xem nhanh</h5>
<p class='detail-info even'><span></p>
<p class='detail-info even'><label>Người nhận:</label><span><?php echo $nguoi_nhan  ;?></span></p>
<p class='detail-info even'><label>Người gửi:</label><span><?php echo $nguoi_gui  ;?></span></p>
<p class='detail-info even'><label>Tiêu đề:</label><span><?php echo $title  ;?></span></p>
<p class='detail-info even'><label>Nội dung:</label><span><?php echo $content;?></span></p>


</div>