<?php
$fullname   = $this->item->fullname;
$avatar     = (!empty($this->item->avatar))  ? UPLOAD_URL .'/avatar/'.$this->item->avatar :  TEMPLATE_URL .'/admin/images/NoImage.jpg';

$phone      = $this->item->phone;
$address    = $this->item->diachi;
$email      = $this->item->email;
$introduced     = $this->item->introduced;
$linkDetail     = $this->url('DetailAgencyRoute',array(
                'module'    =>  'home',
                'controller'=>  'agency',
                'action'    =>  'detail',
                'name'      =>  \ZendVN\Url\FriendlyLink::filter($this->item->fullname),
                'id'        =>  $this->item->id,
));


//Đang môi giới
$xhtml = '';
if(!empty($this->itemsDangMoigioi)){
    foreach ($this->itemsDangMoigioi as $key => $item) {
        $linkDetail = $this->url('DetailBatDongSanRoute',array(
            'module'        =>  'home',
            'controller'    =>  'realestate',
            'action'        =>  'detail',
            'namecategory'  =>  \ZendVN\Url\FriendlyLink::filter($item['name_type']),
            'title'         =>  \ZendVN\Url\FriendlyLink::filter($item['title']),
            'cid'           =>  $item['cat_id'],
            'id'            =>  $item['id'],
            'extension'     =>  'html',
        ));
        $xhtml .= '<li><a href="'.$linkDetail.'" title="'.$item['title'].'">'.\ZendVN\Filter\ReadMore::create($item['title'],0,70).'</a></li>';
    }
}
?>


    <script src="<?php echo TEMPLATE_URL;?>/default/js/JsonDefine.js" type="text/javascript"></script>
    <link href="<?php echo TEMPLATE_URL;?>/default/css/lightbox_Property_detail.css" type="text/css" rel="stylesheet" />
    <script type="text/javascript" src="<?php echo TEMPLATE_URL;?>/default/js/jquery.lightbox_PropertyDetail.js?v=23072014.16"></script>
    <script src="<?php echo TEMPLATE_URL;?>/default/js/PropertyDetail.js" type="text/javascript"></script>
    <script src="<?php echo TEMPLATE_URL;?>/default/js/EmailAlert.js" type="text/javascript"></script>
<div class="pageWrap">
<?php echo $this->cmsBreadcrumb($this->title,array('task'=>'no-data')) .' '.$this->blkAccountGroup($this->identity());?>
</div>

<div class="pageWrap">
        <div class="leftMainContent">
            
<div class="topAgentDetail">
    <div class="contentDetail">
        <div class="leftSmallContent">
            <div class="topObjectTitle">
  <a href="<?php echo $linkDetail;?>" target="_blank" title="<?php echo $fullname;?>" class="avatar">
    <img width="168" alt="<?php echo $fullname;?>" title="<?php echo $fullname;?>" src="<?php echo $avatar;?>">
  </a>
  <div class="text">
    <h1>
      <?php echo $fullname;?>
      <span>Điện thoại: <?php echo $phone;?></span>
      <span>Địa chỉ: <?php echo $address;?></span>
      <span>Email: <?php echo $email;?></span>
      <span><?php echo $introduced;?></span>
    </h1>
    <div class="doingBox">
      
      <p>Đang môi giới</p><ul><?php echo $xhtml;?></ul><input type="hidden" id="hdfTaHeaderDuan" value="4">

    </div>
  </div>
</div>
            <h4>
                Liên hệ</h4>
            <!-- LIÊN HỆ -->
            <?php 
            $contactMeForm = $this->contactMeForm;
            $contactMeForm->setAttribute('action', $this->url('MVC_HomeRouter/action', array(
                'module'    =>  'home',
                'controller'    => 'agency',
                'action'        => 'contact-me'
            )));
            echo $this->form()->openTag($contactMeForm);
            ?>           
              <div class="formSendEmail">
                <div id="contact-me-success" style="display: none;"><b>&nbsp;</b>
                        <span><div id="contact-me-message-success" ></div></span>
                </div>

                <div class="selectedValues marB15">
                    
                    <?php  echo $this->formText($contactMeForm->get('contact-me-fullname'));?>
                    <span class="btDropdown del" title="Xóa" onclick="$('#contact_me_txtName').val('');"></span>
                    <div id="contact-me-error-fullname" style="display: none;"><b>&nbsp;</b>
                    <span><em id="contact-me-error-message-fullname" ></em></span>
                    </div>
                </div>
                <div class="selectedValues marL15 marB15">
                    <?php  echo $this->formText($contactMeForm->get('contact-me-phone'));?>
                    <span class="btDropdown del" title="Xóa" onclick="$('#contact_me_txtPhone').val('');"></span>
                    <div id="contact-me-error-phone" style="display: none;"><b>&nbsp;</b>
                    <span><em id="contact-me-error-message-phone"></em></span>
                    </div>
                </div>
                <div class="selectedValues marL15 marB15">
                    <?php  echo $this->formText($contactMeForm->get('contact-me-email'));?>
                    <span class="btDropdown del" title="Xóa" onclick="$('#contact_me_txtEmail').val('');"></span>
                    <div id="contact-me-error-email" style="display: none;"><b>&nbsp;</b>
                    <span><em id="contact-me-error-message-email"></em></span>
                    </div>
                </div>
                <?php  echo $this->formTextarea($contactMeForm->get('contact-me-content'));?>
                <div id="contact-me-error-content" style="display: none;"><b>&nbsp;</b>
                    <span><em id="contact-me-error-message-content"></em></span>
                </div>
              <div id="btSendMail">
                    
                    <?php  echo $this->formHidden($contactMeForm->get('contact-me-user-id'));?>
                    <?php  echo $this->formSubmit($contactMeForm->get('contact-me-submit'));?>
              </div>
            </div>
             <?php echo $this->form()->closeTag();?>
            

  
              <script type="text/javascript">
            //Liên hệ
            var options = { 
                target      : '#ajax-info',
                dataType    : 'json',
                success     : showResponse  
         
            }; 

            function showResponse(data){
                if(data.status == 'success'){
                    
                    $('#contact-me-success').removeAttr('style');
                    $('#contact-me-error-message-fullname, #contact-me-error-message-phone,#contact-me-error-message-email, #contact-me-error-message-content').removeAttr('style');

                    $('#contact-me-error-fullname, #contact-me-error-phone, #contact-me-error-email, #contact-me-error-content').css({'display':'none'});

                    $('#contact-me-message-success').html(data.messages['success'])
                                        .removeClass()
                                        .addClass('content-success')
                                        .css({'width':'684px','background':'green','padding':'5px','color':'white'});
                    
                    //refresh                    
                    $('#contact_me_txtName').val('');
                    $('#contact_me_txtPhone').val('');
                    $('#contact_me_txtEmail').val('');
                    $('#contact_me_txtContent').val('');
                   
                }else if(data.status == 'error'){
                    
                    $('#contact-me-success').css({'display':'none'});

                    $('#contact-me-error-fullname, #contact-me-error-phone, #contact-me-error-email, #contact-me-error-content').removeAttr('style');

                    $('#contact-me-error-message-fullname').html(data.messages['fullname'])
                                         .removeClass()
                                         .addClass('content-error')
                                         .css({'width':'386px','color':'red'});
                    $('#contact-me-error-message-phone').html(data.messages['phone'])
                                            .removeClass()
                                            .addClass('content-error')
                                            .css({'width':'386px','color':'red'});
                    $('#contact-me-error-message-email').html(data.messages['email'])
                                            .removeClass()
                                            .css({'width':'386px','color':'red'});
                    $('#contact-me-error-message-content').html(data.messages['content'])
                                            .removeClass()
                                            .css({'width':'386px','color':'red'});                                               
                    
                }else if(data.status == undefined){
                    $('#ajax-info').html('Có lỗi trong quá trình xử lý').removeClass().addClass('content-warning');
                }
            }

             //Liên hệ
                $('#contact-me').submit(function(){
                    $(this).ajaxSubmit(options); 
                    return false; 
                });

            //end liện hệ
            </script>
            <!-- END LIÊN HỆ -->
            <script type="text/javascript" src="<?php echo TEMPLATE_URL;?>/default/js/jquery.min.js"></script>
            <script type="text/javascript" src="<?php echo TEMPLATE_URL;?>/default/js/jquery.form.js"></script>
        </div>
    </div>
</div>
<input type="hidden" id="txtEmailToTA" value="ngoclinhnguyen888@gmail.com">

<script type="text/javascript">
function StatisticsClick(kind,idStatistics,isMBND) {
    var param = {
        kind : kind,
        idStatistics:idStatistics,
        isMBND : isMBND
    };
    $.post(pathClientAjax + "services/PropertyHandler.asmx/StatisticsClick", param);
        }
</script>
            
<div class="topAgentPropertyList">
    <div class="contentDetail">
        <h2 class="leftTitle">BĐS của <?php echo $fullname;?></h2>
        <div class="leftSmallContent">
            
            
        <div class="dataTables_wrapper"><!--load--></div>
        <?php
        $page       = !empty($this->arrParam['page']) ? $this->arrParam['page'] : 1;
        $LinkPage   = $this->basePath()."/".$this->arrParam['module']."/realestate/realestate-of-agency/page/".$page;
        ?>
        <script type="text/javascript">

        $(document).ready(function(){
            $(".loading").show();
            var idUser = '<?php echo $this->item->id;?>';
            var page = '<?php echo $page;?>';
            var name = '<?php echo $this->arrParam["name"];?>';
            $.ajax({
                url     : '<?php echo $LinkPage;?>',
                type    : 'GET',
                data    : {page: page, idUser: idUser, name: name},
                cache   : false,
                success : function(data,status){
                    $("div.dataTables_wrapper").html(data);
                    $(".loading").fadeOut(1000);
                }
            });
        });

        </script>
            
            
            





<script type="text/javascript">
    _ITEMS_PAGES=$("#idItemPage").val();
    var tps = (parseInt($("#hTotalRows").val())%_ITEMS_PAGES)!=0?(parseInt(parseInt($("#hTotalRows").val())/(_ITEMS_PAGES))+1):parseInt(parseInt($("#hTotalRows").val())/(_ITEMS_PAGES));
    nvgPaging.mjDrawLbPageListingPiNoAjaxLi(tps, $("#hCurrentPage").val(), "dvPagingDefault",$("#idPage").val(),$("#idQs").val(),$('#pPath').val());
    nvgPaging.loadMiddleListBanner("divMiddleListBanner","middlelistbanner");
</script>

           
        </div>
    </div>
</div>

        </div>
          <div class="rightMainContent">
  <?php echo $this->blkAdsColumnRight();?>     


  <script type="text/javascript">
      function DisplayMe(div) {
          document.getElementById(div).style.display = '';
      }

      $('#txtEmailNL').click(function (event) {$('html').one('click', function () {$("#infoDiv").hide();});event.stopPropagation();});$('#txtFullName').click(function (event) {$('html').one('click', function () {$("#infoDiv").hide();});event.stopPropagation();});
  </script>



 

    <script type="text/javascript">
        $("#divTopAgent .padded .infoGroup img").error(function (event) {
            $(this).attr("src", "http://images.videonhadat.com.vn/avatar_male_84x94.gif");
        })
    </script> 
      
  <?php echo $this->blkRegisterEmail();?> 
  <?php echo $this->blkNhanXet();?> 
  <?php echo $this->blkLienKet();?> 
  </div>
    </div>