
<?php
$isXmlHttpRequest = $this->isXmlHttpRequest;
if($isXmlHttpRequest == true){
    $xhtml = '';
    if(!empty($this->items)){
        foreach ($this->items as $key => $item) {
            $fullname       = $item['fullname'];
            $avatar         = (!empty($item['avatar']))  ? UPLOAD_URL .'/avatar/'.$item['avatar'] :  TEMPLATE_URL .'/admin/images/NoImage.jpg';
            $diachi         = $item['diachi'];
            $phone          = $item['phone'];
            $email          = $item['email'];
            $introduced     = $item['introduced'];
            $linkDetail     = $this->url('DetailAgencyRoute',array(
                'module'    =>  'home',
                'controller'=>  'agency',
                'action'    =>  'detail',
                'name'      =>  \ZendVN\Url\FriendlyLink::filter($fullname),
                'id'        =>  $item['id'],
            ));
            $xhtml          .='<li><div class="content"><div class="infoGroup"><a href="'.$linkDetail.'" title="'.$fullname.'" class="avatar"><img src="'.$avatar.'" width="95" alt="'.$fullname.'" title="'.$fullname.'"></a><div class="text"><h3><a href="'.$linkDetail.'" title="'.$fullname.'">'.$fullname.'</a>
            <span>Điện thoại: '.$phone.'</span>
            <span>Địa chỉ: '.$diachi.'</span>
            <span>Email: '.$email.'</span>
            </h3><p>'.$introduced.'</p></div></div></li>';
        }
    }
?>

<div class="topAgentList">
    <h2 class="leftTitle"><b>Danh sách các nhà môi giới</b></h2>
    <div id="MainContent_ucTopAgentIndexList_divResult" class="leftSmallContent"><input id="hCurrentPage" type="hidden" value="1"><input id="hTotalRows" type="hidden" value="6"><input id="hTotalRowsAgent" type="hidden" value="">
        <ul class="leftListing2">
            <?php echo $xhtml;?>
      

        </ul>

    <?php
    $paramsUrl  = array(
        'module'        =>  'home',
        'controller'    =>  'agency',
        'action'        =>  'category',
        'cityname'      =>  $this->arrParam['cityname'],
        'cityid'        => $this->arrParam['cityid'],
        'page'          =>  '1',
    );
    echo $this->paginationControl($this->paginator , 'sliding' , 'home/business/paginator.phtml', array(
        'router'    => 'AgencyBusinessRoute',
        'arrParam'  =>$paramsUrl,
    )); 
    ?>

<script type="text/javascript">
    _ITEMS_PAGES=$("#idItemPage").val();
    var tps = (parseInt($("#hTotalRows").val())%_ITEMS_PAGES)!=0?(parseInt(parseInt($("#hTotalRows").val())/(_ITEMS_PAGES))+1):parseInt(parseInt($("#hTotalRows").val())/(_ITEMS_PAGES));
    nvgPaging.mjDrawLbPageListingPiNoAjaxLi(tps, $("#hCurrentPage").val(), "dvPagingDefault",$("#idPage").val(),$("#idQs").val(),$('#pPath').val());
    nvgPaging.loadMiddleListBanner("divMiddleListBanner","middlelistbanner");
</script>
</div>
</div>



<?php
}else{
    echo 'not ajax';
}
?>
