<?php

$page                = !empty($this->arrParam['page']) ? $this->arrParam['page'] : 1;
$LinkPage            = $this->basePath()."/".$this->arrParam['module']."/business/list/page/".$page;
$linkLoadDistrict    = $this->url('MVC_HomeRouter/action',array(
    'module'=>'home',
    'controller'=>'agency',
    'action'=>'load-select-district'
));



$xhtml = '';
if(!empty($this->items)){
        foreach ($this->items as $key => $item) {
            $fullname       = $item['fullname'];
            $avatar         = (!empty($item['avatar']))  ? UPLOAD_URL .'/avatar/'.$item['avatar'] :  TEMPLATE_URL .'/admin/images/NoImage.jpg';
            $diachi         = $item['diachi'];
            $phone          = $item['phone'];
            $email          = $item['email'];
            $introduced     = $item['introduced'];
            $linkDetail     = $this->url('DetailAgencyRoute',array(
                'module'    =>  'home',
                'controller'=>  'agency',
                'action'    =>  'detail',
                'name'      =>  \ZendVN\Url\FriendlyLink::filter($fullname),
                'id'        =>  $item['id'],
            ));

            $xhtml          .='<li><div class="content"><div class="infoGroup"><a href="'.$linkDetail.'" title="'.$fullname.'" class="avatar"><img src="'.$avatar.'" width="95" alt="'.$fullname.'" title="'.$fullname.'"></a><div class="text"><h3><a href="'.$linkDetail.'" title="'.$fullname.'">'.$fullname.'</a>
            <span>Điện thoại: '.$phone.'</span>
            <span>Địa chỉ: '.$diachi.'</span>
            <span>Email: '.$email.'</span>
            </h3><p>'.$introduced.'</p></div></div></li>';
        }
    }


//Search Name
$linkSearch         = $this->url('MVC_HomeRouter/action',array('controller'=>'agency','action'=>'search'));

?>
<div class="pageWrap">
        <div class="leftMainContent">
            
        <?php echo $this->formSearchAgency;?>
        <div class="topAgentList">
    <h2 class="leftTitle"><b>Danh sách các nhà môi giới</b></h2>
    <div id="MainContent_ucTopAgentIndexList_divResult" class="leftSmallContent"><input id="hCurrentPage" type="hidden" value="1"><input id="hTotalRows" type="hidden" value="6"><input id="hTotalRowsAgent" type="hidden" value="">
        <ul class="leftListing2">
            <?php echo $xhtml;?>
      

        </ul>

    <?php
    $paramsUrl  = array(
        'module'        =>  'home',
        'controller'    =>  'agency',
        'action'        =>  'search',
    );
    echo $this->paginationControl($this->paginator , 'sliding' , 'home/project/paginator.phtml', array(
        'router'    => 'MVC_HomeRouter/action',
        'arrParam'  =>$paramsUrl,
        'urlQuery'  => '?q='.$this->arrParam['q'].'&city='.$this->arrParam['cityid'].'&district='.$this->arrParam['iddistrict']
    )); 
    ?>

<script type="text/javascript">
    _ITEMS_PAGES=$("#idItemPage").val();
    var tps = (parseInt($("#hTotalRows").val())%_ITEMS_PAGES)!=0?(parseInt(parseInt($("#hTotalRows").val())/(_ITEMS_PAGES))+1):parseInt(parseInt($("#hTotalRows").val())/(_ITEMS_PAGES));
    nvgPaging.mjDrawLbPageListingPiNoAjaxLi(tps, $("#hCurrentPage").val(), "dvPagingDefault",$("#idPage").val(),$("#idQs").val(),$('#pPath').val());
    nvgPaging.loadMiddleListBanner("divMiddleListBanner","middlelistbanner");
</script>
</div>
</div>
       
        <script type="text/javascript">

        $(document).ready(function(){

             //Load quận huyện
            $("#city").change(function(){
                var city = $("#city option:selected").val();
                
                loadDistrict(city);
            });

            $("#search-submit").click(function(){
                var q           = $("#txtName").val();
                var city        = $("#city option:selected").val();
                var district    = $("#district option:selected").val();

                var linkSearchProject = '<?php echo $linkSearch;?>?q='+ q + '&city=' + city + '&district=' + district + '&page=1';

                //Tìm kiếm tất cả thông tin
                if(q != '' || city != ''  || district != ''){
                    window.location = linkSearchProject;
                }else if(q == '' && city == ''  && district == ''){
                     alert("Bạn phải nhập từ khóa, hoặc chọn các tiêu chí");
                }
                
            });
           
        });

         function loadDistrict(city){
            $.ajax({
                url     : '<?php echo $linkLoadDistrict;?>',
                type    : 'GET',
                data    : {city : city},
                success: function(data){
                    $("#district").html(data);
                },
                complete: function(){

                }
            });
        }

        </script>

           
        

    </div>
    <div class="rightMainContent">
        <?php echo $this->contentRightColumn;?>
    </div>
</div>