<?php
$isXmlHttpRequest = $this->isXmlHttpRequest;
if($isXmlHttpRequest == true){


$myForm = $this->myForm;
$myForm->prepare();
$elementGoogleAnalyticsCode     = $myForm->get('GoogleAnalyticsCode');
$elementactiveAccountEmail      = $myForm->get('activeAccountEmail');
$elementlimitSendEmailMarketing = $myForm->get('limitSendEmailMarketing');
$elements = array(
    array(
        'label'             =>  $this->formLabel($elementGoogleAnalyticsCode),
        'input'             =>  $this->formElement($elementGoogleAnalyticsCode),
        'class'             =>  'col-sm-9',
        'required'          =>  '*',
        'tooltiptitle'      =>  'Google Analytics Code (Sử dụng đoạn mã của Google để thống kê phân tích website)',
        'tooltipmessage'    =>  'Google Analytics Code (Sử dụng đoạn mã của Google để thống kê phân tích website)',
    ),

    array(
        'label'             =>  $this->formLabel($elementactiveAccountEmail),
        'input'             =>  $this->formElement($elementactiveAccountEmail),
        'class'             =>  'col-sm-9',
        'required'          =>  '',
        'tooltiptitle'      =>  'Kích hoạt tài khoản qua email',
        'tooltipmessage'    =>  'Kích hoạt tài khoản qua email',
    ),

     array(
        'label'             =>  $this->formLabel($elementlimitSendEmailMarketing),
        'input'             =>  $this->formElement($elementlimitSendEmailMarketing),
        'class'             =>  'col-sm-9',
        'required'          =>  '*',
        'tooltiptitle'      =>  'Giới hạn gửi email marketing(Số lần gửi trong một chiến dịch Email)',
        'tooltipmessage'    =>  'Giới hạn gửi email marketing(Số lần gửi trong một chiến dịch Email)',
    ),

    
    
);
          
?>

<table class="admintable" style="width: 100%;">
    <?php  echo $this->form()->openTag($myForm);
    echo $this->partialLoop('admin/form-group.phtml',$elements);
    echo $this->form()->closeTag();
    ?>
</table>


<?php
}else{
    echo 'not ajax';
}
?>




