<?php
$isXmlHttpRequest = $this->isXmlHttpRequest;
if($isXmlHttpRequest == true){


$myForm = $this->myForm;
$myForm->prepare();
$elementNotice     = $myForm->get('notice');
$elementStatus     = $myForm->get('status');

$elements = array(
 
    array(
        'label'             =>  $this->formLabel($elementNotice),
        'input'             =>  $this->formElement($elementNotice),
        'class'             =>  'col-sm-9',
        'required'          =>  '*',
        'tooltiptitle'      =>  'Thông báo',
        'tooltipmessage'    =>  'Thông báo',
    ),

     array(
        'label'             =>  $this->formLabel($elementStatus),
        'input'             =>  $this->formElement($elementStatus),
        'class'             =>  'col-sm-9',
        'required'          =>  '*',
        'tooltiptitle'      =>  'Trạng thái',
        'tooltipmessage'    =>  'Trạng thái',
    ),

    
    
);
          
?>

<table class="admintable" style="width: 100%;">
    <?php  echo $this->form()->openTag($myForm);
    echo $this->partialLoop('admin/form-group.phtml',$elements);
    echo $this->form()->closeTag();
    ?>
</table>


<?php
}else{
    echo 'not ajax';
}
?>




