<?php
$title          = $this->item['title'];
$description    = $this->item['description'];
$date_time      = $this->item['date_time'];
$content        = $this->item['content'];
$print          =   $this->url('PrintNewsRoute',array(
    'controller'        => 'news',
    'action'            => 'print',
    'id'                => $this->item['id'],
));

//tin tương tự
$xhtml = '';
if(!empty($this->itemsTuongTu)){
    foreach ($this->itemsTuongTu as $key => $item) {
        $urlDetail   = $this->url('DetailNewsRoute',array(
            'controller'        => 'news',
            'action'            => 'detail',
            'namecategory'      => \ZendVN\Url\FriendlyLink::filter($item['name_category']),
            'title'             => \ZendVN\Url\FriendlyLink::filter($title),
            'cid'               => $item['cat_id'],
            'id'                => $item['id'],
            'extension'         => 'html',
        ));
        $xhtml .='<li><a href="'.$urlDetail.'" title="'.$item['title'].'">'.$item['title'].' <span>('.$item['date_time'].')</span></a></li>';
    }
}
?>

<div class="pageWrap">
<?php echo $this->cmsBreadcrumb($this->breadcrumb,array('task'=>'data')) .' '.$this->blkAccountGroup($this->identity());?>
</div>
<div class="pageWrap">
        <div class="leftMainContent">
            
<div id="fb-root" class=" fb_reset"><div style="position: absolute; top: -10000px; height: 0px; width: 0px;"><div><iframe name="fb_xdm_frame_http" frameborder="0" allowtransparency="true" scrolling="no" id="fb_xdm_frame_http" aria-hidden="true" title="Facebook Cross Domain Communication Frame" tabindex="-1" src="http://static.ak.facebook.com/connect/xd_arbiter/7r8gQb8MIqE.js?version=41#channel=faedd442&amp;origin=http%3A%2F%2Fmuabannhadat.com.vn" style="border: none;"></iframe><iframe name="fb_xdm_frame_https" frameborder="0" allowtransparency="true" scrolling="no" id="fb_xdm_frame_https" aria-hidden="true" title="Facebook Cross Domain Communication Frame" tabindex="-1" src="https://s-static.ak.facebook.com/connect/xd_arbiter/7r8gQb8MIqE.js?version=41#channel=faedd442&amp;origin=http%3A%2F%2Fmuabannhadat.com.vn" style="border: none;"></iframe></div></div><div style="position: absolute; top: -10000px; height: 0px; width: 0px;"><div></div></div></div>


<div class="newsDetail">
  <div class="contentDetail">
    <div class="leftSmallContent">
      <h1><?php echo $title;?></h1>
      <div class="likeThisContent top"> 
<small>Chia sẻ bài viết qua:</small>
  <a href="https://www.facebook.com/sharer/sharer.php?u=<?php echo ZendVN\Url\CurrentUrl::get();?>" id="linkShareFacebook" class="facebook rvnfacebook" title="Kết nối chúng tôi trên facebook">
    <img src="<?php echo TEMPLATE_URL;?>/default/images/facebook.png" alt="Facebook" title="Facebook">
  </a>

</div>


      <div class="moreEmailPrint">
        <a href="javascript:void(0);" onclick="window.open('<?php echo $print;?>','_blank','scrollbars=yes,width=700')" title="In bài viết này" class="print" style="border-right:0px solid #ddd;">In bài viết này</a>
        <!--a href="javascript:ShowFormSendMailFriend(37777);" title="Gửi cho bạn bè" class="sendEmailFriend2">Gửi cho bạn bè</a-->
        <span><?php echo $date_time ;?></span>
      </div>
      <b class="textLead"><?php echo $description;?></b>

      <?php echo $content;?>

      
      <div class="moreEmailPrint">
        <a href="javascript:void(0);" onclick="window.open('<?php echo $print;?>','_blank','scrollbars=yes,width=700')" title="In bài viết này" class="print" style="border-right:0px solid #ddd;">In bài viết này</a>
        <!--a href="javascript:ShowFormSendMailFriend(37777);" title="Gửi cho bạn bè" class="sendEmailFriend2">Gửi cho bạn bè</a-->
        <b>Nhật Vy - muabannhadat</b>
      </div>
      

      

      <div style="color:#fff;" onclick="javascript:ListTagNewsEdit(37777,0);">eTags</div>
      
      <div class="likeThisContent">
        <iframe src="//www.facebook.com/plugins/like.php?href=<?php echo ZendVN\Url\CurrentUrl::get();?>&amp;send=false&amp;layout=standard&amp;width=450&amp;show_faces=false&amp;font&amp;colorscheme=light&amp;action=like&amp;height=35" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:450px; height:35px;" allowtransparency="true"></iframe>
        <small>Chia sẻ bài viết qua:</small>
<a href="https://www.facebook.com/sharer/sharer.php?u=<?php echo ZendVN\Url\CurrentUrl::get();?>" id="linkShareFacebook" class="facebook rvnfacebook" title="Kết nối chúng tôi trên facebook">
  <img src="<?php echo TEMPLATE_URL;?>/default/images/facebook.png" alt="Facebook" title="Facebook">
</a>


      </div>
    </div>
  </div>
</div>

<div class="commentFacebook">
  <div class="fb-comments" data-href="http://developers.facebook.com/docs/plugins/comments/" data-numposts="5" data-colorscheme="light"></div>
</div>



<div class="otherListBox">
                <h2 class="leftTitle"><b>Các tin khác</b></h2>
                <div class="leftSmallContent">
                    <ul class="leftLine">
                       <?php echo $xhtml;?>
                        
                    </ul>
                </div>
            </div>


        </div>
   <div class="rightMainContent">
  <?php echo $this->blkAdsColumnRight();?>     


  <script type="text/javascript">
      function DisplayMe(div) {
          document.getElementById(div).style.display = '';
      }

      $('#txtEmailNL').click(function (event) {$('html').one('click', function () {$("#infoDiv").hide();});event.stopPropagation();});$('#txtFullName').click(function (event) {$('html').one('click', function () {$("#infoDiv").hide();});event.stopPropagation();});
  </script>



 

    <script type="text/javascript">
        $("#divTopAgent .padded .infoGroup img").error(function (event) {
            $(this).attr("src", "http://images.videonhadat.com.vn/avatar_male_84x94.gif");
        })
    </script> 
      
  <?php echo $this->blkRegisterEmail();?> 
  <?php echo $this->blkNhanXet();?> 
  <?php echo $this->blkLienKet();?> 
  </div>
</div>