<?php
//giá dự án theo thành phố
$xhtmlCity = '';
if(!empty($this->listCity)){
    foreach($this->listCity as $item){
        $urlCity   = $this->url(
            'CityMarketRoute',
            array('controller'=>'project','action'=>'city','cityname'=>\ZendVN\Url\FriendlyLink::filter($item['name']),'page'=>1,'cityid'=>$item['id']
        ));
        $xhtmlCity      .= '<li><a href="'.$urlCity.'" title="'.$item['name'].'">Giá dự án '.$item['name'].'</a></li>';
    }  
}


//giá dự án theo danh mục
$xhtmlCategory = '';
if(!empty($this->listCategory)){
    foreach($this->listCategory as $item){
        $urlCategory  = $this->url(
            'CategoryMarketRoute',
            array(
                'action'    =>'category',
                'name'      =>\ZendVN\Url\FriendlyLink::filter($item['name']),
                'page'      =>1,
                'id'        =>$item['id']
            )
        );
        $xhtmlCategory      .= '<li><a href="'.$urlCategory.'" title="'.$item['name'].'">Giá '.$item['name'].'</a></li>';
    }  
}

//dự án nổi bật
$listItemHighlight = '';
if(!empty($this->listItemHighlight)){
    foreach($this->listItemHighlight as $item){
         $linkIntro = $this->url('IntroProjectRoute',array(
            'module'        =>  'home',
            'controller'    =>  'project',
            'action'        =>  'intro',
            'title'         =>  \ZendVN\Url\FriendlyLink::filter($item['name']),
            'id'            =>  $item['id'],
            'extension'     =>  'html',
        ));
        $image          =  TEMPLATE_URL .'/admin/images/NoImage.jpg';
        $i = 1;
        if(!empty($item['images'])){
            $images  = \Zend\Json\Json::decode($item['images']);
            foreach ($images as $key => $image) {
                if($i == 1){
                    $image = UPLOAD_URL .'/project/'.$image;
                    break;
                } 
            }
        }
        
        $listItemHighlight      .= '<li><a href="'.$linkIntro.'" title="'.$item['name'].'"><img src="'.$image.'" width="113" alt="'.$item['name'].'" title="'.$item['name'].'"></a><h3><a href="'.$linkIntro.'" title="'.$item['name'].'">'.\ZendVN\Filter\ReadMore::create($item['name'],0,30).'</a></h3></li>';
    }  
}

?>
<div class="pageWrap">
<?php echo $this->cmsBreadcrumb($this->breadcrumb,array('task'=>'data')) .' '.$this->blkAccountGroup($this->identity());?>
</div>
<div class="pageWrap">
        <div class="leftMainContent">
            

          <?php echo $this->searchProject;?>
 <script type="text/javascript">
                
            </script>


<script type="text/javascript">
    SearchGiaBDSDuAn.bindData();
</script>
<div class="shortenPrice">
    <h2 class="leftTitle"><b>Bảng giá dự án <?php echo $this->itemInfoCategory['name'];?> </b></h2>

    <div class="dataTables_wrapper"><!--load--></div>
        <?php
        $page       = !empty($this->arrParam['page']) ? $this->arrParam['page'] : 1;
        $LinkPage   = $this->basePath()."/".$this->arrParam['module']."/market/category-ajax/page/".$page;
        $catid      = (!empty($this->arrParam["id"])) ? $this->arrParam["id"] : "" ;
        $name       = $this->arrParam["name"];
        ?>
        <script type="text/javascript">

        $(document).ready(function(){
            $(".loading").show();
            var page        = '<?php echo $page;?>';
            var catid       = '<?php echo $catid ?>';
            var name        = '<?php echo $name;?>';
            $.ajax({
                url     : '<?php echo $LinkPage;?>',
                type    : 'GET',
                data    : {page: page, catid: catid, name: name},
                cache   : false,
                success : function(data,status){
                    $("div.dataTables_wrapper").html(data);
                    $(".loading").fadeOut(1000);
                }
            });
        });

        </script>
</div>

<script type="text/javascript">
    //<!--
    if ((nvgUtils.getCookie('GAgentID') == null || nvgUtils.getCookie('GAgentID') == "") && $('#hdfKeyWdg').val() != "1") {
        $('#dvgiaDANote').show();
    }
//-->
</script>


            
            
            <div id="MainContent_divLoaiTt">
            </div>
            <a name="attkhacgda"></a>
            



            <div class="propertyKind"><h2 class="leftTitle"><b>Giá dự án theo tỉnh thành</b></h2><div class="leftSmallContent">
              <ul class="leftLine">
                <?php echo $xhtmlCity;?>
              </ul></div></div>
            <div class="propertyKind"><h2 class="leftTitle"><b>Giá loại bất động sản</b></h2><div class="leftSmallContent">
              <ul class="leftLine">
                <?php echo $xhtmlCategory;?>
              </ul></div></div>

             <div class="vipObject company">
            <h2 class="leftTitle"><b>Dự án nổi bật</b></h2>
            <div class="leftSmallContent">
                <div id="nodegalleryDa" style="left:0;"><ul style="width: 1197px; position: relative; left: -283.0664157292731px;">
                    <?php echo $listItemHighlight;?>

                </ul><a onclick="SlideCaroulse(&quot;l&quot;);" href="javascript:" class="previousButton grey" title="Previous"></a><a onclick="SlideCaroulse(&quot;r&quot;);" href="javascript:" class="nextButton grey" title="Next"></a></div>
                
            </div>
        </div>
         <script type="text/javascript">
             self.setInterval("SlideCaroulse('l')", 3000);
             var previousB = 5;
             var noOfSlide = 5;
             var selectedUl = 'div#nodegalleryDa ul';
             var ulWidth = $(selectedUl).width();
             var liWidth = 133;
             
             
        </script>
<script type="text/javascript">
    $("#ulDaVipMainMnu img").error(function (event) {
        $(this).attr("src", "http://muabannhadat.com.vn/images/du-an-noi-bat.jpg");
    })
</script> 
<script type="text/javascript">
    //    $(function () {
    //        LoadNextTopEstate();
    //    });
    var esi = 4;
    function LoadNextTopEstate() {

        $("#ulDaVipMainMnu").html("");

        var countes = 1;
        while (esi < listtopestate.length) {
            if (countes > 4)
                break;
            var htmlinner = listtopestate[esi].es;
            esi++;
            $("#ulDaVipMainMnu").append(htmlinner);
            countes++;
            if (esi > listtopestate.length - 1)
                esi = 0;
        }

        setTimeout("LoadNextTopEstate()", 10000);
        $("#ulDaVipMainMnu img").error(function(event) {
            $(this).attr("src", "http://muabannhadat.com.vn/images/du-an-noi-bat.jpg");
        });
    }    
    if(listtopestate.length>4)
        setTimeout("LoadNextTopEstate()", 10000);
</script>
        </div>
       <div class="rightMainContent">
  <?php echo $this->blkAdsColumnRight();?>     


  <script type="text/javascript">
      function DisplayMe(div) {
          document.getElementById(div).style.display = '';
      }

      $('#txtEmailNL').click(function (event) {$('html').one('click', function () {$("#infoDiv").hide();});event.stopPropagation();});$('#txtFullName').click(function (event) {$('html').one('click', function () {$("#infoDiv").hide();});event.stopPropagation();});
  </script>



 

    <script type="text/javascript">
        $("#divTopAgent .padded .infoGroup img").error(function (event) {
            $(this).attr("src", "http://images.videonhadat.com.vn/avatar_male_84x94.gif");
        })
    </script> 
      
  <?php echo $this->blkRegisterEmail();?> 
  <?php echo $this->blkNhanXet();?> 
  <?php echo $this->blkLienKet();?> 
  </div>
    </div>