
<?php
$isXmlHttpRequest = $this->isXmlHttpRequest;
if($isXmlHttpRequest == true){
$xhtml = '';
if(!empty($this->items)){
    foreach($this->items as $item){
       
        $id             = $item['id'];
        $name           = $item['name'];
        $name_category  = $item['name_category'];
        $area           = $item['area'];
        $cat_id         = $item['cat_id'];
        $pricem2        = $item['price_m2'];
        $address        = $item['name_district'];
        $image          =  TEMPLATE_URL .'/admin/images/NoImage.jpg';
        $i              = 1;
        if(!empty($item['images'])){
            $images  = \Zend\Json\Json::decode($item['images']);
            foreach ($images as $key => $image) {
                if($i == 1){
                    $image = UPLOAD_URL .'/project/'.$image;
                    break;
                } 
            }
        }

        

        $linkDetail = $this->url('IntroProjectRoute',array(
            'module'        =>  'home',
            'controller'    =>  'project',
            'action'        =>  'intro',
            'title'         =>  \ZendVN\Url\FriendlyLink::filter($name),
            'id'            =>  $id,
            'extension'     =>  'html',
        ));

       

      
       
        

        $xhtml .= ' <tr>
                <td rowspan="1">'.$address.'</td>
                <td class="alignLeft"><a title="'.$name.'" href="'. $linkDetail.'">'.$name.'</a></td>
                <td>'.$name_category.'</td>
                <td>Đang thi công</td>
                <td>'.$area.'</td>
                <td>'.$pricem2.'</td>
            </tr>';

                    

                             
    }
}

?>
   <div class="leftSmallContent">
    
        <table>
            <tbody><tr>
                <th>Quận/Huyện</th>
                <th class="w30 alignLeft">Tên dự án</th>
                <th>Loại BĐS</th>
                <th>Tiến độ</th>
                <th>Diện tích (m2)</th>
                <th>Giá (triệu/m2)</th>
            </tr>
            <?php echo $xhtml;?> 
           
            </tbody>
        </table>


     <?php
     $paramsUrl  = array(
        'module'        => 'home',
        'controller'    => 'business',
        'action'        => 'city',
        'cityname'      =>  $this->arrParam['cityname'],
        'page'          => '1',
        'cityid'        => $this->arrParam['cityid'],
        'extension'     => 'html',
    );
    echo $this->paginationControl($this->paginator , 'sliding' , 'home/business/paginator.phtml', array(
        'router'    => 'CityMarketRoute',
        'arrParam'  =>$paramsUrl,
    )); 
 ?>
     <small id="dvgiaDANote" style="display:none;">Lưu ý: Bạn phải <a href="javascript:;" onclick="LoginRequest('bang-gia-bat-dong-san/');">đăng nhập</a> vào hệ thống để xem bảng giá đầy đủ của nhiều dự án trên toàn quốc</small>
   </div>

  








<?php
}else{
    echo 'not ajax';
}
?>
