


<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head><title>
	Print
</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

    <style type="text/css">
body{ font-size: 13px; font-family: Arial, Helvetica, sans-serif;}
p{ margin-top: 20px; margin-bottom: 20px;}
</style>
<meta name="keywords" content="nha dat, bat dong san, du an, nhà đất, bất động sản, dự án" /></head>
<body onload="javascript:window.print();">
    <form method="post" action="PrintNews.aspx?id=37777" id="form1">
<div class="aspNetHidden">
<input type="hidden" name="__VIEWSTATE" id="__VIEWSTATE" value="/wEPDwUKLTMxOTMyMTQyN2RkyPiLwCusccWcZWNV1IJPruV1rB4QMaiaSEfca3l1g20=" />
</div>

<div class="aspNetHidden">

	<input type="hidden" name="__VIEWSTATEGENERATOR" id="__VIEWSTATEGENERATOR" value="B5C9E183" />
</div>
    <div>
    <center>
		<div class="WidthpagePrint">
    		<div class="HeaderPrint">
        		<img src="images/header_print.jpg" width="600" height="80" alt=""/>
			</div>
			 <div class="ContentPrint">
        <h1 class="Bold_ff6"><?php echo $this->item['title'];?></h1>
		<font class="Normal_808"><?php echo $this->item['date_time'];?></font>
		<div class="mar_b10">
            <b><?php echo $this->item['description'];?></b>
		</div>
		<p class="pad_t5">
			<?php echo $this->item['content'];?>
		</p>
</div>
			<div class="FooterPrint">
        		<div class="BgLinksite"><div class="DesLinksite"><a href="#" class="LinkFooter"></a></div></div>
			</div>
		</div>
	</center>	
       
    
    </div>
    </form>
</body>
</html>
