<?php
$ssFilter   = $this->arrParam['ssFilter'];

//==========Messages=========================//
$messages   = $this->flashMessenger()
                    ->setMessageOpenFormat('<div id="cph_Main_ctl00_notification_rptNotice_divMessage_0" class="alert alert-success">')
                    ->setMessageSeparatorString('')
                    ->setMessageCloseString('<button data-dismiss="alert" class="close">×</button>')
                    ->render('success',array('success message'));




//==========CREATE SEARCH FORM===============//


$frmTextBox = $this->cmsInput('keywords_file','keywords_file','text',array('value'=>$ssFilter['keywords_file'],'maxlength'=>'100','placeholder'=>'Nhập keywords','style'=>'width:20%;'));

$linkSearch = $this->basePath($this->currentController . '/filter/search/null/null/1');
$frmSubmit  = $this->cmsInput('search','search','button',array('value'=>'Lọc','class'=>'btn','onclick'=>'OnSubmitForm(\''.$linkSearch.'\')','style'=>'width:5%;'));

$linkClear  = $this->basePath($this->currentController . '/filter/search/null/null/0');
$frmClear   = $this->cmsInput('clear','clear','button',array('value'=>'Bỏ lọc','class'=>'btn','onclick'=>'OnSubmitForm(\''.$linkClear.'\')','style'=>'width:8%;'));


//Tìm kiếm theo field
$arrOptions = array(
    array('id'=>'title','name'=>'Thư mục'),
    array('id'=>'id','name'=>'ID'),
);
$frmField   = $this->cmsSelect('field',$ssFilter['field'],$arrOptions,'no-level',array('style' =>'width:15%;'));


$frmTieuDe = $this->cmsInput('name','name','text',array('value'=>$ssFilter['keywords'],'maxlength'=>'100','placeholder'=>'Tên file','style'=>'width:400px;'));



$frmSearch  = $frmTextBox . '  ' .$frmSubmit . ' '.$frmClear;


//==========Select Record====================//
$arrOptions = array(
    array('id'=>5,'name'=>'5 tập tin / Trang'),
    array('id'=>10,'name'=>'10 tập tin / Trang'),
    array('id'=>20,'name'=>'20 tập tin / Trang'),
    array('id'=>30,'name'=>'30 tập tin / Trang'),
    array('id'=>50,'name'=>'50 tập tin / Trang'),
    array('id'=>100,'name'=>'100 tập tin / Trang'),
);
$linkReoord   = $this->currentController . '/filter/record';
$frmRecord    = $this->cmsSelect('record',$ssFilter['record'],$arrOptions,'no-level',array('style' =>'width:60%','onchange'=>'OnSubmitForm(\''.$linkReoord.'\')'));

?>

<form name="appForm" id="appForm" method="post" action="" enctype="multipart/form-data">

<?php include('sublink/index.php');?>
    <!--Nội dung load ở đây-->                   
    <div id="cph_Main_ContentPane">

        <div class="widget">
            <?php include('toolbar/index.php');?>

            <div class="widget-body">
                <div id="cph_Main_ctl00_notification_divNotice" style="padding-top:10px;">
                <?php echo $messages ;?> 
                <?php echo $this->errorMessages($this->error,'admin');?> 
                </div>

                <div class="row-fluid">
                    <div class="span3">
                        <div id="sample_1_length" class="dataTables_length">    
                        <?php echo $frmRecord;?>
                        </div>
                    </div>
                    <div class="span9 form-search pull-right text-right">
                       <?php echo $frmSearch;?> <span>Chọn tất cả file:</span> <input type="button" class="btn"value="Check All" onclick="this.value=check(this.form.cid)"> <span></span><img src="<?php echo TEMPLATE_URL;?>/admin/images/uploadicon.png" title ="Upload file" id="clicker">
                    
                    </div>

                 <!--POP UP upload-->    
                <div id="popup-wrapper">
                <a href="#" id="close-btn">Close</a>
                <br />
                <span style="color: red;"><?php echo 'Chọn file tải lên lưu ý chỉ được upload file có dạng : jpg,png,gif,txt,rar,zip,exe,doc,docx,xls,pdf Và không quá 5MB';?></span><br />
                <input type="file" name="file" id="img" 0="">
                <br /><span><?php echo 'Tên File';?></span><br />
                <?php echo $frmTieuDe;?>
                <br />
                <input type="submit" name="upload" id="upload" class="btn" value="Bắt đầu tải lên">
               </div>   
                <!--POP UP upload-->     
                <div class="dataTables_wrapper">
                        <!-- V? tri load datat-->
                </div>
        
                <style type="text/css">
                #tooltip { position: absolute; z-index: 10102; background-color: #FFF; padding: 5px; border: solid 3px #cccccc; display: block; width: 350px; text-align: center; }
                </style>

        </div>
</div>


<?php
$page       = !empty($this->arrParam['page']) ? $this->arrParam['page'] : 1;
$LinkPage   = $this->basePath()."/".$this->arrParam['module']."/".$this->arrParam['controller']."/file-list/page/".$page;
?>
<script type="text/javascript">

$j(document).ready(function(){
    $j(".loading").show();
    $j.ajax({
        url     : '<?php echo $LinkPage;?>',
        type    : 'GET',
        data    : {id : '<?php echo $this->arrParam['id'];?>'},
        cache   : false,
        success : function(data,status){
            $j("div.dataTables_wrapper").html(data);
            $j(".loading").fadeOut(1000);
            console.log(data);
        }
    });
});

</script>

<link href="<?php echo  TEMPLATE_URL;?>/admin/css/modalPopLite1.3.0.css" rel="stylesheet" type="text/css" />
<script src="<?php echo  TEMPLATE_URL;?>/admin/js/modalPopLite1.3.0.min.js" type="text/javascript"></script>
<script type="text/javascript">
$j(function () {
    $j('#popup-wrapper').modalPopLite({ openButton: '#clicker', closeButton: '#close-btn', isModal: true });
});
</script>

<script type="text/javascript">
var checkflag = "false";
function check(field) {
  if (checkflag == "false") {
    for (i = 0; i < field.length; i++) {
      field[i].checked = true;
    }
    checkflag = "true";
    return "Uncheck All";
  } else {
    for (i = 0; i < field.length; i++) {
      field[i].checked = false;
    }
    checkflag = "false";
    return "Check All";
  }
}

</script>